-- ============================================================================
-- ADENDA — tipo de contrato y serie propia (AD).  8-sep-2026, encargo del owner
-- ----------------------------------------------------------------------------
-- PARA QUE. Modificar un contrato YA FIRMADO sin rehacerlo. El contrato madre se
-- queda intacto y firmado; la adenda es una pagina que dice que se modifica y
-- ratifica el resto. Hasta hoy habia dos salidas y las dos malas:
--   · anular la firma y reeditar  -> el comprador vuelve a firmar el contrato
--     entero y se pierde la traza de QUE cambio;
--   · duplicarlo en uno nuevo     -> dos documentos vivos sobre la misma
--     operacion, sin vinculo entre ellos.
-- El owner lo pidio con CC00014 delante: «el cliente firmo y requiere una
-- modificacion, es un conazo estar asi».
--
-- TIPO PROPIO, no reutilizar uno existente: `TIPO_SLUG` en app.html es un mapa
-- inverso tipo->slug, asi que compartir tipo hace que reabrir un documento
-- guardado cargue la plantilla equivocada. Es el mismo motivo por el que ya
-- nacieron las series CA, CH, C2 y CP.
-- SERIE PROPIA (AD): por el numero tiene que saberse con que texto se firmo.
--
-- SIN PRECIO A PROPOSITO. La adenda no declara `precio_total`. Si lo hiciera,
-- Operaciones sumaria el importe otra vez sobre la misma operacion — el fallo
-- que ya dio 328.000 EUR por una villa de 164.000 (ver vocabulario.js).
--
-- ⚠️ LA FUNCION Y EL CHECK SE REESCRIBEN DESDE SU DEFINICION VIVA, leida con
-- `pg_get_functiondef` / `pg_get_constraintdef`, NUNCA desde este directorio:
-- estos ficheros van por detras de produccion con facilidad, y aplicar una copia
-- vieja borraria series enteras sin decir nada. Al anadir la rama 16 (adenda) la
-- funcion viva tenia 15.
--
-- APLICADO en produccion el 8-sep-2026 (migracion `adenda_tipo_y_serie_ad`) y
-- verificado con un insert dentro de una transaccion revertida: devolvio
-- AD00001. La secuencia se dejo en 1 con `setval(..., 1, false)` para que la
-- primera adenda real sea AD00001 y no AD00002.
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: (fichero de ALTER/INSERT, sin CREATE)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260908083655_adenda_tipo_y_serie_ad.sql
-- ============================================================================
