-- Auditor de la firma electronica — 15-ago-2026
--
-- POR QUE EXISTE. El 15-ago aparecieron dos contratos firmados por el comprador
-- que llevaban semanas sin cerrarse, y nadie lo sabia:
--   · CC00007 (Juan Ramon Sanchez Garcia) firmado el 1-ago
--   · CR00020 (Jorge Miguel Domingo Berenguer) firmado el 14-ago
-- Los dos son contratos de DOS compradores. El primero firmo, y la cadena se
-- paro sin que el segundo llegara a recibir su enlace:
--   · en CR00020 la segunda compradora (Mayka Nunez Saez) NO TIENE EMAIL en el
--     contrato, asi que `firma-submit` no pudo generarle el enlace. La funcion
--     hace exactamente lo que debe -- lo mete en `avisosCadena` y responde
--     ok:true con avisos -- pero ese aviso viaja al NAVEGADOR DEL COMPRADOR y a
--     `console.error`. El equipo no lo ve en ningun sitio.
--   · CC00007 es anterior al 7-ago, cuando el enlace del siguiente firmante lo
--     generaba un operador a mano. Nadie lo genero.
--
-- El diseno de `firma-submit` ya preveia este estado: marca la firma ANTES de
-- bloquear el contrato a proposito, y su comentario dice que si algo falla
-- «queda una firma registrada sin contrato bloqueado — DETECTABLE Y REPARABLE».
-- La decision es correcta. Lo que faltaba era el detector. Esto es el detector.
--
-- MIENTRAS UNA CADENA ESTA PARADA el contrato sigue EDITABLE, asi que el texto
-- que el primer comprador ya firmo se puede modificar. Ese es el riesgo real, no
-- el PDF que falta.
--
-- CRITERIO: preciso antes que exhaustivo. Un auditor que grita por cosas
-- normales se ignora, y entonces es peor que no tenerlo. Se descartaron a
-- proposito tres «anomalias» que al medirlas eran ruido:
--   · firma `firmado` sin `pdf_path` -> normal en las firmas INTERMEDIAS de una
--     cadena: el PDF solo se sella con la ULTIMA. Se probo a avisar cuando el
--     contrato ya estaba cerrado y aun asi faltaba, y salieron 6 contratos: los
--     SEIS con su PDF en su sitio y solo la firma intermedia sin ruta propia,
--     o sea 100% falsos positivos. Regla retirada el mismo dia que se escribio.
--     `pdf_path` por firma es informativo; la prueba es `contratos.pdf_firmado_path`.
--   · contrato bloqueado sin ninguna firma electronica -> normal: es «Subir
--     firmado» a mano, con el PDF en su sitio. Hoy son 3 y los 3 son legitimos.
--   · enlaces pendientes -> una cadena a medias es un estado sano mientras el
--     enlace siga vivo.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: auditoria_firmas
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260815001234_auditoria_firmas.sql
--   supabase/migrations/20260815001341_auditoria_firmas_sin_ruido.sql
--   supabase/migrations/20260815011928_auditoria_firmas_solo_equipo.sql
--   supabase/migrations/20260817001738_auditoria_firmas_regla_procesando_atascado.sql
--   supabase/migrations/20260824044529_auditoria_firmas_exige_agente.sql
--   supabase/migrations/20260911031743_auditoria_firmas_y_obra_respetan_el_alcance.sql
-- ============================================================================
