-- destructivo-ok: `create or replace function`, no borra filas ni objetos.
-- ════════════════════════════════════════════════════════════════════════════
-- auditoria_firmas() NO COMPROBABA PERMISO — 24-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Hallazgo de Desarrollo (auditoría pedida por el owner): a diferencia de sus
-- hermanas `contratos_equipo()`, `facturas_equipo()`, `contrato_firmas_equipo()`,
-- `facturas_pendiente_equipo()` y `uso_almacenamiento()` (todas con
-- `where public.es_agente()` o un `raise exception` si no lo es),
-- `auditoria_firmas()` no llevaba NINGÚN gate. Es `security definer`, así que
-- corre saltándose la RLS de `contratos`/`contrato_firmas` por diseño — sin el
-- gate, cualquier sesión `authenticated` podía llamarla directamente
-- (`POST /rest/v1/rpc/auditoria_firmas`), incluida la de un COMPRADOR logueado
-- en `/portal/` (que sí es `authenticated`, solo que con
-- `app_metadata.portal=true` en vez de agente) — y recibir número de contrato,
-- nombre del comprador y estado de firma de TODOS los contratos del estudio,
-- de cualquier cliente. Confirmado con `get_advisors(security)`:
-- `has_function_privilege` daba `true` para `authenticated` sin más filtro.
--
-- Es `language sql` (no plpgsql), así que no hay `if/raise` de por medio: se
-- envuelve la consulta entera y se filtra el resultado por `es_agente()` —
-- una sesión que no lo es recibe CERO filas, igual que ya hacen las funciones
-- hermanas. No se toca ni una línea de las cinco reglas de auditoría.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: auditoria_firmas
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260815001234_auditoria_firmas.sql
--   supabase/migrations/20260815001341_auditoria_firmas_sin_ruido.sql
--   supabase/migrations/20260815011928_auditoria_firmas_solo_equipo.sql
--   supabase/migrations/20260817001738_auditoria_firmas_regla_procesando_atascado.sql
--   supabase/migrations/20260824044529_auditoria_firmas_exige_agente.sql
--   supabase/migrations/20260911031743_auditoria_firmas_y_obra_respetan_el_alcance.sql
-- ============================================================================
