-- ============================================================================
-- Vigilancia del almacenamiento — 31-jul-2026
-- ----------------------------------------------------------------------------
-- Medido el 31-jul: 162 MB de 1 GB (15%), pero el ritmo real es 14,25 MB/día y
-- eso son ~60 DÍAS DE MARGEN. Un porcentaje bajo no tranquiliza si el ritmo se
-- lo come en dos meses, y por eso el aviso mira el margen, no solo el %.
--
-- Corre en la propia base de datos (pg_cron) y avisa por el mismo endpoint de
-- correo que usa el resto de la suite (pg_net → api/send_email.php). Sin
-- servicio externo que mantener ni credencial nueva.
--
-- Se separa `_uso_almacenamiento()` (el cálculo, sin permisos) de
-- `uso_almacenamiento()` (lo que llama el panel, con `es_agente()`): el cron
-- corre como postgres y no tiene JWT, así que compartir la función con el guard
-- dentro lo dejaría fallando en silencio todas las noches.
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: agentes, avisos_almacenamiento, revisar_almacenamiento
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090740_rls_propiedad_contratos_facturas.sql
--   supabase/migrations/20260730044257_storage_update_snapshots_pendientes.sql
--   supabase/migrations/20260731043211_documentacion_bucket_e_indice.sql
--   supabase/migrations/20260731043542_aviso_almacenamiento_cron.sql
--   supabase/migrations/20260805023613_portal_comprador.sql
--   supabase/migrations/20260807021850_unidades_catalogos_proyecto_tipo.sql
--   supabase/migrations/20260807024457_unidades_catalogos_policies_to_authenticated.sql
--   supabase/migrations/20260807043910_contratos_facturas_visibilidad_por_agente.sql
--   supabase/migrations/20260811034823_recibi_aplicaciones_reforma_facturacion.sql
--   supabase/migrations/20260811034859_bucket_justificantes.sql
--   supabase/migrations/20260811035518_recibi_aplicaciones_delete_propio.sql
--   supabase/migrations/20260817131756_storage_borrar_solo_snapshots_pendientes.sql
--   supabase/migrations/20260901021433_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260901120000_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260908040626_aviso_almacenamiento_enlace_intranet.sql
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260911031517_equipo_deja_de_saltarse_la_rls.sql
--   supabase/migrations/20260911033802_proyectos_solo_los_asignados.sql
--   supabase/migrations/20260911035515_solo_admin_da_de_alta_proyectos.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
--   supabase/migrations/20260918021400_storage_deja_de_ser_una_carpeta_compartida.sql
--   supabase/migrations/20260922133000_facturas_congela_contrato_numero_security_invoker.sql
-- ============================================================================
