-- destructivo-ok: DROP TRIGGER/CREATE OR REPLACE FUNCTION son sustituciones
-- (mismo nombre, misma forma, se amplía una que ya existía), no retiradas de
-- capacidad. Cero DELETE de filas, cero RLS desactivada, cero TRUNCATE.
-- ════════════════════════════════════════════════════════════════════════════
-- AVISO POR CORREO A sales_manager/project_manager EN CAMBIO DE ESTADO — 10-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Parte 2 del encargo de roles (modelo de acceso en
-- permisos_agente_solo_lo_suyo_y_managers.sql). Esta es la mitad de "avisos":
-- contrato bloqueado (firmado), solicitud de pago resuelta, unidad que avanza
-- de estado — para los managers asignados al proyecto de cada fila.
--
-- MISMO PATRÓN que facturacion_automatica.sql (18-ago-2026): pg_cron + secreto
-- de Vault + `net.http_post` a una Edge, NUNCA un trigger llamando a red
-- directamente. Un trigger que bloqueara la transacción del usuario con I/O de
-- red convertiría un fallo de SMTP (ya conocido: 502 de Hostinger) en un
-- contrato que no se guarda. El trigger solo dEJA la fila en `notificaciones`
-- con `email_pendiente=true`; la Edge `avisos-manager` la recoge y la envía.
--
-- MINIMIZACIÓN (Legal, revisión previa 10-sep, CEO/flujos/revision_previa.md):
-- el correo lleva nombre + proyecto + estado + enlace. NUNCA pasaporte,
-- nacionalidad ni domicilio — ese dato sigue detrás de la RLS, tras el enlace,
-- no viaja por email.

-- ── 1. Cómo se sabe qué avisos faltan por salir como correo ─────────────────

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: _avisar_managers, _trg_contrato_bloqueado_aviso_manager, _trg_solicitud_pago_aviso, _trg_unidad_estado_aviso_manager, cron_avisos_manager_secret, notificaciones_email_pendiente_idx, son, trg_contrato_bloqueado_aviso_manager, trg_unidad_estado_aviso_manager
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260909071823_solicitudes_pago.sql
--   supabase/migrations/20260909073555_solicitudes_pago_pagos_a_agentes.sql
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260910091817_avisos_manager_email.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260911013643_proyectos_supervisados_separado.sql
--   supabase/migrations/20260914090558_comisiones_equipos_venta.sql
--   supabase/migrations/20260914093532_comisiones_devengadas_manager_no_veia_al_closer.sql
-- ============================================================================
