-- ============================================================================
-- Borrar una operación entera — 31-jul-2026 (última reescritura: 22-sep-2026)
-- ----------------------------------------------------------------------------
-- Una "operación" no es un contrato: es el contrato padre, los que cuelgan de
-- él (reserva → bloqueo → obra), sus enlaces de firma y sus facturas. Borrar
-- solo el padre dejaba los hijos huérfanos, los enlaces de firma VIVOS —o sea,
-- alguien con el enlace podía seguir firmando un contrato que ya no existe— y
-- las facturas apuntando al vacío.
--
-- Qué hace con cada cosa, y por qué:
--   · enlaces de firma pendientes  → ANULADOS. Un token vivo de un contrato
--     borrado es un documento que se puede firmar sin que nadie lo vea venir.
--   · facturas emitidas            → ANULADAS, no borradas. Borrarlas deja un
--     hueco en la serie fiscal que un contable no puede explicar; anularlas deja
--     el rastro, que es justo lo que hace falta.
--   · comisión ya devengada        → PURGADA (comisiones_devengadas + su
--     solicitud_pago), salvo que esa solicitud ya esté 'pagada' — en ese caso
--     la función para en seco sin borrar nada. Decisión explícita del owner
--     (22-sep-2026), ver
--     supabase/migrations/20260922134500_borrar_operacion_purga_comision_devengada.sql
--     para el porqué completo (hallazgo de Administración tras el fix de
--     facturas_contrato_obligatorio, que hizo alcanzable por primera vez este
--     camino: antes el CHECK de facturas fallaba antes de llegar aquí), y
--     supabase/migrations/20260922141500_borrar_operacion_gate_pagada_no_cerrada.sql
--     para la corrección del nombre del estado (el esquema real usa 'pagada'
--     + pago_referencia/pagado_en, no 'cerrada'/factura_id como en la
--     migración original de solicitudes_pago), y
--     supabase/migrations/20260922143000_borrar_operacion_gate_pagada_cubre_closer.sql
--     porque una comisión de CLOSER pagada no lleva solicitud_id
--     (comisiones_devengadas_solicitud_solo_manager lo exige NULL para
--     closer) — el gate mira también el estado propio del devengo, no solo
--     el de su solicitud. Ampliado en
--     supabase/migrations/20260922150000_borrar_operacion_gate_aprobada_y_disputa.sql:
--     el gate también bloquea una solicitud 'aprobada' (ya visada para pago,
--     aunque no ejecutado) y un devengo 'en_disputa' (reclamación abierta) —
--     decisión del owner tras hallazgos MEDIA de Legal/Administración. Lo que
--     SÍ se purga (comisiones_devengadas + solicitudes_pago) deja rastro en
--     `public.borrados` desde
--     supabase/migrations/20260922150500_purga_comisiones_deja_rastro_en_borrados.sql
--     (reutiliza el trigger genérico de auditoría LAW-71, ya colgado de
--     contratos/facturas — mismo patrón, dos tablas más).
--   · contratos                    → BORRADOS (el padre y sus hijos, con
--     rastro en `public.borrados` desde LAW-71). El ON DELETE SET NULL de
--     facturas_contrato_id_fkey deja huérfanas (pero con contrato_numero
--     congelado, ver trg_facturas_congela_contrato_numero) las facturas ya
--     anuladas del paso anterior — y desde
--     supabase/migrations/20260922140000_factura_anulada_permite_contrato_id_a_null.sql
--     eso ya no choca con la inmutabilidad de una factura anulada. Esa
--     excepción quedó acotada en
--     supabase/migrations/20260922151000_factura_anulada_contrato_null_solo_si_borrado.sql
--     a que el contrato realmente ya no exista — un super_admin YA NO puede
--     desvincular a mano una factura anulada de un contrato que sigue vivo
--     (hallazgo MEDIA de Seguridad: antes esa vía quedaba abierta y sin rastro).
--   · unidades                     → vuelven a `disponible` solas, por el
--     trigger `libera_unidad_sin_contrato`.
--
-- Va en una función y no en la aplicación porque son pasos que tienen que
-- pasar TODOS o NINGUNO: a mitad de camino queda una operación con las facturas
-- anuladas y los contratos todavía vivos, que es peor que no haber empezado.
--
-- Verificado en vivo end-to-end (22-sep-2026, transacciones de prueba con
-- ROLLBACK, auth.uid() real simulado): factura reciente anulada sobrevive al
-- borrado del contrato con contrato_numero intacto; comisión pendiente se
-- purga junto al contrato y deja rastro en `borrados`; comisión pagada (closer
-- o manager), en disputa, o con solicitud aprobada bloquea la operación entera
-- sin dejar nada a medias; un UPDATE manual de contrato_id=NULL sobre una
-- factura anulada con contrato vivo también queda bloqueado.
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: borrar_operacion
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731072223_borrar_operacion.sql
--   supabase/migrations/20260922134500_borrar_operacion_purga_comision_devengada.sql
--   supabase/migrations/20260922141500_borrar_operacion_gate_pagada_no_cerrada.sql
--   supabase/migrations/20260922143000_borrar_operacion_gate_pagada_cubre_closer.sql
--   supabase/migrations/20260922150000_borrar_operacion_gate_aprobada_y_disputa.sql
-- ============================================================================
