-- ============================================================================
-- Borrado con permisos + documentación por enlace + precios en el inventario
-- 31-jul-2026
-- ----------------------------------------------------------------------------
-- Hasta hoy NADIE podía borrar: `contratos` y `facturas` tenían policies de
-- SELECT/INSERT/UPDATE y ninguna de DELETE, y sin policy la RLS deniega. Lo que
-- pidió el owner:
--   · contratos  → el super admin siempre; cada operador los SUYOS si no están
--                  bloqueados (bloqueado = firmado y sellado).
--   · facturas   → solo administradores y super admin.
--   · documentos → solo super admin.
-- ============================================================================

-- ---- quién es super admin --------------------------------------------------
-- `es_admin()` ya existe y cubre admin + super_admin. Hace falta el escalón de
-- arriba porque el owner separó explícitamente los dos casos.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: borrar, documentacion, es_super_admin
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731043211_documentacion_bucket_e_indice.sql
--   supabase/migrations/20260731045054_borrado_con_permisos_y_enlaces.sql
--   supabase/migrations/20260811053843_usuarios_admin_no_toca_super_admin.sql
--   supabase/migrations/20260819044926_law71_editar_firmado_y_borrar_facturas.sql
--   supabase/migrations/20260821153053_policy_borrar_facturas_a_authenticated.sql
--   supabase/migrations/20260911033911_catalogo_por_proyecto_tambien_se_filtra.sql
--   supabase/migrations/20260911034050_documentacion_se_escribe_con_el_mismo_alcance_que_se_lee.sql
--   supabase/migrations/20260917010415_comision_admin_intranet.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
--   supabase/migrations/20260918021400_storage_deja_de_ser_una_carpeta_compartida.sql
--   supabase/migrations/20260918144841_documento_general_de_la_empresa.sql
--   supabase/migrations/20260921125405_law_facturas_enviada_no_se_borra.sql
-- ============================================================================
