-- Corrección de fondo tras `/code-review high` (17-sep-2026): doble cómputo
-- cuando UNA Carta con varias parcelas se traspasa a VARIOS Bloqueos por
-- separado (no todas a un único Bloqueo multi-parcela).
-- ════════════════════════════════════════════════════════════════════════════
-- EL FALLO ORIGINAL. `contrato_cobrado(carta_id)` devuelve el TOTAL cobrado
-- en la Carta, sin memoria de si ese dinero ya se aplicó a un Bloqueo
-- anterior. El trigger AFTER (`sincroniza_unidad_contrato`) solo fija
-- `contrato_padre_id` en la Carta la PRIMERA vez (`where c.contrato_padre_id
-- is null`), así que una Carta con 3 parcelas (p.ej. CR00025: B9/B15/B16)
-- puede traspasar cada una a un Bloqueo distinto en fechas distintas, y CADA
-- Bloqueo vería el 100% de lo cobrado en la Carta y lo descontaría entero —
-- el mismo abono aplicado dos o tres veces, en documentos firmables
-- independientes. Real en este dominio (Cartas multi-parcela existen en
-- producción, CP00002/CR00025), no cubierto por ninguna regla ya cerrada del
-- owner (que hablaban de "varias Cartas hacia UN Bloqueo", no de "una Carta
-- hacia varios Bloqueos" secuenciales).
--
-- ARREGLO (sin tabla nueva): cada Bloqueo que reclama dinero de una Carta
-- ahora escribe también `fields.carta_cobrado_detalle`, un array
-- `[{carta_id, numero, importe}]` con CUÁNTO reclamó de CADA Carta de
-- origen. El siguiente Bloqueo que mire la MISMA Carta resta lo que YA
-- reclamaron sus hermanos antes de calcular su propio descuento — el
-- "disponible" de cada Carta, no su total bruto. El sobrante NUNCA se anota
-- como reclamado.
--
-- ESTA VERSIÓN añade tres correcciones de la consulta de deploy sobre la
-- primera versión (aplicada como 20260917151710, ya en producción — esto la
-- reemplaza con CREATE OR REPLACE, no es una migración nueva desde cero):
--
-- 1) [ALTA, Legal] `carta_cobrado_numeros` citaba TODAS las Cartas que
--    ocupan la parcela por coincidencia de parcela+moneda, no solo las que
--    de verdad aportaron algo al descuento. Si la Carta A ya estaba agotada
--    por un Bloqueo anterior y solo la Carta B aportó el resto, el
--    documento firmado decía igualmente "conforme a la Carta de Reserva A,
--    B" — citando a A como origen de un abono que no puso nada en ESTE
--    reparto. Arreglo: `carta_cobrado_numeros` se construye ahora a partir
--    de las Cartas que SÍ entran en `carta_cobrado_detalle`, no de la lista
--    bruta de la consulta inicial.
--
-- 2) [ALTA, Administración + Seguridad — mismo hallazgo desde dos ángulos]
--    `carta_cobrado_detalle` solo lo escribe el trigger en el INSERT y
--    nunca se protege en el UPDATE. Dos formas de perderlo:
--      (a) Uso normal: reabrir y volver a guardar un Bloqueo ya creado
--          (`guardarContrato()` hace `.update(payload)` con el `datos`
--          ENTERO reconstruido desde `collect()`+`CAMPOS_HEREDADOS`, que
--          nunca carga `carta_cobrado_detalle` — administración, confirmado
--          por grep: cero referencias a ese campo fuera del SQL) — el
--          re-guardado lo borra sin que nadie lo pida, y el siguiente
--          Bloqueo sobre la misma Carta vuelve a ver "disponible" completo.
--      (b) Manipulación directa: un agente con permiso de UPDATE sobre su
--          propio Bloqueo (antes de firma) puede mandar un PATCH crudo a
--          Supabase —sin pasar por la UI— y borrar su propia entrada del
--          ledger, o inyectar una entrada falsa apuntando al `carta_id` de
--          una Carta ajena para poner su disponible a cero.
--    Ambos caminos reabren el doble cómputo que esta migración existe para
--    cerrar. Arreglo: nuevo trigger BEFORE UPDATE que congela los 4 campos
--    `carta_cobrado_*` a su valor de INSERT — cualquier UPDATE, venga de
--    donde venga, los repone desde `old`, ignorando lo que traiga `new`.
--    Coherente con la regla 3 del encargo original ("frozen, never
--    recalculated even across later edits"): esto es CERRAR ese mandato
--    para el camino de escritura que se quedó sin cubrir, no una regla
--    nueva.
--
-- 3) [MEDIA, Seguridad + Administración] Sin lock entre dos Bloqueos
--    insertándose a la vez sobre la MISMA Carta: ambos podrían leer
--    "disponible" completo antes de que ninguno confirme su claim.
--    Arreglo de una línea: `pg_advisory_xact_lock` por Carta, liberado solo
--    al terminar la transacción — serializa sin tocar el resto del sistema.
-- ════════════════════════════════════════════════════════════════════════════
--
-- DECISIÓN DEL OWNER, 18-sep-2026: el reparto "quien se guarda primero, se
-- lleva primero" (arriba, "disponible por Carta") se queda SIN cláusula que
-- lo explique en el documento. Legal lo había marcado como punto abierto tras
-- el 17-sep; el owner respondió que el Bloqueo YA admite varias parcelas en
-- un solo documento (chips de `parcela_codigo`, ver `parcela_inventario.js`),
-- así que el camino esperado es una Carta multi-parcela → UN Bloqueo que se
-- lleva todas de una vez — no el reparto secuencial que motivó esta migración.
-- Ese reparto sigue existiendo (CR00025 lo usa de verdad) y sigue siendo
-- financieramente seguro (el ledger de arriba impide el doble cómputo pase lo
-- que pase), pero es el caso raro, no el flujo que hay que documentar en la
-- plantilla. No añadir cláusula para esto salvo que el owner lo pida explícito.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: carta_cobrado_al_bloquear, carta_cobrado_congelado_en_update, trg_carta_cobrado_congelado_en_update
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917143835_carta_cobrado_al_bloquear.sql
--   supabase/migrations/20260917145913_carta_cobrado_al_bloquear_moneda_y_grant.sql
--   supabase/migrations/20260917151710_carta_cobrado_ledger_multibloqueo.sql
--   supabase/migrations/20260917152712_carta_cobrado_ledger_numeros_congelado_lock.sql
--   supabase/migrations/20260921142708_carta_cobrado_aplicado_tabla_lateral.sql
-- ============================================================================
