-- El Bloqueo de Parcela descuenta lo que la Carta de Reserva ya cobró —
-- 17-sep-2026, revisión previa #24 (Legal + Administración + Seguridad).
-- ════════════════════════════════════════════════════════════════════════════
-- QUÉ RESUELVE. Cuando una Carta de Reserva (cualquier variante, todas con
-- prefijo `carta_reserva_%`) transfiere de verdad su parcela a un Bloqueo
-- (`sincroniza_unidad_contrato()`, ver abajo por qué NO se toca), el cliente
-- ya pagó algo en la Carta y el Bloqueo debe reflejarlo y descontarlo — no
-- puede pedirle el 100% del suelo otra vez.
--
-- ⚠️ HALLAZGO ANTES DE ESCRIBIR ESTO (verificado, no supuesto): el plan
-- original decía "dentro (o al lado, mismo trigger BEFORE) de
-- sincroniza_unidad_contrato()", asumiendo que ese trigger ya es BEFORE.
-- Comprobado contra producción (`pg_trigger`): `trg_sincroniza_unidad` es
-- AFTER INSERT OR UPDATE. Escribir en `new.datos` dentro de un trigger AFTER
-- no tiene efecto — el executor descarta cualquier NEW devuelto por un
-- trigger AFTER, no se persiste ni lo ven los triggers AFTER siguientes.
--
-- Y NO se puede arreglar pasando `trg_sincroniza_unidad` a BEFORE: esa
-- función hace `update unidades set contrato_id = new.id` y
-- `update contratos set contrato_padre_id = new.id`, y `unidades.contrato_id`
-- tiene FK NOT DEFERRABLE contra `contratos.id` (comprobado:
-- `select condeferrable from pg_constraint where conname =
-- 'unidades_contrato_id_fkey'` → false). En BEFORE INSERT la fila de
-- `contratos` todavía no existe en el heap — ese UPDATE reventaría la FK en
-- CADA Bloqueo con parcela, no solo en los que traspasan.
--
-- SOLUCIÓN: un trigger BEFORE INSERT nuevo y aparte, que NO escribe en
-- `unidades` ni en `contratos.contrato_padre_id` (eso lo sigue haciendo
-- solo `sincroniza_unidad_contrato`, AFTER, sin tocar) — solo LEE quién
-- ocupa hoy cada parcela y, si es una Carta de Reserva, calcula y estampa el
-- descuento en `new.datos` antes de que la fila se escriba. La comprobación
-- de que el traspaso es LEGÍTIMO (mismo comprador — LAW-51) la sigue haciendo
-- en exclusiva `sincroniza_unidad_contrato()` (AFTER, misma transacción): si
-- rechaza el traspaso, revienta con su excepción de siempre y esa excepción
-- deshace el INSERT COMPLETO — incluido lo que este trigger nuevo estampó.
-- Este trigger BEFORE es deliberadamente más permisivo en su lectura (no
-- comprueba identidad del comprador) precisamente porque el AFTER es quien
-- tiene la última palabra y puede abortarlo todo.
--
-- Dos triggers BEFORE INSERT sobre la MISMA fila, cada uno con su mitad de la
-- misma pregunta, no es ideal — pero es más seguro que una tercera copia de
-- la comprobación de "mismo comprador" (ya van dos: el trigger AFTER y
-- `estadoTraspaso()` en parcela_inventario.js) o que tocar la FK.
--
-- REGLAS DEL CÁLCULO (owner, ya cerradas — ver el encargo completo):
--   1) UNA vez, solo en INSERT (columna `datos.fields`, foto fija).
--   2) El cliente NUNCA manda este número: cualquier carta_cobrado_* que
--      llegue en el INSERT se ignora y se recalcula de cero aquí. Nunca se
--      expone `contrato_cobrado()` a un RPC del navegador (sería un oráculo:
--      cualquier agente autenticado podría leer el cobrado de cualquier
--      contrato ajeno con solo pasar su uuid).
--   3) Tope: el descuento nunca supera `precio_total` del propio Bloqueo (el
--      suelo, no la villa que declaraba la Carta). El sobrante sin aplicar
--      se anota aparte, nunca desaparece en silencio.
--   4) Reparto en cascada sobre los hitos que YA traiga el INSERT, en el
--      orden en que estén — nunca un monto por debajo de 0.
--   5) Si el cobrado de todas las Cartas de origen suma 0: no se escribe
--      ninguna clave nueva y el Bloqueo se guarda exactamente como hoy.
--
-- FORMATO DEL IMPORTE: el mismo que ya usa `datos.fields.precio_total`
-- (comprobado contra filas reales — RP00164: "54.204"; el separador de
-- miles solo aparece a partir de 10.000, un numero de 4 cifras se imprime
-- sin punto: "27.102" pero también hay legado sin canonicalizar como
-- "5000"/"20000" en RP00161/RP00162, de antes de que el cálculo automático
-- existiera). Se replica `lwImporteCanonico()` (contracts/assets/dinero.js)
-- con `lw_importe_texto()` más abajo, con la MISMA tabla de casos.
--
-- ════════════════════════════════════════════════════════════════════════════

-- ── 1) ESCRIBIR un importe en el formato canónico de la suite ──────────────
-- Gemelo de `lw_importe()` (dinero_no_es_texto.sql, que LEE), y de
-- `lwImporteCanonico()` (contracts/assets/dinero.js, que hace lo mismo en el
-- navegador). Locale-independiente a propósito (no usa 'G'/'D' de to_char,
-- que dependen de lc_numeric del servidor) — se construye el agrupado a
-- mano para no heredar la configuración regional de quien ejecute esto.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: carta_cobrado_al_bloquear, lw_importe_texto, trg_carta_cobrado_al_bloquear
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917143835_carta_cobrado_al_bloquear.sql
--   supabase/migrations/20260917145913_carta_cobrado_al_bloquear_moneda_y_grant.sql
--   supabase/migrations/20260917151710_carta_cobrado_ledger_multibloqueo.sql
--   supabase/migrations/20260917152712_carta_cobrado_ledger_numeros_congelado_lock.sql
--   supabase/migrations/20260921142708_carta_cobrado_aplicado_tabla_lateral.sql
-- ============================================================================
