-- ════════════════════════════════════════════════════════════════════════════
-- CARTA DE RESERVA CONDICIONADA VÍA PT PMA — tipo propio, serie CP · 7-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Motivo: el comprador de Mejan B2/B3/B4/B6/B7 (una S.L. española) condiciona la
-- transferencia de la Cuota de Reserva a que (a) la reserva quede sujeta a una due
-- diligence con devolución si falla, (b) desaparezca la referencia a Hak Sewa
-- porque la estructura de compra va a ser una PT PMA, y (c) pueda designar a esa
-- PT PMA como adquirente definitivo y transmitir después cada parcela por separado.
--
-- Ninguna de las tres cartas que ya existen sirve tal cual:
--   · CR (carta_reserva)              — 52 emitidas, sin condiciones ni devolución.
--   · CA (carta_reserva_ampliada)     — arrendamiento con obra: plazo de Hak Sewa,
--                                       escrow, garantías de construcción.
--   · CH (carta_reserva_hak_sewa)     — tiene las condiciones y la devolución, pero
--                                       su eje es Hak Sewa y su comprador es persona
--                                       física con pasaporte.
-- Se añade una CUARTA, ensamblada de las piezas ya validadas de las anteriores.
--
-- TIPO PROPIO, no compartido: TIPO_SLUG (app.html) mapea tipo→plantilla 1:1, así que
-- compartir tipo con cualquiera de las otras haría que reabrir un contrato guardado
-- cargase la plantilla equivocada. Mismo motivo por el que nacieron CA, CH y C2.
-- SERIE PROPIA (CP, no CR): por el número tiene que saberse con qué texto se firmó
-- una operación. CP se elige por simetría con CH — la carta "de Hak Sewa" y la carta
-- "de PMA" son las dos condicionadas y se distinguen por su vía de tenencia.
--
-- ⚠️ LA FUNCIÓN SE REESCRIBE DESDE SU DEFINICIÓN VIVA, NO DESDE ESTE DIRECTORIO.
-- `sql/carta_reserva_ampliada.sql` (31-jul) trae la versión de 8 ramas; la que corre
-- hoy en producción tiene 14 (se le añadieron PB, C2, HS, CH, PA y cc00014_timon).
-- Aplicar aquel fichero habría borrado seis series sin decir nada y el siguiente
-- contrato de esos tipos habría reventado con «Tipo de contrato sin numeracion
-- definida». Antes de tocar esta función: `pg_get_functiondef` y añadir la rama.
-- ════════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: set_contrato_numero
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260717073753_create_contratos_table.sql
--   supabase/migrations/20260717082752_contratos_add_remaining_types.sql
--   supabase/migrations/20260731075330_carta_reserva_ampliada.sql
--   supabase/migrations/20260804065545_numeracion_ppjb_bonian.sql
--   supabase/migrations/20260805023643_numeracion_hak_sewa.sql
--   supabase/migrations/20260806060951_numeracion_ppjb_bonian_c2.sql
--   supabase/migrations/20260806093122_numeracion_carta_reserva_hak_sewa.sql
--   supabase/migrations/20260810094256_contrato_numero_serie_poa.sql
--   supabase/migrations/20260831021755_cc00014_timon_numeracion_defensiva.sql
--   supabase/migrations/20260907083636_carta_reserva_pma.sql
--   supabase/migrations/20260908083655_adenda_tipo_y_serie_ad.sql
--   supabase/migrations/20260910025145_investor_deck_palmfield.sql
--   supabase/migrations/20260910025534_tipos_de_contrato_regenera_investor_deck.sql
-- ============================================================================
