-- Dos correcciones de la consulta de deploy (17-sep-2026, capa 1) sobre
-- carta_cobrado_al_bloquear.sql — ambas ALTA, las dos verificadas antes de
-- escribir esto, ninguna es una opinión.
-- ════════════════════════════════════════════════════════════════════════════

-- ── 1) Administración: el descuento comparaba importes sin comprobar moneda ──
-- `v_cobrado` sale de `contrato_cobrado()` — la suma de lo cobrado en la(s)
-- Carta(s) de origen, en SU moneda — y se comparaba/restaba directamente
-- contra `precio_total` del propio Bloqueo sin mirar si son la misma moneda.
-- La suite ya admite varias (EUR/USD/AUD/IDR, `lwSumaPorMoneda` en dinero.js,
-- "no hay tipo de cambio en el sistema y meter uno inventado sería peor").
-- Si la Carta y el Bloqueo declaran monedas distintas, el descuento y su
-- reparto en cascada sobre los hitos serían una cifra sin sentido, impresa
-- firmable en el documento. Arreglo: una Carta con moneda distinta a la del
-- Bloqueo se EXCLUYE del cálculo automático (no se adivina un cambio) — igual
-- que ya hace el resto del estudio ante monedas mezcladas.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: carta_cobrado_al_bloquear
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917143835_carta_cobrado_al_bloquear.sql
--   supabase/migrations/20260917145913_carta_cobrado_al_bloquear_moneda_y_grant.sql
--   supabase/migrations/20260917151710_carta_cobrado_ledger_multibloqueo.sql
--   supabase/migrations/20260917152712_carta_cobrado_ledger_numeros_congelado_lock.sql
--   supabase/migrations/20260921142708_carta_cobrado_aplicado_tabla_lateral.sql
-- ============================================================================
