-- Estado PREVIO a `carta_reserva_pma.sql` (7-sep-2026), capturado de la base viva
-- con `pg_get_constraintdef` y `pg_get_functiondef` justo antes de aplicar.
-- Es el "backup" que pide CLAUDE.md para este cambio: aquí no se toca ni una fila,
-- solo el esquema, y la política del estudio es que el esquema se respalda
-- versionándolo (`tools/respaldo_supabase.py` copia DATOS, no esquema, y lo dice).
-- Para revertir: ejecutar este fichero entero. La secuencia `contratos_cp_seq` se
-- queda creada y vacía a propósito — borrarla no aporta nada y sí puede pisar a
-- otra sesión.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: set_contrato_numero
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260717073753_create_contratos_table.sql
--   supabase/migrations/20260717082752_contratos_add_remaining_types.sql
--   supabase/migrations/20260731075330_carta_reserva_ampliada.sql
--   supabase/migrations/20260804065545_numeracion_ppjb_bonian.sql
--   supabase/migrations/20260805023643_numeracion_hak_sewa.sql
--   supabase/migrations/20260806060951_numeracion_ppjb_bonian_c2.sql
--   supabase/migrations/20260806093122_numeracion_carta_reserva_hak_sewa.sql
--   supabase/migrations/20260810094256_contrato_numero_serie_poa.sql
--   supabase/migrations/20260831021755_cc00014_timon_numeracion_defensiva.sql
--   supabase/migrations/20260907083636_carta_reserva_pma.sql
--   supabase/migrations/20260908083655_adenda_tipo_y_serie_ad.sql
--   supabase/migrations/20260910025145_investor_deck_palmfield.sql
--   supabase/migrations/20260910025534_tipos_de_contrato_regenera_investor_deck.sql
-- ============================================================================
