-- Carta de Reserva ampliada — nuevo tipo de contrato con serie propia (CA).
-- 31-jul-2026. Motivo: el memorándum legal 002/LPH-LM/AGP/VII/2026 (despacho del
-- comprador) pedía en la Carta de Reserva quince cosas que no estaban. En vez de
-- reescribir la Carta corta —que tiene contratos ya emitidos— se añade una plantilla
-- APARTE. Necesita tipo propio porque TIPO_SLUG (app.html) mapea tipo→plantilla 1:1:
-- si las dos compartieran tipo, al reabrir un contrato guardado saldría la plantilla
-- equivocada.
--
-- Serie propia CA (no CR) para que las dos cartas no compartan numeración: mezclarlas
-- haría imposible saber, por el número, con qué texto se firmó una operación.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: set_contrato_numero
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260717073753_create_contratos_table.sql
--   supabase/migrations/20260717082752_contratos_add_remaining_types.sql
--   supabase/migrations/20260731075330_carta_reserva_ampliada.sql
--   supabase/migrations/20260804065545_numeracion_ppjb_bonian.sql
--   supabase/migrations/20260805023643_numeracion_hak_sewa.sql
--   supabase/migrations/20260806060951_numeracion_ppjb_bonian_c2.sql
--   supabase/migrations/20260806093122_numeracion_carta_reserva_hak_sewa.sql
--   supabase/migrations/20260810094256_contrato_numero_serie_poa.sql
--   supabase/migrations/20260831021755_cc00014_timon_numeracion_defensiva.sql
--   supabase/migrations/20260907083636_carta_reserva_pma.sql
--   supabase/migrations/20260908083655_adenda_tipo_y_serie_ad.sql
--   supabase/migrations/20260910025145_investor_deck_palmfield.sql
--   supabase/migrations/20260910025534_tipos_de_contrato_regenera_investor_deck.sql
-- ============================================================================
