-- La familia de Cartas de Reserva se queda FUERA de una lista a mano — 10-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- SÍNTOMA (caso real, HOLMACA 1970 S.L., Mejan Village S7, CP00002): reservada
-- una parcela con la Carta de Reserva Condicionada (serie CP, tipo
-- `carta_reserva_pma`, alta 7-sep), el Bloqueo de Parcela (`reserva_parcela`)
-- que debería sucederla muere con
--   La parcela B2 de Mejan Village S7 ya esta asignada al contrato CP00002
-- exactamente el mismo síntoma que `parcela_traspaso_carta_a_bloqueo.sql`
-- (14-ago) vino a arreglar — pero para un tipo de Carta que no existía ese día.
--
-- CAUSA: `traspaso_ok` (y su gemelo, la Carta que sigue editable tras perder su
-- parcela) miran `ocupada_tipo in ('carta_reserva', 'carta_reserva_ampliada',
-- 'carta_reserva_hak_sewa')` — una lista escrita a mano el 14-ago con las TRES
-- Cartas que existían entonces. Desde entonces se dieron de alta DOS más
-- (`carta_reserva_pma` 7-sep, `carta_reserva_investor_deck` 10-sep) y ninguna
-- entró en esta lista: es el patrón LAW-48 ("al alta de un tipo le faltan
-- sitios"), y esta lista concreta ya lleva DOS altas seguidas sin acordarse de
-- ella — la 2ª reincidencia que la escalera de aprendizaje manda promocionar
-- (`tools/aprendizaje.py log`), no volver a parchear con dos strings más.
--
-- ARREGLO — se generaliza al criterio que ya existe, en vez de ampliar la
-- lista una tercera vez: TODOS los tipos de Carta de Reserva llevan el prefijo
-- `carta_reserva_` por diseño deliberado (ver el comentario de cada alta en
-- `contracts/app.html` — "tipo PROPIO... mismo motivo que las otras Cartas"),
-- así que `like 'carta_reserva%'` cubre las cinco de hoy y cualquiera que se
-- dé de alta mañana sin tocar este trigger otra vez. Nada más cambia: mismo
-- guardarrail de mismo-comprador (LAW-51), mismo enlace Carta->Bloqueo
-- (LAW-50), misma escalera de estados, mismo bucle multi-parcela
-- (`parcelas_multiples.sql`, 18-ago — este fichero es su continuación, no un
-- reemplazo del resto de reglas que trae).
--
-- ✅ Comprobado antes de escribir: `prosrc` de producción == la última versión
-- del repo (`parcelas_multiples.sql`), sin deriva. Caso real que lo prueba:
-- CP00002/HOLMACA reserva B2,B3,B4,B6,B7 de Mejan Village S7, las 5 en
-- `reservada` — el Bloqueo de cualquiera de ellas es justo el caso que hoy
-- revienta y que este cambio deja pasar.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: sincroniza_unidad_contrato
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
