-- Ya aplicado en producción (28-ago-2026, petición del owner: "Necesito ese
-- contrato configurarlo como una nueva plantilla, sin inyectar datos, debe
-- ir así"). Copia de repo-de-registro, no se vuelve a ejecutar.
--
-- CC00014 (construcción, Timon Taeke van den Bosch, Tamarind Rise · modelo
-- Dali) llegó con un .docx ya negociado a mano: 78 tramos de texto resaltados
-- en amarillo frente a la plantilla genérica de Construcción, cláusulas
-- propias (fase de construcción ya iniciada en marzo 2026 antes de firmar,
-- vínculo con un Land Lease Agreement notarial propio, arbitraje SIAC en vez
-- de BANI, calendario de pagos propio...). Igual que ppjb_bonian_c2 (serie
-- C2, "un solo ejemplar, texto fijo"), se convierte en su propia plantilla
-- estática (contracts/templates/cc00014_timon.html) en vez de forzarlo por
-- el sistema genérico de campos, que perdería exactamente las cláusulas que
-- lo hacen distinto.
--
-- Primero se amplía el CHECK de contratos.tipo para admitir el tipo propio
-- (mismo patrón que al dar de alta ppjb_bonian_c2/hak_sewa_notario en su
-- momento), y luego se pasa CC00014 de 'construccion' a 'cc00014_timon' —
-- necesario porque TIPO_SLUG (contracts/app.html) es un mapa inverso
-- tipo→plantilla: compartir tipo con la genérica pisaría la entrada y
-- reabrir este contrato cargaría la plantilla equivocada. No afecta a la
-- facturación: unidad_parte_cobrada y avanza_unidad_por_cobro trabajan por
-- contrato_padre_id/unidad_id, nunca filtran por tipo.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: (fichero de ALTER/INSERT, sin CREATE)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260828060000_cc00014_timon_tipo_propio.sql
-- ============================================================================
