-- ════════════════════════════════════════════════════════════════════════════
-- CADA UNIDAD ENSEÑA SU PARTE DE LO COBRADO — 19-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- EL CASO (owner): RP00055 lleva DOS parcelas, C2 y D3 de Soka Village W2, a
-- 20.000 EUR cada una — 40.000 en total. Se cobran 10.000 de reserva (5.000 por
-- parcela) y la ficha de CADA parcela dice **50% pagado**. Lo pagado es el 25%.
--
-- LA CAUSA: `unidades_estado` compara TODO lo cobrado del contrato contra el
-- precio de UNA unidad — `contrato_cobrado(u.contrato_id) / u.precio`. Con una
-- parcela por contrato salía bien; multi-parcela (18-ago) lo rompió, y el
-- número aparece dos veces (10.000 contra 20.000, y otra vez 10.000 contra
-- 20.000) en vez de repartirse.
--
-- ⚠️ LO QUE **NO** HAY QUE TOCAR, y casi se toca: `avanza_unidad_por_cobro`,
-- que es quien decide cuándo una parcela pasa a `cobrada`, YA está bien desde
-- `parcelas_multiples.sql` (18-ago): compara `v_cobrado >= v_precio_unidades`,
-- o sea contra la SUMA de las unidades del contrato, no contra una. Se sacó su
-- `prosrc` de producción antes de escribir esto y coincide con el repo. Quien
-- lo "arregle" copiando la versión de `estado_unidad_por_tipo_y_cobro.sql` (la
-- de 11-ago, que sigue en el repo) le quitará de paso el control de moneda
-- mezclada (`v_mon`/`v_nmon`) que aquella no tenía. No es el fichero vivo.
--
-- EL REPARTO: proporcional al precio de cada unidad y, si los precios no están
-- puestos (CR00025 tiene tres unidades y `sum(precio)` sale null), a partes
-- iguales. Nunca se inventa un precio: sin precios, tres unidades es un tercio
-- cada una, que es lo único defendible.
--
-- Así el porcentaje de la vista y el salto a `cobrada` dicen lo mismo: la
-- unidad llega al 100% exactamente cuando el contrato cubre la suma de sus
-- unidades, que es cuando la función las marca cobradas.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: unidad_parte_cobrada, unidades_estado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260805024801_unidades_estado_con_obra.sql
--   supabase/migrations/20260810100129_unidades_estado_vista_fase_zona.sql
--   supabase/migrations/20260810101230_unidades_estado_restaura_security_invoker.sql
--   supabase/migrations/20260811035145_unidades_estado_solo_recibi.sql
--   supabase/migrations/20260812042114_estado_unidad_por_tipo_y_cobro_fix_view.sql
--   supabase/migrations/20260819044137_cobro_repartido_entre_unidades.sql
--   supabase/migrations/20260824035201_construccion_por_parcela.sql
--   supabase/migrations/20260826112241_unidades_estado_precio_efectivo.sql
--   supabase/migrations/20260902022413_unidades_estado_restaura_security_invoker_2.sql
--   supabase/migrations/20260911005624_unidades_estado_agente_creador.sql
--   supabase/migrations/20260911085533_unidad_parte_cobrada_split_suelo_obra.sql
--   supabase/migrations/20260911085553_unidades_estado_cobrado_suelo_obra.sql
--   supabase/migrations/20260911085617_unidades_estado_restaura_security_invoker_3.sql
--   supabase/migrations/20260915004928_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915005452_unidad_parte_cobrada_split_gate_de_permiso.sql
--   supabase/migrations/20260915005638_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260915100000_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915103000_unidad_parte_cobrada_split_gate_de_permiso.sql
--   supabase/migrations/20260915104500_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260916093309_unidades_codigo_orden_natural.sql
-- ============================================================================
