-- ════════════════════════════════════════════════════════════════════════════
-- UN COMPRADOR PUEDE SER UNA EMPRESA — 19-ago-2026, encargo del owner
-- ════════════════════════════════════════════════════════════════════════════
-- EL FALLO QUE LO DESTAPA. Dar de alta la sociedad de un cliente que ya está
-- fichado como persona reventaba con «ese correo ya se ha usado»: `clients`
-- tenía UNIQUE(email), y una persona y su sociedad comparten correo casi
-- siempre. Con lo cual la sociedad no podía existir como ficha, y su único
-- hueco era la sección «El adquiriente firma como sociedad (PT PMA)» del
-- contrato: cuatro campos tecleados a mano, clavados a Indonesia (NIB, NPWP)
-- cuando el comprador puede ser una S.L. española o una LLC americana.
--
-- CÓMO QUEDA. `clients` distingue PERSONA de EMPRESA, y la empresa es un
-- comprador de pleno derecho: se ficha, se enlaza al contrato y el documento
-- imprime sus datos. El párrafo de «Segunda Parte» tiene ahora dos redacciones
-- —persona y sociedad— y la plantilla elige por `adq1_tipo`.
--
-- POR QUÉ NO HAY COLUMNAS NUEVAS PARA EL NIF NI PARA EL PAÍS. Una empresa
-- guarda su identificación fiscal en `passport_number` y su país de
-- constitución en `nationality`, las mismas columnas que la persona. No es
-- pereza: `contrato_identificadores` (LAW-51, y el guardarraíl de recibís del
-- 19-ago) compara identidad con pasaporte + email, y meter el NIF en una
-- columna aparte lo dejaría fuera de esa comparación — dos sociedades
-- distintas con el mismo correo pasarían por la misma. El campo del contrato
-- ya se llama «Nº pasaporte / identificación fiscal» desde el primer día.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: (fichero de ALTER/INSERT, sin CREATE)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260819022524_compradores_empresa.sql
-- ============================================================================
