-- ============================================================================
-- La ficha del comprador la crea la BASE, no la aplicación — 4-ago-2026
-- ----------------------------------------------------------------------------
-- PREGUNTA DEL OWNER: «¿todos los contratos crean usuarios en compradores?».
-- Medido sobre los 32 contratos de producción: NO. Faltaban 5 enlaces en 5
-- contratos (RP00012 ×2, CC00007, RP00016, CC00008), y de los 5, tres personas
-- no tenían ni ficha.
--
-- Es la SEGUNDA vez que se mide lo mismo (31-jul y 4-ago), así que la regla
-- sube un peldaño de la escalera: deja de vivir en el JavaScript de una
-- pantalla y pasa a ser un disparador de la base. El motivo es el mismo que ya
-- se escribió para `vinculo_contrato_unidad.sql` el 31-jul: a `contratos` le
-- escriben tres sitios distintos —la app, la función de firma y cualquier
-- corrección por SQL— y una regla que vive en uno de los tres no se cumple
-- desde los otros dos.
--
-- POR QUÉ FALLABA. Tres causas distintas, y solo una era la que estaba escrita:
--   1. `clients.email` es UNIQUE y una familia comparte correo. Mª Amparo
--      (CC00007 y RP00016) da el mismo email que su marido Juan Ramón, que ya
--      tenía ficha: el insert moría con violación de clave única y el aviso se
--      iba con el toast. NO era «se guardó antes de que existiera el alta».
--      → Ahora, si el correo ya es de otra persona, la ficha se crea SIN correo:
--        a quien trae pasaporte lo identifica el pasaporte, y perder el correo
--        de la ficha es infinitamente menos grave que no tener ficha.
--   2. Contratos guardados antes del 28-jul (RP00012) nunca pasaron por el alta,
--      y nadie reabre un contrato viejo para reguardarlo.
--      → Ahora hay una función que se puede pasar sobre lo ya guardado.
--   3. CC00008 tenía un cuarto adquiriente que el bug de roles ≤3 se comió, y el
--      contrato está BLOQUEADO: reguardarlo no es una opción.
--      → La función se llama por id, sin tocar el contrato. Un documento firmado
--        no se altera para arreglar su índice de personas.
--
-- QUÉ NO HACE, A PROPÓSITO:
--   · Sin pasaporte NI email no crea ficha. Un "cliente" sin identificador se
--     duplica en cuanto alguien teclee el nombre distinto, y limpiar eso después
--     cuesta más que no crearlo. Hoy son 3: CC00004, CR00006 y RP00022.
--   · No enriquece fichas existentes. Si la persona ya está, se enlaza y punto:
--     pisar un dato que alguien corrigió a mano desde Compradores con el que
--     lleva el contrato viejo es perder trabajo, no ganarlo.
--   · No aborta el guardado si algo va mal (ver el disparador, abajo).
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: sincronizar_compradores, trg_compradores_desde_datos, trg_sincronizar_compradores
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260804041013_compradores_desde_contrato.sql
--   supabase/migrations/20260819022615_sincronizar_compradores_desempate_por_tipo.sql
--   supabase/migrations/20260819101011_trigger_compradores_definer_y_ruidoso.sql
--   supabase/migrations/20260824111810_compradores_sin_fantasmas.sql
-- ============================================================================
