-- ════════════════════════════════════════════════════════════════════════════
-- EL COMPRADOR SALE DE SU FICHA, NO DEL TEXTO — 18-ago-2026, encargo del owner
-- ════════════════════════════════════════════════════════════════════════════
-- CÓMO ERA. `sincronizar_compradores` cogía el pasaporte y el email escritos en
-- el contrato, buscaba una ficha que coincidiera y, si no la encontraba, CREABA
-- UNA PERSONA NUEVA. La identidad de un cliente la decidía lo que alguien
-- tecleaba, y de ahí salieron las dos cosas que ya costaron dinero y tiempo:
--   · los compradores DUPLICADOS (el owner pidió el 18-ago poder borrarlos);
--   · CR00025, con un email en el contrato distinto del de la ficha — el
--     contrato «se envió» a un dominio que no existe;
--   · y RP00043, 165.800 €, con un email metido en el campo del NOMBRE: por eso
--     nunca tuvo ficha.
--
-- CÓMO ES AHORA, y el orden importa:
--   1. Si el contrato trae el ENLACE explícito (`datos.adq1_client_id` para el
--      adquiriente I, `client_id` en cada fila de `datos.compradores`), se usa
--      ese y no se adivina nada. Es lo que manda la app desde hoy.
--   2. Si no lo trae (contrato viejo, o guardado desde una pestaña sin
--      recargar), se sigue buscando por pasaporte o email como siempre — eso no
--      inventa a nadie, solo reconoce.
--   3. Y si no aparece: NO SE CREA. Se devuelve en `sin_ficha` y ahí se queda.
--      La app ya no deja guardar un comprador sin ficha, así que este caso solo
--      lo alcanzan las pestañas viejas y las escrituras a mano por SQL.
--
-- ⚠️ LA OTRA MITAD DE LA REGLA vive en `contracts/app.html` (buscar / «Crear
-- ficha de cliente nuevo» / «Corregir ficha», y el freno al guardar). Si cambia
-- una, cambia la otra: sin la app, esto deja contratos sin comprador enlazado;
-- sin esto, la base volvería a inventar personas a partir de una errata.
-- LAW-51: al tocar esta función se relee TODO consumidor — hoy el trigger
-- `trg_compradores_desde_datos` y la llamada suelta desde /intranet/compradores/.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: sincronizar_compradores
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260804041013_compradores_desde_contrato.sql
--   supabase/migrations/20260819022615_sincronizar_compradores_desempate_por_tipo.sql
--   supabase/migrations/20260824111810_compradores_sin_fantasmas.sql
-- ============================================================================
