-- ════════════════════════════════════════════════════════════════════════════
-- PASO 2 · EL COMPRADOR SE LEE DE SU FICHA, AL MOMENTO — 19-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Decisión del owner: «Compradores manda; si corrijo un cliente, toda la suite
-- se actualiza al momento, ni siquiera preguntar». Mismo patrón que el paso 1
-- con los proyectos (ENLACE + ESPEJO), aplicado a la identidad del comprador.
--
-- CÓMO ESTABA. El contrato guardaba una COPIA de los datos del cliente en
-- `datos.fields.adq1_*`. Corregir la ficha no llegaba a ningún sitio: había que
-- abrir el documento y aceptar un aviso. De ahí el caso que lo destapó —CSP
-- CONCEPTS con el NIF corregido y la factura INV00037 diciendo lo de antes—.
--
-- CÓMO QUEDA. Dos espejos encadenados, cada uno de un salto:
--     ficha  →  contrato VIVO  →  factura VIVA
-- Cada guardado reescribe la copia desde su fuente, y corregir la ficha empuja
-- el cambio a todos los documentos vivos que cuelgan de ella.
--
-- ⚠️ VIVO Y SOLO VIVO. Un contrato `bloqueado` o con firmas en curso, y una
-- factura `enviada` o `anulada`, NO se tocan jamás: ese papel ya está en manos
-- de alguien. Para esos sigue el aviso «Ficha ≠», que es su sitio.
--
-- ⚠️ LÍMITE CONOCIDO Y DELIBERADO: la factura solo se refleja cuando su
-- contrato tiene UN comprador con ficha. Con varios, su etiqueta es compuesta
-- («A · B», y «A: P1 · B: P2» en los documentos) y esa composición la define
-- `contracts/assets/compradores.js`. Rehacerla aquí en SQL sería una SEGUNDA
-- definición de «quién compra», que es justo el fallo que este trabajo persigue.
-- Esas facturas se quedan con el aviso «Ficha ≠» hasta que la composición suba
-- a la base o baje una función común.

-- ── de la ficha al contrato ────────────────────────────────────────────────

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: espeja_comprador, trg_cliente_actualizado, trg_espejo_comprador
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260819150732_comprador_en_vivo.sql
-- ============================================================================
