-- ============================================================================
-- Un comprador que sale del contrato tiene que salir de la tabla — 24-ago-2026
--
-- SÍNTOMA (owner): en Operaciones, C200003 mostraba como compradores a «Aranzazu
-- Bahon Bueno y Carlos Fragua Martinez», que no tienen nada que ver con ese
-- contrato. Sus compradores reales son Xavier Roman y Andrea Köver, y así lo
-- decía `contratos.comprador_nombre`. Los que sobraban vivían en
-- `contrato_compradores`, que es de donde Operaciones pinta esa columna.
--
-- CAUSA: `sincronizar_compradores` solo sabía sumar. Su bucle hace
--   insert ... on conflict (contrato_id, rol) do update
-- y nada más: si el contrato tuvo cuatro adquirientes y se editó dejando dos,
-- los roles `adquiriente_3` y `adquiriente_4` se quedan enlazados para siempre,
-- apuntando a las personas de la versión anterior. No hay error, no hay aviso, y
-- el documento impreso —que sale de `datos`— sigue correcto: la contradicción
-- solo se ve en las pantallas que leen la tabla.
--
-- Medido antes de tocar: de 112 contratos, 3 no cuadran. C200003 (2 en el
-- documento, 4 en la tabla) es el caso del owner. CR00013 tiene el problema
-- INVERSO —2 en el documento, 1 en la tabla— y esa es otra causa distinta (un
-- comprador sin ficha que el bucle salta a propósito, `v_sin_ficha`), así que
-- este arreglo no lo toca ni debe. CO00004 es una Oferta Comercial, que por
-- diseño no exige ficha.
--
-- EL ARREGLO, y por qué así: se borran los roles que YA NO EXISTEN EN EL
-- DOCUMENTO, no «los que no he podido enlazar en esta pasada». La diferencia
-- importa: un comprador que sigue nombrado en el contrato pero cuya ficha no se
-- puede resolver hoy (sin pasaporte ni email todavía) conserva su enlace, que es
-- lo correcto. Solo desaparecen los roles fantasma — los que el documento ya no
-- menciona. Con el criterio fácil («borra lo que no he enlazado») una ficha
-- borrada o un email corregido habrían desenlazado a un comprador de verdad.
-- ============================================================================

-- destructivo-ok: el DELETE es el arreglo, y esta acotado a los roles que el
-- propio documento ya no menciona, dentro de UN contrato. Sin el, la tabla no
-- puede volver a cuadrar con el contrato. Verificado antes de aplicarlo: nada
-- referencia `contrato_compradores` por clave ajena, asi que no arrastra nada.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: sincronizar_compradores
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260804041013_compradores_desde_contrato.sql
--   supabase/migrations/20260819022615_sincronizar_compradores_desempate_por_tipo.sql
--   supabase/migrations/20260824111810_compradores_sin_fantasmas.sql
-- ============================================================================
