-- Corregir la sociedad de un BORRADOR tiene que recalcular su emisor congelado.
--
-- Hallazgo ALTA de otra sesion en la consulta de deploy del 17-sep-2026, sobre
-- la migracion de hace un rato. La rama de UPDATE restauraba
-- `old.datos->'emisor'` SIEMPRE que existiera, sin mirar si la sociedad habia
-- cambiado. Pero `factura_enviada_no_cambia_emisor` permite a proposito cambiar
-- `sociedad` mientras la factura NO esta enviada.
--
-- Resultado: un agente corregia la sociedad de un borrador, la columna y el
-- desplegable pasaban a San Dal Woods, y `datos.emisor` seguia diciendo Tepi Sun
-- Gai. Como el PDF que se manda por correo imprime el congelado
-- (`paginaParaEmail` usa `SAVED.emisor`), el comprador habria recibido un
-- documento de la empresa vieja mientras la pantalla ensenaba la corregida. Es
-- exactamente la familia de fallo que todo este trabajo viene a cerrar, metida
-- por la puerta de atras.
--
-- Ahora: sociedad igual -> se preserva; sociedad distinta (o INSERT) -> se
-- (re)congela desde la tabla. Verificado con bloque de rollback en los dos casos.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: congela_emisor_factura
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917082716_facturas_emisor_congelado_y_permisos.sql
--   supabase/migrations/20260917092917_congela_emisor_tambien_en_update.sql
--   supabase/migrations/20260917093621_congela_emisor_recalcula_si_cambia_sociedad.sql
--   supabase/migrations/20260917161500_facturas_emisor_congelado_y_permisos.sql
--   supabase/migrations/20260917174500_congela_emisor_tambien_en_update.sql
--   supabase/migrations/20260917182000_congela_emisor_recalcula_si_cambia_sociedad.sql
-- ============================================================================
