-- destructivo-ok: los `drop trigger/policy if exists` son idempotencia estándar
-- sobre objetos que este mismo fichero recrea a continuación (mismo patrón que
-- el resto del repo, ver law71_editar_firmado_y_borrar_facturas.sql); no borra
-- datos ni ningún objeto ajeno. Las dos funciones se `create or replace`, no se
-- borran filas de ninguna tabla.
-- ════════════════════════════════════════════════════════════════════════════
-- CADA CONSTRUCCIÓN SABE DE QUÉ PARCELA ES — 24-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- EL CASO (owner): RP00069 tiene dos parcelas, C1 (131.750€) y C2 (128.250€),
-- cada una con su propio contrato de Construcción — CC00030 (89.000€) y
-- CC00031 (95.000€). El contrato de Construcción nunca ha guardado a qué
-- parcela pertenece (`parcela_codigo` queda vacío ahí — gap ya visto el
-- 12-ago, dejado pendiente a propósito: "LAW-42, dejarlas por ahora"). Sin ese
-- dato, `unidad_parte_cobrada` no puede saber que el pago de CC00030 es de C1 y
-- el de CC00031 es de C2: agrupaba TODO el cobrado de la reserva + sus hijos y
-- lo repartía proporcional al precio entre las dos parcelas — el pago de la
-- construcción de una se mezclaba con el de la otra, y las dos salían con el
-- MISMO % cobrado (46,3%) pese a tener cada una su propio avance real.
--
-- REVISIÓN PREVIA (24-ago-2026, Desarrollo+Datos+Seguridad) antes de este
-- fichero — lo que cambió respecto al plan original por sus hallazgos:
--   · Datos: el dinero cobrado en la RAÍZ (depósito de reserva) es de TODA la
--     reserva y se sigue prorrateando entre TODAS las hermanas, tengan o no ya
--     su Construcción asignada. Solo el dinero de los HIJOS sin `unidad_id` se
--     prorratea entre las hermanas que TODAVÍA no tienen ninguna Construcción
--     asignada — no es un único reparto "sin asignar" como decía el plan.
--   · Desarrollo: `avanza_unidad_por_cobro` (decide el estado) tenía su propio
--     cálculo aparte de `unidad_parte_cobrada` (decide el %); si solo se
--     arregla uno de los dos, vuelve la contradicción "ficha dice 100%, estado
--     no se ha movido" que el fix del 19-ago ya cerró una vez. Se reescriben
--     los dos, y `avanza_unidad_por_cobro` pasa a llamar a
--     `unidad_parte_cobrada` fila a fila en vez de reimplementar el cálculo —
--     una sola fuente de verdad para las dos.
--   · Seguridad: sin guardarraíl de base, un `unidad_id` mal puesto (a mano,
--     por la API, o por un bug de UI) atribuiría dinero a la parcela de OTRO
--     comprador. Trigger que exige que `unidad_id` pertenezca a la MISMA
--     reserva raíz del contrato, y que solo un admin pueda CAMBIARLO una vez
--     puesto (darlo de alta al crear el contrato sigue abierto a cualquier
--     agente — mismo patrón que `clients_solo_admin_edita.sql`: cualquiera da
--     de alta, solo admin corrige después). El rastro de auditoría en un
--     contrato ya bloqueado no hace falta añadirlo aparte:
--     `trg_registra_edicion_privilegiada` (LAW-71) ya registra CUALQUIER
--     UPDATE sobre un contrato que ya estaba bloqueado, genérico.
--
-- SIN BACKFILL (confirmado por Datos): CC00030/CC00031 no tienen forma fiable
-- de deducirse por importe — 89.000 y 95.000 no casan con ninguna proporción
-- limpia de 131.750/128.250. Se quedan sin `unidad_id`, con el reparto
-- proporcional de siempre entre las hermanas sin asignar (que hoy son las dos,
-- así que su comportamiento no cambia). El fix aplica desde la próxima
-- Construcción que se derive.

-- 1) la columna, con índice (Datos: el lado que referencia una FK no se indexa solo)

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: avanza_unidad_por_cobro, contratos_unidad_id_idx, trg_valida_unidad_id_contrato, unidad_parte_cobrada, unidades_estado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260805024801_unidades_estado_con_obra.sql
--   supabase/migrations/20260810100129_unidades_estado_vista_fase_zona.sql
--   supabase/migrations/20260810101230_unidades_estado_restaura_security_invoker.sql
--   supabase/migrations/20260811035145_unidades_estado_solo_recibi.sql
--   supabase/migrations/20260812042114_estado_unidad_por_tipo_y_cobro_fix_view.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260812043919_avanza_unidad_por_cobro_fix_forward.sql
--   supabase/migrations/20260819044137_cobro_repartido_entre_unidades.sql
--   supabase/migrations/20260824035201_construccion_por_parcela.sql
--   supabase/migrations/20260824043534_unidad_id_null_saltaba_guardarrail.sql
--   supabase/migrations/20260826112241_unidades_estado_precio_efectivo.sql
--   supabase/migrations/20260902022413_unidades_estado_restaura_security_invoker_2.sql
--   supabase/migrations/20260911005624_unidades_estado_agente_creador.sql
--   supabase/migrations/20260911085533_unidad_parte_cobrada_split_suelo_obra.sql
--   supabase/migrations/20260911085553_unidades_estado_cobrado_suelo_obra.sql
--   supabase/migrations/20260911085617_unidades_estado_restaura_security_invoker_3.sql
--   supabase/migrations/20260915004928_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915005452_unidad_parte_cobrada_split_gate_de_permiso.sql
--   supabase/migrations/20260915005638_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260915100000_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915103000_unidad_parte_cobrada_split_gate_de_permiso.sql
--   supabase/migrations/20260915104500_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260916040622_avanza_unidad_por_cobro_exige_suelo_100.sql
--   supabase/migrations/20260916093309_unidades_codigo_orden_natural.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
-- ============================================================================
