-- `contrato_cobrado` perdia dinero realmente cobrado -- 14-ago-2026.
--
-- SINTOMA (lo trajo el owner): CR00020, Jorge Miguel Domingo Berenguer / Mayka
-- Nunez Saez, parcela C5 de Bonian Village. El cliente paga la reserva, se le
-- emite factura y recibi (REC00019, 1.000 EUR, con justificante) y el contrato
-- sigue diciendo 0 cobrado.
--
-- CAUSA. La funcion sumaba por dos ramas que no cubren todos los casos:
--   (A) importes aplicados cuya FACTURA es de este contrato, y
--   (B) el total de los recibis de este contrato que NO tienen ninguna aplicacion.
-- REC00019 esta aplicado a INV00001, una factura que NO tiene `contrato_id`
-- (una de las 12 antiguas de LAW-38). Asi que:
--   · la rama A no lo ve, porque la factura no es de CR00020 (no es de nadie);
--   · la rama B lo descarta, porque el recibi SI tiene una aplicacion.
-- El dinero se cae por la rendija entre las dos.
--
-- Y lo importante, que es por lo que esto no es "un caso raro": la rama B se
-- desactiva con que exista UNA aplicacion cualquiera. O sea que el mismo agujero
-- se traga tambien:
--   · el resto no aplicado de un recibi aplicado en PARTE (recibi de 1.000
--     aplicado 400 a una factura del contrato -> los otros 600 desaparecian);
--   · cualquier recibi aplicado a una factura sin `contrato_id`, y de esas
--     quedan 3 vivas por 60.000 EUR: el problema se REPRODUCE cada vez que
--     alguien aplique un cobro nuevo contra una de ellas.
-- Hoy no habia ningun recibi parcial, pero nada lo impedia.
--
-- ARREGLO. La rama B deja de ser "recibis sin ninguna aplicacion" y pasa a ser
-- "la parte de cada recibi que no se ha atribuido a ningun contrato": su total
-- menos lo aplicado a facturas que SI tienen `contrato_id`. El dinero de un
-- recibi pertenece al contrato del recibi salvo que se haya atribuido
-- explicitamente a otro.
--
-- Se conserva a proposito el caso legitimo de aplicacion CRUZADA entre padre e
-- hijo (un recibi del Bloqueo aplicado a una factura de su Construccion): esa
-- aplicacion apunta a una factura CON contrato, asi que sigue contando en el
-- contrato de la factura y no se duplica en el del recibi.
--
-- Comprobado antes de aplicar, calculando la formula nueva contra los 36
-- contratos sin tocar la funcion: cambia EXACTAMENTE UNO, CR00020, de 0 a 1.000.
-- Todos los demas dan el mismo numero que hoy.
--
-- LO QUE ESTO **NO** ARREGLA, y sigue abierto:
--   · Los 9 recibis sin `contrato_id` (166.610 EUR de clientes reales) siguen
--     invisibles: no hay contrato al que sumarlos. Es LAW-38/LAW-40 y es una
--     decision del owner, no un bug de codigo: hay que decir a que contrato
--     corresponde cada uno.
--   · La parcela no avanza de estado si `unidades.contrato_id` esta suelto.
--     Ver LAW-55.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contrato_cobrado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260811035106_contrato_cobrado_fn.sql
--   supabase/migrations/20260814114541_contrato_cobrado_no_pierde_dinero.sql
--   supabase/migrations/20260917145913_carta_cobrado_al_bloquear_moneda_y_grant.sql
--   supabase/migrations/20260918014618_20260918_contrato_cobrado_reabre_sin_reabrir_el_oraculo.sql
--   supabase/migrations/20260918_contrato_cobrado_reabre_sin_reabrir_el_oraculo.sql
-- ============================================================================
