-- SEMIBLOQUEO: un contrato enviado a firma no se edita por accidente
-- 15-ago-2026, propuesta del owner.
--
-- EL HUECO, verificado contra las policies de produccion. La RLS de `contratos`
-- solo mira una cosa:
--     UPDATE ... USING (bloqueado = false AND es_agente() AND ... es_suyo(...))
-- Es decir: un contrato FIRMADO DEL TODO no lo puede editar nadie -- eso ya
-- estaba bien atado. Pero entre «enviado a firma» y «firmado» no habia NADA: un
-- contrato con un enlace de firma vivo, o con una de dos firmas ya recogidas, era
-- tan editable como un borrador en blanco.
--
-- POR QUE IMPORTA, y no es teorico: el 15-ago aparecieron dos contratos con la
-- cadena parada (CC00007 desde el 1-ago, CR00020 desde el 14) esperando a su
-- segundo firmante. Durante esas semanas, cualquiera podia cambiarles el texto
-- que el PRIMER comprador ya habia firmado. Nadie lo hizo, pero nada lo impedia.
--
-- LA REGLA. Si el contrato tiene alguna firma viva (`pendiente`) o ya recogida
-- (`firmado`), no se le puede tocar `datos` -- que es donde vive el texto y los
-- campos del documento. Para editarlo hay que ANULAR la firma primero, y eso es
-- una decision explicita que la app pide con un dialogo.
--
-- Y es la semantica correcta, no solo una barrera: si el texto cambia, la firma
-- que alguien dio sobre el texto ANTERIOR ya no vale. Anularla no es un castigo,
-- es lo que de verdad ha pasado.
--
-- LO QUE NO BLOQUEA, a proposito:
--   · `firma-submit` cerrando el contrato -- toca `bloqueado`, `pdf_firmado_path`
--     y `pdf_firmado_hash`, nunca `datos`. Verificado leyendo la funcion.
--   · el propio flujo de anular-y-editar: al anular, las firmas pasan a
--     `anulado`, ya no hay ninguna viva y el update entra sin necesidad de
--     ninguna bandera ni excepcion. Esa es la parte elegante -- no hay puerta
--     trasera que alguien pueda dejarse abierta.
--   · cambiar el color de portada, el nombre del contrato o cualquier otra cosa
--     que NO viva en `datos`... no aplica: todo eso vive en `datos`. Es
--     deliberado: si el documento cambia en algo, la firma anterior deja de
--     corresponder a lo firmado.
--
-- NADA SE BORRA. Las firmas anuladas se quedan como historia con
-- `estado = 'anulado'`, y su `snapshot_path` conserva el documento que el
-- comprador vio y firmo. Esa copia es la prueba, y sobrevive a la edicion.
--
-- 17-sep-2026: el raise exception se acorta (owner: "ve al grano"). El detalle
-- de cuántos enlaces/firmas hay ya no va en el mensaje -- el operador solo
-- necesita saber qué hacer, no el conteo; si hace falta el detalle está en
-- `contrato_firmas`. Ver migración 20260917040000_errores_de_guardado_al_grano.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contrato_no_editable_en_firma, trg_contrato_no_editable_en_firma
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260815002956_contrato_semibloqueo_en_firma.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
-- ============================================================================
