-- Serie PA para el nuevo tipo de contrato 'poa' (Poder Notarial / Surat Kuasa,
-- exhibit del Hak Sewa ante notario, ver templates/poa_notario.html) — 10-ago-2026.
-- Mismo patrón que las series ya existentes (RP, CC, CG, CO, CR, CA, AC, PO, PB,
-- C2, HS, CH): una secuencia propia y un caso más en set_contrato_numero(). No
-- toca ninguna fila existente. Aplicado en Supabase con apply_migration, espejado
-- aquí para que el repo no diverja de lo que hay en producción.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: set_contrato_numero
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260717073753_create_contratos_table.sql
--   supabase/migrations/20260717082752_contratos_add_remaining_types.sql
--   supabase/migrations/20260731075330_carta_reserva_ampliada.sql
--   supabase/migrations/20260804065545_numeracion_ppjb_bonian.sql
--   supabase/migrations/20260805023643_numeracion_hak_sewa.sql
--   supabase/migrations/20260806060951_numeracion_ppjb_bonian_c2.sql
--   supabase/migrations/20260806093122_numeracion_carta_reserva_hak_sewa.sql
--   supabase/migrations/20260810094256_contrato_numero_serie_poa.sql
--   supabase/migrations/20260831021755_cc00014_timon_numeracion_defensiva.sql
--   supabase/migrations/20260907083636_carta_reserva_pma.sql
--   supabase/migrations/20260908083655_adenda_tipo_y_serie_ad.sql
--   supabase/migrations/20260910025145_investor_deck_palmfield.sql
--   supabase/migrations/20260910025534_tipos_de_contrato_regenera_investor_deck.sql
-- ============================================================================
