-- contrato_cobrado(): recupera el EXECUTE de `authenticated` sin reabrir el
-- oráculo — incidente en vivo, 18-sep-2026
--
-- QUÉ PASÓ. La consulta de deploy de ayer (20260917145913) revocó el EXECUTE de
-- `authenticated` sobre `contrato_cobrado(uuid)` para cerrar un oráculo real:
-- cualquier sesión con rol `authenticated` (agente, o un comprador del portal
-- si comparte rol — mismo hallazgo que contexto/pendientes ya tenía fichado
-- para RLS) podía pedir `rpc/contrato_cobrado` con el uuid de un contrato ajeno
-- y leer lo cobrado. Diagnóstico correcto — pero esa misma revocación rompió
-- `contratos_cobrado_equipo()` (20260911031517, SECURITY INVOKER), que llama a
-- `contrato_cobrado(c.id)` DESDE la sesión del propio agente para cada fila que
-- la RLS de `contratos` ya le dejó ver. Sin el EXECUTE, esa llamada interna
-- también revienta: "permission denied for function contrato_cobrado" al abrir
-- Facturas, Compradores o Vencimientos — lo reportó el owner en vivo.
--
-- ARREGLO. No se reabre el oráculo, se cierra DENTRO de la función: antes de
-- sumar nada, `contrato_cobrado` exige ahora `es_agente()` (mismo candado que ya
-- usan las cinco `*_equipo()` desde el 11-sep) o `auth.role() = 'service_role'`
-- (la Edge Function factura-vencimiento la llama con la service key). Un
-- comprador del portal — que no es agente — recibe 0, no la cifra real: el
-- oráculo desaparece. Un agente cualquiera sigue viendo el total COMPLETO de
-- cualquier contrato del equipo, no solo el suyo — a propósito, igual que antes
-- de hoy: el cálculo de dinero no es cuestión de propiedad de fila (ver
-- 20260911031517 — "el recibí que salda la factura pudo emitirlo otro agente"),
-- y `carta_cobrado_al_bloquear()` (17-sep) sigue necesitando sumar Cartas de
-- Reserva de OTROS agentes sobre la misma parcela para el descuento en cascada.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contrato_cobrado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260811035106_contrato_cobrado_fn.sql
--   supabase/migrations/20260814114541_contrato_cobrado_no_pierde_dinero.sql
--   supabase/migrations/20260917145913_carta_cobrado_al_bloquear_moneda_y_grant.sql
--   supabase/migrations/20260918014618_20260918_contrato_cobrado_reabre_sin_reabrir_el_oraculo.sql
--   supabase/migrations/20260918_contrato_cobrado_reabre_sin_reabrir_el_oraculo.sql
-- ============================================================================
