-- APLICADA en producción el 29-jul-2026 (MCP supabase-lawang, migración
-- `contratos_contrato_padre_id`). Se guarda aquí como registro, igual que el
-- resto de sql/ — no hace falta volver a correrla.
--
-- Vínculo entre contratos de la misma venta (obra → su reserva/PPJB).
-- Lo escribe contracts/app.html al guardar (el número elegido en el desplegable
-- «Nº del Contrato de Reserva/PPJB vinculado» se resuelve a id); lo lee
-- /intranet/operaciones/ para juntar ambos documentos en una sola operación.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contratos_padre_idx
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729025648_contratos_contrato_padre_id.sql
-- ============================================================================
