-- Tope del descuento comercial de Construcción, en el SERVIDOR — 21-sep-2026,
-- revisión previa #33 (Legal + Administración + Seguridad).
-- ════════════════════════════════════════════════════════════════════════════
-- QUÉ RESUELVE. `contracts/app.html` deja aplicar un `descuento_comercial` al
-- precio de techo+extras de un Contrato de Construcción, con dos candados de
-- PANTALLA: solo super_admin/admin lo tocan (ROLES_HITOS_FIJOS/
-- puedeHitosFijos, reutilizado), y no se guarda si supera el 15% de
-- techo+extras o si falta el motivo con descuento>0 (guardarContrato()).
--
-- ⚠️ HALLAZGO DE SEGURIDAD ANTES DE ESCRIBIR ESTO (verificado, no supuesto):
-- ambos candados son SOLO de pantalla. `contratos.precio_total` no tiene
-- ningún CHECK, y la RLS de `contratos` no mira el rol de quien escribe ni el
-- contenido de `datos` — quien llame a PostgREST/al RPC directamente (o abra
-- la consola del navegador) salta los dos sin que nada en el servidor se
-- entere. Mismo patrón de deuda que ya documentaba el candado de
-- `validez_dias`/FIJOS_ESTUDIO, ahora aplicado a un descuento sobre dinero.
--
-- QUÉ CUBRE ESTE TRIGGER Y QUÉ NO (dicho explícito, no se infla el alcance):
--   · SÍ valida el TOPE del 15% cuando el techo elegido viaja en `datos.techo`
--     con forma reconocible (número en `precio`) — que es como lo escribe
--     `contractPayload()` hoy siempre que hay techo elegido.
--   · SÍ valida que `descuento_comercial` nunca sea negativo.
--   · SÍ es el cinturón final CUANDO HAY DESCUENTO (`v_descuento > 0`), tanto
--     si el 15% se pudo calcular como si no (formato inesperado en
--     `datos.techo`/`datos.extras`): `precio_total` (columna propia, ya
--     numérica) no puede quedar en cero ni negativo por culpa de ese
--     descuento. ⚠️ CORREGIDO el mismo día (migración
--     …_fix_precio_total_incondicional, hallado por autorrevisión antes de
--     cerrar la tarea): la primera versión de este cinturón NO estaba
--     condicionada a que hubiera descuento, así que bloqueaba CUALQUIER
--     UPDATE de un contrato tipo=construccion — y hay contratos reales
--     (CC00040/CC00076/CC00086) con `precio_total` NULL sin ningún descuento,
--     que habrían quedado inguardables para cualquier otra edición.
--   · NO valida el ROL de quien escribe — igual que `validez_dias`/
--     FIJOS_ESTUDIO, comprobar "qué rol tiene la sesión que hizo este UPDATE"
--     no es un dato que un trigger de fila pueda leer sin más infraestructura
--     (una tabla de sesión→rol o un claim de JWT propio, que hoy no existe
--     para este propósito) — igual que el resto de candados de rol de esta
--     suite, sigue siendo de pantalla. Dicho aquí para que quede escrito, no
--     escondido: quien tenga acceso directo a la API con la sesión de un
--     sales_manager puede seguir poniendo el descuento él mismo saltándose
--     app.html. Cerrar ESO es un encargo aparte (rol real en servidor), fuera
--     del alcance de esta tarea.
--   · NO exige el motivo cuando hay descuento — eso tampoco es un hueco de
--     seguridad (no protege dinero), solo higiene de datos, y ya lo cubre la
--     pantalla.
-- ════════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: descuento_comercial_construccion_valido, trg_descuento_comercial_construccion
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260921122811_descuento_comercial_construccion_valido.sql
--   supabase/migrations/20260921124646_descuento_comercial_construccion_valido_fix_precio_total_incondicional.sql
--   supabase/migrations/20260922013705_precio_construccion_cuadra_con_techo.sql
-- ============================================================================
