-- ════════════════════════════════════════════════════════════════════════════
-- EL DINERO DEJA DE SER TEXTO — 19-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- `contrato_vencimientos.monto` y `.pct` eran `text`, y son las DOS únicas
-- columnas de dinero de toda la base que lo eran. Dentro conviven «5000» y
-- «22.250»: qué significa ese punto depende de quién lo lea, y eso ya ha
-- costado dinero en este estudio (el depósito a 500 en la web y a 1.000 en el
-- motor del bot, cobrando el doble durante una semana).
--
-- QUÉ SIGNIFICA EL PUNTO AQUÍ, comprobado contra la aritmética del contrato y
-- no a ojo — RP00012 tiene monto «42.215» con pct 100 sobre un precio_total de
-- 42.215 €, y CC00029 «17.592» con 32,58% sobre 54.000 (= 17.593). Es
-- SEPARADOR DE MILES en los 13 casos que lo llevan. Ninguno es decimal.
--
-- ⚠️ POR QUÉ NO BASTA CON UN `::numeric`: Postgres castea '22.250' a 22,25 sin
-- rechistar. Convertir a lo bruto habría dividido esos importes por mil y nada
-- habría dado error. Se convierte con la MISMA regla que usa la interfaz.

-- ── la regla de leer un importe, gemela de lwParseImporte ───────────────────
-- ⚠️ Es la SEGUNDA copia de esa regla, y eso normalmente está prohibido aquí.
-- Se acepta porque los dos lados leen lo mismo desde sitios distintos —el
-- navegador lee lo que el agente teclea, la base lee lo que quedó guardado— y
-- porque el bloque de autocomprobación de abajo lleva LOS MISMOS CASOS que
-- `assets/dinero.test.js`: si una de las dos deriva, esta migración no aplica.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: lw_importe
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260819154931_lw_importe_regla_de_leer_dinero.sql
-- ============================================================================
