-- destructivo-ok: `create or replace view`, mismas columnas y orden — no borra
-- filas ni objetos, solo cambia CÓMO se resuelve el join.
-- ════════════════════════════════════════════════════════════════════════════
-- documentos_desactualizados TARDABA 4,5 SEGUNDOS EN CADA CARGA — 24-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Hallazgo de Desarrollo (auditoría pedida por el owner tras el fix de hoy de
-- `contratos_del_mismo_comprador`, la MISMA familia de bug): el rama de
-- `contrato` de esta vista unía por
--   `join public.clients cl on cl.id = (c.datos->>'adq1_client_id')::uuid`
-- — leer una clave de `datos` (el jsonb con firmas/anexos en base64, hasta
-- 7,3 MB por fila) obliga a Postgres a destoastear el valor ENTERO por cada
-- fila de `contratos` para poder evaluar el join. Medido con `explain
-- (analyze, buffers)` contra los 111 contratos reales: 4,48 SEGUNDOS y 31.535
-- buffers — la misma magnitud que los 4,27 s de `contratos_del_mismo_comprador`
-- antes de arreglarla hoy mismo.
--
-- Esta vista la lee `lwDivergencias()` (contracts/assets/ficha_divergencia.js)
-- en CADA apertura del listado de Contratos y de Facturas — no es una consulta
-- rara, es tráfico constante.
--
-- LA CURA, la misma de hoy: `contrato_compradores` ya tiene `client_id` del
-- adquiriente_1 en una tabla sin el jsonb pesado, indexada por
-- `(contrato_id, rol)` y por `client_id`, mantenida al día por
-- `sincronizar_compradores()`. Se une por ahí; los campos que SÍ hace falta
-- comparar (nombre, pasaporte, email...) se siguen leyendo de `datos`, pero
-- solo para las filas que YA hicieron match — no como condición del join sobre
-- TODAS las filas.
--
-- La rama de `factura` no se toca: ya unía por `f.client_id`, una columna
-- real, no un jsonb.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: documentos_desactualizados
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260819141250_documentos_al_dia_con_su_ficha.sql
--   supabase/migrations/20260824044334_documentos_al_dia_sin_leer_el_blob.sql
--   supabase/migrations/20260917005548_divergencia_contrato_sin_domicilio.sql
--   supabase/migrations/20260917012943_divergencia_factura_sin_domicilio.sql
--   supabase/migrations/20260917020000_divergencia_contrato_sin_domicilio.sql
--   supabase/migrations/20260917050000_divergencia_factura_sin_domicilio.sql
-- ============================================================================
