-- ════════════════════════════════════════════════════════════════════════════
-- UN DOCUMENTO VIVO NO PUEDE CONTRADECIR A SU FICHA — 19-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- EL CASO (owner): corrige la ficha de CSP CONCEPTS —el NIF estaba en el campo
-- del domicilio— y la factura INV00037 sigue diciendo lo de antes. Y el
-- contrato RP00044 también. La cadena **ficha → contrato → factura viaja por
-- COPIA**, y nadie vuelve atrás: corregir el origen no arregla lo que ya salió.
--
-- LA DECISIÓN DEL OWNER, y ordena todo lo demás:
--   · Documento VIVO      → sigue a la ficha (se avisa y se traen los datos).
--   · Documento CONGELADO → no se toca NUNCA. Corregirlo es reemitirlo.
-- Vivo/congelado no es un campo nuevo: es lo que cada documento ya dice de sí
-- mismo — un contrato `bloqueado` está firmado; una factura `enviada` está en
-- manos del cliente; una `anulada` es historia.
--
-- ⚠️ `facturas.client_id` va ADEMÁS de `contrato_id`, nunca en su lugar (aviso
-- del owner): los hitos, los vencimientos, `contrato_cobrado`, la facturación
-- automática y el avance de unidades cuelgan del CONTRATO. Aquí solo se añade
-- de QUIÉN es la factura, que hoy no se sabe más que por el texto copiado.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: diferencias_con_ficha, documentos_desactualizados, facturas_client_idx
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260819141250_documentos_al_dia_con_su_ficha.sql
--   supabase/migrations/20260819141345_diferencias_con_ficha_sin_falsos_positivos.sql
--   supabase/migrations/20260821154831_auditoria_revocar_triggers_del_21ago_y_search_path.sql
--   supabase/migrations/20260824044334_documentos_al_dia_sin_leer_el_blob.sql
--   supabase/migrations/20260917005548_divergencia_contrato_sin_domicilio.sql
--   supabase/migrations/20260917012943_divergencia_factura_sin_domicilio.sql
--   supabase/migrations/20260917020000_divergencia_contrato_sin_domicilio.sql
--   supabase/migrations/20260917050000_divergencia_factura_sin_domicilio.sql
-- ============================================================================
