-- ════════════════════════════════════════════════════════════════════════════
-- EL ESTADO SE REFRESCA POR ID, NO SOLO POR TEXTO · LAW-73 REABIERTA CON INVENTARIO
-- 21-sep-2026 · encargo del owner · revisión previa: Datos + Desarrollo (revisión
-- previa #29, folio en CEO/revisiones/estado.json) + advisor (corrigió el plan:
-- el enlace por ID que hacía falta YA EXISTE, es `unidades.contrato_id`)
-- ════════════════════════════════════════════════════════════════════════════
-- POR QUÉ EXISTE. RP00116 (Yolanda Bartolome Gonzalez, Bloqueo de Parcela) se
-- firmó el 27-ago-2026 (`bloqueado=true`, PDF firmado) pero `unidades.estado`
-- se quedó en `reservada` en vez de pasar a `bloqueada`. Causa: el bucle de
-- `sincroniza_unidad_contrato()` ata y mueve el estado de una unidad SOLO
-- cuando `unidades.codigo` casa EXACTO con el texto de
-- `datos.fields.parcela_codigo`. La unidad real es `W3.1. - D5` (con punto);
-- el contrato traía `W3.1 - D5` (sin él) — una corrección manual de este
-- mismo contrato en agosto (`rp00116_corrige_parcela_codigo.sql`, owner:
-- "está vinculado a A5, que está fuera de inventario") se hizo por SQL
-- directo, fuera de `contracts/app.html`, y tecleó el código sin pasarlo por
-- el desplegable — que es justo la vía que `parcela_inventario.js` protege
-- desde LAW-73 para que esto no pueda pasar tecleando a mano.
-- El UPDATE de la firma SÍ disparó el trigger (`trg_sincroniza_unidad` es
-- `AFTER INSERT OR UPDATE` sin `OF`, verificado con `pg_get_triggerdef`), pero
-- el `UPDATE ... WHERE u.codigo = cod` del bucle no encontró ninguna fila —
-- silencioso, cero aviso.
--
-- LA CORRECCIÓN NO ES UNA TABLA NUEVA. La primera versión de este plan
-- proponía una tabla puente `contrato_parcelas`. El enlace por ID que hacía
-- falta ya existe y ya es la fuente de verdad para todo lo demás del sistema
-- (`avanza_unidad_por_cobro`, `libera_reserva`, `unidades_estado`): es
-- `unidades.contrato_id`, y ya apuntaba bien a RP00116 — el texto era lo
-- único desincronizado. Lo único que faltaba era que, además de atar por
-- texto (necesario: así nace el enlace y así se detectan choques/traspasos),
-- la función refrescara el estado de TODO lo que YA está enlazado por ID,
-- pase lo que pase con el texto ese día. Eso es lo que añade el bloque nuevo
-- al final del bucle — ni tabla, ni RLS nueva, ni backfill.
--
-- LAW-73, REABIERTA (decisión del owner, 21-sep-2026, "la opción 2 es mucho
-- mejor que la 1" sobre la revisión previa #29). Hasta hoy un código que no
-- casaba con ninguna unidad se guardaba callado a propósito (`contracts/sql/
-- exige_parcela_al_guardar.sql`, "FUERA DE ALCANCE A PROPÓSITO") para no
-- bloquear un proyecto sin inventario cargado. Ahora, si el PROYECTO ya tiene
-- inventario, un código que no casa con NINGUNA unidad de ese proyecto para
-- el guardado — habría cazado el propio error de agosto en el momento de
-- teclearlo. Si el proyecto no tiene ninguna unidad cargada todavía, se
-- sigue dejando pasar: la regla original de LAW-73 sigue viva para ese caso,
-- textual.
-- Acotado igual que el resto de esta función (comentario de
-- `exige_parcela_al_guardar.sql`, "la regla solo muerde cuando el UPDATE TOCA
-- esos campos"): si el proyecto y los códigos son idénticos a los de OLD, se
-- deja pasar igual que hasta hoy — si no, el legado (37 contratos, 18
-- firmados) se vuelve imposible de tocar por un motivo ajeno al que se está
-- editando.
--
-- LO QUE ESTO NO CIERRA A PROPÓSITO: los 37 contratos legado que YA tienen el
-- texto desincronizado no disparan la excepción nueva mientras nadie toque
-- `parcela_codigo`/`proyecto_nombre` en ellos — y el catch-all por ID de
-- arriba solo arregla el ESTADO, no el texto impreso. Para verlos en un
-- listado (no solo cuando el bucle los cruza) queda la vista
-- `contratos_sin_parcela_vinculada` de más abajo — el "no callar" que pedía
-- Desarrollo en la revisión previa. Wiring visual en la pantalla de
-- Contratos/Operaciones: pendiente, tarea de Desarrollo aparte.
--
-- IDEMPOTENTE: `create or replace function` + `create or replace view`. No
-- toca datos, no backfillea nada, no dispara `trg_registra_edicion_privilegiada`
-- (no hay ningún UPDATE sobre `contratos` en este fichero).
-- ════════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contratos_sin_parcela_vinculada, sincroniza_unidad_contrato
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
