-- ════════════════════════════════════════════════════════════════════════════
-- EL ENLACE DEL COMPRADOR DEJÓ DE HACERSE, Y NADIE LO VIO — 19-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- SÍNTOMA: los 7 contratos creados hoy (RP00053-58 y CR00035) traían su
-- `datos.adq1_client_id` pero NO tenían fila en `contrato_compradores`. Todos
-- los de ayer sí. O sea: el enlace se rompió en algún momento de la madrugada.
--
-- CAUSA, y es una regresión de la propia auditoría de esta mañana. El hallazgo
-- decía: «`sincronizar_compradores` tiene EXECUTE para anon — una definer que
-- escribe, invocable sin sesión por REST». Cierto y bien cazado. Pero el
-- arreglo fue `revoke all ... from public, anon`, y **el EXECUTE que usaba
-- `authenticated` venía justamente por PUBLIC**. Desde entonces:
--
--   guardar contrato → trg_compradores_desde_datos (INVOKER)
--                    → public.sincronizar_compradores(...)  ← permission denied
--                    → el handler lo convierte en RAISE WARNING
--                    → el contrato se guarda igual, sin enlace, sin ruido
--
-- El WARNING va al log del servidor, que no mira nadie. Es la forma más cara de
-- fallar: todo parece funcionar.
--
-- ARREGLO: no reabrir la función —eso deshace la auditoría—, sino que el
-- TRIGGER sea `security definer`. Así la llamada corre como su dueño (postgres)
-- y REST sigue cerrado para anon Y para authenticated, que era el objetivo.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: trg_sincronizar_compradores
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260804041013_compradores_desde_contrato.sql
--   supabase/migrations/20260819101011_trigger_compradores_definer_y_ruidoso.sql
-- ============================================================================
