-- ============================================================================
-- El tipo de contrato y el dinero mandan sobre el estado — 12-ago-2026
-- ----------------------------------------------------------------------------
-- Supera el CASE de `sincroniza_unidad_contrato()` en vinculo_contrato_unidad.sql
-- (31-jul-2026), que solo miraba `contratos.bloqueado` (firmado sí/no) y por eso
-- CUALQUIER contrato firmado —una Carta de Reserva incluida— saltaba directo a
-- `vendida`. Bug real reportado por el owner: firmar una Carta de Reserva no
-- debe mover la parcela ni generar proforma (la proforma ya se corrigió el
-- 12-ago en `crearProformaAutomatica`/`enviarProformaTotal`; esto corrige el
-- otro efecto del mismo bug, el estado).
--
-- FLUJO NUEVO:
--   · Carta de Reserva (CR), crear o firmar   → reservada (firmar NO avanza)
--   · Bloqueo de Parcela (RP), crear          → reservada
--   · Bloqueo de Parcela (RP), firmar         → bloqueada
--   · Contrato de Construcción (CC)           → no toca el estado de la parcela
--   · primer recibí real cobrado              → vendida
--   · 100% cobrado (misma base que ya usa la
--     ficha de Unidades: `contrato_cobrado()` contra `unidades.precio`) → cobrada
--
-- 'bloqueada' SE REUSA para dos causas — bloqueo manual (litigio, reserva
-- verbal que la base no conoce) y la firma automática de un RP — porque
-- pedirle al owner dos valores en el enum para "la parcela no se puede vender
-- a otro" es la misma pregunta dos veces. NO se guarda de cuál de las dos
-- viene: se DERIVA en cada evaluación (¿el contrato vinculado hoy es un RP
-- firmado? si sí, el automatismo puede seguir moviéndola; si no, es manual y
-- se protege igual que siempre). Guardar un origen en una columna aparte
-- sería una tercera copia de un dato que ya está en `contratos.tipo` +
-- `contratos.bloqueado` — la misma razón por la que el AVANCE DE COBRO
-- tampoco se guarda (comentario original de más abajo).
--
-- LÍMITE CONOCIDO, a propósito: ni este trigger ni `avanza_unidad_por_cobro`
-- REVIERTEN un estado. Si se anula el recibí que llevó una parcela a
-- `vendida`/`cobrada`, la parcela se queda ahí — mismo criterio que ya tenía
-- `sincroniza_unidad_contrato` (una edición del contrato tampoco hacía
-- retroceder `vendida`). Corrección manual desde `/intranet/proyectos/`.
-- ============================================================================

-- ---- 1) el tipo de contrato decide el TECHO al que llega la firma sola ----

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: avanza_unidad_por_cobro, sincroniza_unidad_contrato, trg_avanza_por_aplicacion, trg_avanza_por_recibi, unidades_estado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260805024801_unidades_estado_con_obra.sql
--   supabase/migrations/20260810100129_unidades_estado_vista_fase_zona.sql
--   supabase/migrations/20260810101230_unidades_estado_restaura_security_invoker.sql
--   supabase/migrations/20260811035145_unidades_estado_solo_recibi.sql
--   supabase/migrations/20260812042114_estado_unidad_por_tipo_y_cobro_fix_view.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260812043919_avanza_unidad_por_cobro_fix_forward.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260819044137_cobro_repartido_entre_unidades.sql
--   supabase/migrations/20260824035201_construccion_por_parcela.sql
--   supabase/migrations/20260826112241_unidades_estado_precio_efectivo.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260902022413_unidades_estado_restaura_security_invoker_2.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260911005624_unidades_estado_agente_creador.sql
--   supabase/migrations/20260911085553_unidades_estado_cobrado_suelo_obra.sql
--   supabase/migrations/20260911085617_unidades_estado_restaura_security_invoker_3.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260915004928_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915005638_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260915100000_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915104500_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260916040622_avanza_unidad_por_cobro_exige_suelo_100.sql
--   supabase/migrations/20260916093309_unidades_codigo_orden_natural.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
