-- ════════════════════════════════════════════════════════════════════════════
-- UN CONTRATO QUE RESERVA PARCELA NO SE GUARDA SIN PROYECTO Y SIN PARCELA
-- 14-sep-2026 · encargo del owner · revisión previa: Datos + Desarrollo
-- 17-sep-2026: los dos raise exception de abajo se acortaron (owner: "ve al
-- grano, el operador no necesita el porqué"). El porqué se queda en ESTE
-- comentario, no en el texto que ve el operador — ver migración
-- 20260917040000_errores_de_guardado_al_grano.
-- ════════════════════════════════════════════════════════════════════════════
-- POR QUÉ EXISTE. RP00164 (54.204 €) se guardó sin proyecto y con el código de
-- la subparcela ("C3") escrito en `parcela_master` —el código del terreno
-- entero— en vez de en `parcela_codigo`. Como la plantilla imprime cada campo
-- en una frase distinta, el PDF que firmaron las dos partes dice «parcela
-- máster C3» y deja EN BLANCO el número de la parcela que se cede. Y como
-- `sincroniza_unidad_contrato()` lee `parcela_codigo` para atar la unidad, la
-- parcela C3 se quedó `disponible` con el contrato firmado y 27.102 € cobrados:
-- vendible dos veces, sin que nada avisara.
--
-- El agujero por el que salió está escrito literalmente aquí abajo, en esta
-- misma función: un `return new` mudo. Este fichero lo convierte en un error.
--
-- POR QUÉ SE MODIFICA ESTA FUNCIÓN Y NO SE AÑADE UN TRIGGER HERMANO.
-- Un `trg_exige_parcela` aparte serían dos triggers razonando sobre los mismos
-- dos campos, con orden de disparo por nombre alfabético y con la lista de
-- tipos duplicada — la familia de fallo que este repo ya paga tres veces. El
-- sitio donde la falta de parcela YA se detecta es este `if`; lo único que le
-- faltaba era hablar.
--
-- LA LISTA DE TIPOS NO SE ESCRIBE A MANO. Sale de `contrato_tipo_etapa`
-- (`etapa = 'reserva'`), que es donde el estudio ya declara qué tipos reservan
-- una parcela: reserva_parcela, carta_reserva, carta_reserva_ampliada,
-- carta_reserva_hak_sewa y carta_reserva_pma. Un tipo nuevo de reserva hereda
-- el guardarraíl el día que se le pone su etapa, sin tocar este fichero.
-- `construccion` queda fuera sola y por el motivo correcto: su etapa es
-- 'contrato', y además se vincula por `unidad_id`, no por código de parcela.
--
-- LA SALIDA PARA EL LEGADO, QUE TAMBIÉN PROTEGE LAS ALTAS NUEVAS.
-- Hay 37 contratos ya guardados que no cumplirían la regla, 18 de ellos
-- firmados. Rechazar todo UPDATE los dejaría imposibles de anular y de
-- corregir — incluido RP00164, que es justo al que hay que ir. Peor: esta
-- misma función hace `update public.contratos set contrato_padre_id` sobre el
-- contrato VIEJO en el traspaso carta→bloqueo, así que guardar un contrato
-- nuevo y perfectamente válido abortaría por culpa de un legado ajeno, con un
-- mensaje hablando de otro contrato.
-- Por eso la regla solo muerde cuando el UPDATE TOCA esos campos: si el
-- proyecto y los códigos son idénticos a los de OLD, se deja pasar. Se puede
-- anular, cobrar y corregir lo demás; lo que no se puede es dejarlos mal
-- habiéndolos tocado.
--
-- FUERA DE ALCANCE A PROPÓSITO: que el código EXISTA en `unidades`. Cerraría
-- también los 23 códigos huérfanos que LAW-73 dejó vivos, pero bloquea guardar
-- en un proyecto cuyas unidades aún no están cargadas. Es una decisión del
-- owner, no un detalle de implementación — va anotada aparte.
--
-- IDEMPOTENTE: es un `create or replace` de la función. Correrlo dos veces
-- deja lo mismo. No toca datos, no toca la tabla, no borra nada.
-- ════════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: sincroniza_unidad_contrato
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
