-- ============================================================================
-- FACTURAS — el emisor se congela en el documento, y el numero deja de estar
-- al alcance del navegador
--
-- Sale de la revision previa del 17-sep-2026 (Datos + Administracion +
-- Seguridad) sobre el plan de abrir la intranet a mas empresas. Tres de los
-- hallazgos NO son sobre el futuro: son defectos de hoy.
--
-- 1. EL EMISOR NO ESTABA CONGELADO. Razon social, NPWP y domicilio se leen en
--    vivo de `SOCIEDADES` al imprimir, asi que los 412 documentos ya emitidos se
--    reimprimen siempre con la identidad de HOY. Ya paso dos veces: Tepi Sun Gai
--    cambio como se imprime su nombre el 31-jul-2026 y de representante el
--    11-ago-2026. Mientras eso exigia un commit quedaba en git; desde que
--    `public.sociedades` es editable desde un panel, un UPDATE lo haria al
--    instante y sin rastro. A partir de aqui cada documento nace con su emisor
--    dentro, en `datos->'emisor'`.
--    ⚠️ Solo hacia adelante. Los 412 anteriores se quedan como historico
--    documentado (decision del owner, 17-sep-2026): rellenarlos hacia atras es
--    un UPDATE masivo sobre una tabla con cinco triggers de fila, dos de los
--    cuales se tragan los errores, y ademas seria mejor esfuerzo — la identidad
--    anterior al 11-ago ya no se puede reconstruir desde la base.
--
-- 2. CUALQUIER AGENTE PODIA CAMBIAR EL EMISOR DE UNA FACTURA YA ENVIADA. De los
--    doce triggers de `facturas`, ninguno congelaba `sociedad`; el unico que
--    congela algo (`factura_anulada_solo_cambia_autor`) solo actua si la factura
--    ya esta anulada. Un PATCH bastaba para que un documento enviado cambiase de
--    empresa conservando su numero.
--
-- 3. EL NUMERO LO PODIA PONER EL CLIENTE. `set_factura_numero` solo actua si
--    `new.numero is null`, asi que el navegador podia mandar el numero que
--    quisiera y el unico freno era el UNIQUE global.
--
-- Y el marco: verificado en `pg_default_acl` que `anon` tiene hoy INSERT, UPDATE
-- y SELECT sobre las 21 columnas de `facturas`. Lo unico que lo salva es que las
-- policies son todas `{authenticated}`. Eso es «el GRANT manda antes que la
-- policy» con la tabla del dinero delante.
--
-- LO QUE ESTA MIGRACION NO HACE: no separa las series por sociedad. El owner
-- decidio el 17-sep NO hacerlo todavia (LAW-235, necesita contable indonesio).
-- Las tres secuencias globales siguen intactas y no se toca ni un numero.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. El trigger de numeracion pasa a SECURITY DEFINER.
-- Motivo: para poder quitarle a `anon`/`authenticated` el privilegio sobre las
-- secuencias hace falta que `nextval` lo ejecute el dueño de la funcion y no el
-- que inserta. ORDEN IMPORTANTE: primero DEFINER, despues el revoke. Al reves,
-- toda alta de factura desde la pantalla falla.
-- ---------------------------------------------------------------------------

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: congela_emisor_factura, contrato_sociedad_existe, factura_enviada_no_cambia_emisor, set_factura_numero, trg_congela_emisor, trg_contrato_sociedad_existe, trg_factura_enviada_no_cambia_emisor
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917082716_facturas_emisor_congelado_y_permisos.sql
--   supabase/migrations/20260917092031_fix_contrato_sociedad_existe_ambiguedad.sql
--   supabase/migrations/20260917092917_congela_emisor_tambien_en_update.sql
--   supabase/migrations/20260917093621_congela_emisor_recalcula_si_cambia_sociedad.sql
--   supabase/migrations/20260917161500_facturas_emisor_congelado_y_permisos.sql
--   supabase/migrations/20260917174500_congela_emisor_tambien_en_update.sql
--   supabase/migrations/20260917182000_congela_emisor_recalcula_si_cambia_sociedad.sql
-- ============================================================================
