-- LAW v4 paridad lanzamiento, S14 (encargo 20260919, revision previa #34 con Legal+Seguridad+Administracion).
-- Decision del owner 21-sep-2026: una factura/recibi/proforma YA ENVIADA a un comprador real
-- (facturas.enviada = true) no se puede borrar NUNCA desde el panel, ni por super_admin.
-- Unico camino que queda para un documento enviado: Anular. Solo sigue siendo borrable un
-- borrador interno que nunca salio del sistema (enviada = false).
--
-- Toca la policy "borrar facturas" de public.facturas (creada en
-- 20260819044926_law71_editar_firmado_y_borrar_facturas.sql). Anade "AND NOT enviada" a las DOS
-- ramas (super_admin y admin) sin tocar ninguna otra condicion (anulada / recibi_aplicaciones
-- para la rama admin se quedan exactamente igual).

-- destructivo-ok: drop+create de policy es el patron estandar del estudio para reemplazar una
-- policy (departamentos/datos/prompt.md permite crear/drop policy sin preguntar); no borra datos.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: borrar
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731045054_borrado_con_permisos_y_enlaces.sql
--   supabase/migrations/20260819044926_law71_editar_firmado_y_borrar_facturas.sql
--   supabase/migrations/20260821153053_policy_borrar_facturas_a_authenticated.sql
--   supabase/migrations/20260917010415_comision_admin_intranet.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
--   supabase/migrations/20260921125405_law_facturas_enviada_no_se_borra.sql
-- ============================================================================
