-- ════════════════════════════════════════════════════════════════════════════
-- FIX URGENTE: LAS DOS MIGRACIONES DE HOY BORRARON EL BLINDAJE DE liberado_en
-- 21-sep-2026 · encontrado por advisor antes de dar la tarea por cerrada
-- ════════════════════════════════════════════════════════════════════════════
-- QUÉ PASÓ. Las migraciones `enlace_por_id_y_law73_reabierta` (08:09) y
-- `law73_reabierta_ambito_por_codigo` (08:17) de HOY se escribieron a partir
-- de `contracts/sql/exige_parcela_al_guardar.sql` (14/17-sep) — la copia
-- legible que se supone es la fuente de la función. Esa copia estaba
-- DESACTUALIZADA: la migración `20260921060542_libera_reservas_vencidas`
-- (aplicada esta misma mañana, otra sesión, antes que las mías) ya había
-- modificado `sincroniza_unidad_contrato()` para añadir el blindaje de
-- `liberado_en` (`libera_reserva()`, el RPC que libera una reserva vencida o
-- desistida) y nadie refrescó la copia legible tras aplicarla. Mis dos
-- `create or replace function` de hoy sobrescribieron esa función SIN esas
-- dos piezas:
--   1. La guarda de entrada `if new.liberado_en is not null then return new;
--      end if;` — sin ella, el propio `update contratos set liberado_en =
--      now()` que hace `libera_reserva()` vuelve a pasar por TODO el cuerpo
--      de la función, incluido mi catch-all nuevo, que hace
--      `update unidades set contrato_id = new.id, estado = 'reservada' ...`
--      sobre la unidad que el mismo `libera_reserva()` acababa de poner
--      `disponible` un instante antes — **la reserva liberada se re-reserva
--      sola**, en la misma transacción, sin ningún error.
--   2. `and c.liberado_en is null` en el lookup de "ocupada" — sin ella, un
--      contrato ya liberado sigue contando como que "ocupa" su parcela vieja,
--      bloqueando una reserva nueva y legítima sobre una unidad ya libre.
-- Ninguna de las dos migraciones de hoy tocó estas líneas A PROPÓSITO — se
-- perdieron por trabajar sobre una copia vieja. Este fichero las restaura
-- TAL CUAL estaban en la migración de esta mañana (`libera_reservas_vencidas`,
-- fuente verificada con `grep` sobre ese fichero) y injerta SOLO las piezas
-- de hoy encima — nada más se reestructura.
--
-- TAMBIÉN SE DESHACE una unificación que nadie revisó: la primera migración
-- de hoy cambió la condición del bloque de desvinculación (arriba del todo)
-- de comparar el TEXTO crudo `(old.datos->'fields'->>'proyecto_nombre') is
-- distinct from (new.datos->'fields'->>'proyecto_nombre')` a comparar
-- `proy_ant is distinct from proy` (con `coalesce` a la columna
-- `proyecto_nombre`) — un cambio semántico real para contratos con ese campo
-- vacío en `datos.fields`, que no formaba parte de ningún hallazgo de la
-- consulta de deploy. Se restaura la comparación original; `proy_ant` se
-- sigue calculando (coalesced) pero SOLO se usa para el guardarraíl nuevo de
-- LAW-73, no para el desvinculado.
--
-- VERIFICACIÓN antes de aplicar (en transacción, con rollback, contra un
-- contrato real): `libera_reserva()` sobre una unidad reservada por una
-- Carta de Reserva no liberada deja la unidad en `disponible`/`contrato_id
-- null` — no vuelve a `reservada`.
--
-- IDEMPOTENTE: `create or replace function`. No toca datos.
-- ════════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: sincroniza_unidad_contrato
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
