-- APLICADA en producción el 29-jul-2026 (MCP supabase-lawang, migración
-- `hash_pdf_firmado`). Registro, no hace falta volver a correrla.
--
-- Integridad probatoria del PDF firmado (UU ITE 11/2008): con el bucket en
-- upsert no hay forma de demostrar que el fichero no cambió — el hash SHA-256
-- guardado en el registro sí lo prueba. Lo escriben firma-submit (firma
-- remota) y la subida manual de app.html.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: (fichero de ALTER/INSERT, sin CREATE)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729051748_hash_pdf_firmado.sql
-- ============================================================================
