-- ════════════════════════════════════════════════════════════════════════════
-- LAW-73 REABIERTA: EL ÁMBITO ES POR CÓDIGO, NO POR CONTRATO — 21-sep-2026
-- Fix-forward sobre `enlace_por_id_y_law73_reabierta.sql` (mismo día, consulta
-- de deploy capa 1, hallazgo ALTA de Desarrollo).
-- ════════════════════════════════════════════════════════════════════════════
-- EL BUG. La migración anterior gateaba la excepción nueva con `toca_parcela`,
-- una bandera de TODO el contrato: true si el array `cods` entero cambiaba
-- respecto a OLD. Caso real encontrado por Desarrollo: RP00126 (Java Sunset
-- S2) tiene `parcela_codigo = "PLOT 6, S1 - H6"` — "PLOT 6" está en el
-- inventario, "S1 - H6" no (legado, chip sin ✕, no se puede tocar desde la
-- UI). El flujo normal y SOPORTADO de "añadir otra parcela"
-- (`pintarSelectorParcela`/`parcela_inventario.js`) cambia el array `cods` al
-- añadir una tercera parcela válida → `toca_parcela = true` para TODO el
-- contrato → el bucle volvía a evaluar "S1 - H6", que nadie estaba tocando, y
-- reventaba con la excepción de LAW-73. Un guardado legítimo bloqueado por un
-- código que ni siquiera aparecía en el formulario que se estaba editando.
--
-- LA CORRECCIÓN. El guardarraíl de LAW-73 se mueve de "¿tocó el contrato
-- parcela o proyecto?" a "¿es ESTE código concreto nuevo en el contrato, o
-- cambió el proyecto?" — por código, dentro del propio FOREACH, no por
-- contrato. Un código que YA estaba en `cods_ant` y sigue en `cods` tal cual
-- no se revalida aunque el contrato gane o pierda OTRAS parcelas en el mismo
-- guardado. Si cambia el proyecto, sí se revalidan todos — un código válido
-- en el proyecto viejo no tiene por qué existir en el nuevo.
--
-- `toca_parcela` (a nivel de contrato) se queda intacta para lo que ya hacía
-- bien: soltar unidades que dejaron de estar en `cods` (bloque de arriba) y
-- la salida temprana del legado "sin código" (rama vacía). Solo el guardarraíl
-- de LAW-73 pasa a mirar el código, no el contrato entero.
--
-- IDEMPOTENTE: `create or replace function`. No toca datos.
-- ════════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: sincroniza_unidad_contrato
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
