-- ════════════════════════════════════════════════════════════════════════════
-- LIBERACIÓN DE RESERVAS — 21-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Una Carta de Reserva (CR/CA/CH/CP) trae un plazo contractual
-- (datos.fields.fecha_pago_reserva + validez_dias, legado validez_meses). Si
-- vence sin que exista detrás un Bloqueo de Parcela (RP, tipo='reserva_parcela')
-- la parcela se libera sola. Si el comprador desiste antes, el equipo la libera
-- a mano. En NINGÚN caso se borra o edita el contrato — la cuota de reserva es
-- no reembolsable y el recibí ya emitido no se toca. Pasó por revisión previa
-- con Datos+Seguridad+Administración; las dos decisiones ambiguas (blindaje de
-- columnas por trigger, y qué rol puede liberar por desistimiento) ya las
-- resolvió el owner y van aplicadas tal cual abajo.
--
-- Verificado contra la base real antes de escribir esto (21-sep-2026):
--   · contrato_tipo_etapa.etapa='reserva' menos 'reserva_parcela' da
--     exactamente {carta_reserva, carta_reserva_ampliada,
--     carta_reserva_hak_sewa, carta_reserva_pma} — el catálogo no se escribe
--     a mano, sale de esa tabla (punto 5 del encargo).
--   · sincroniza_unidad_contrato() es AFTER INSERT OR UPDATE (sin "OF"): CUALQUIER
--     UPDATE de contratos la dispara, incluida la que hace esta función —
--     de ahí el guard obligatorio al principio.
--   · el UPDATE de esta función solo toca liberado_en/liberado_motivo, así que
--     los triggers "BEFORE UPDATE OF <columna>" de contratos (datos, poder_id,
--     unidad_id, proyecto_id/nombre, bloqueado) no se disparan; los que sí son
--     incondicionales (contrato_no_editable_en_firma, carta_cobrado_congelado_
--     en_update, contrato_sociedad_existe, contrato_evento_log,
--     registra_edicion_privilegiada) se comprobaron uno a uno y ninguno bloquea
--     ni duplica el evento (contrato_no_editable_en_firma sale en su primera
--     línea si datos no cambió).
--   · avisos-manager y _avisar_managers ya existen (18/19-sep): el aviso de
--     "vence mañana" reusa ese canal, no se inventa uno nuevo.
--
-- Migraciones reales aplicadas (repo: supabase/migrations/):
--   20260921060542_libera_reservas_vencidas.sql
--   20260921060625_libera_reservas_vencidas_revoke_public_trigger.sql
-- Este fichero es la copia legible de las dos, en un solo sitio.
-- ════════════════════════════════════════════════════════════════════════════


-- ── 1. Columnas nuevas ───────────────────────────────────────────────────────

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: _protege_liberado_contrato, avanza_unidad_por_cobro, cron_libera_reservas_secret, libera_reserva, sincroniza_unidad_contrato, trg_protege_liberado_contrato
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260812043919_avanza_unidad_por_cobro_fix_forward.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260824035201_construccion_por_parcela.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260922125208_prorroga_reserva_art3_escrow.sql  (reserva_vence_el, reservas_vencimiento, prorroga_reserva - la edge ya no calcula el vencimiento en TypeScript)
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260916040622_avanza_unidad_por_cobro_exige_suelo_100.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921060625_libera_reservas_vencidas_revoke_public_trigger.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
--   supabase/migrations/20260922011152_law259_libera_reserva_todas_las_unidades.sql
-- ============================================================================
