-- destructivo-ok: DROP+CREATE POLICY son reescrituras completas de la misma
-- policy (patron ya usado en permisos_por_proyecto.sql), sustituidas en la
-- misma sentencia, nunca retiradas sin reemplazo. CREATE OR REPLACE FUNCTION
-- es sustitucion. Cero DELETE/TRUNCATE/RLS off.
-- ════════════════════════════════════════════════════════════════════════════
-- sales_manager/project_manager PUEDEN CREAR Y EDITAR (no solo leer) — 11-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Corrección directa del owner sobre lo construido ayer: "un sales manager es
-- el encargado del proyecto — si un agente se equivoca al hacer algo en su
-- contrato necesito que el manager pueda rectificar sin tener que acudir a un
-- administrador". Revisión previa de Seguridad (11-sep) antes de escribir esto,
-- 5 hallazgos + 1 nota, todos plegados aquí:
--
--   1. `bloqueado=false` NO equivale a "sin firmar" — verificado en vivo: 2
--      contratos reales tienen firma ya `estado='firmado'` en `contrato_firmas`
--      con `bloqueado` todavía en `false`. La policy vieja solo miraba
--      `bloqueado`; se añade `contrato_firma_viva()` (mira `contrato_firmas`
--      de verdad, mismo criterio que ya usa el trigger
--      `contrato_no_editable_en_firma`) — y se aplica a TODOS los editores,
--      no solo al manager: el mismo agujero ya existía para el propio agente.
--   2. Los 7 usuarios sales_manager/project_manager de hoy ya tienen entre 2 y
--      29 proyectos en su array (probablemente de un "Marcar todos" desde
--      /usuarios/, antes de que la asignación se limitara a la ficha de cada
--      proyecto en la corrección anterior de hoy). Esto NO se poda aquí — es
--      dato del owner, no algo que un backend deba decidir en su nombre — pero
--      queda anotado en pendientes.md para que se revise antes de dar por
--      buena la asignación de escritura tan ancha que ya implica.
--   3. `facturas.proyecto_nombre` no se resincronizaba igual que en
--      `contratos` (solo si venía vacío) — se iguala aquí: `trg_espejo_proyecto`
--      ahora sobreescribe SIEMPRE en las dos tablas, mismo criterio, una sola
--      función. Antes de esto solo `contratos` lo hacía incondicionalmente.
--   4. Sin rastro de "un manager corrigió a un agente" — `contrato_evento_log`
--      ya registraba QUIÉN edita (`v_quien`) en cada evento 'editado', pero no
--      si ese quien era el propio autor. Se añade `autor_distinto` al detalle
--      del evento cuando `v_quien` no coincide con `creado_por` — cubre tanto
--      manager-corrige-agente como super_admin-corrige-agente, sin evento
--      nuevo en el CHECK cerrado (menos superficie que tocar).
--   5. `es_suyo(NULL) = TRUE` ya expone 10 contratos y 8 facturas reales a
--      escritura de CUALQUIER agente activo — pero es una decisión YA TOMADA
--      y documentada el 27-jul-2026 (contracts/sql/usuarios_y_permisos.sql):
--      bloquearlas dejaría esos contratos vivos intocables. NO se revierte
--      aquí sin hablarlo con el owner — queda anotado en pendientes.md como
--      una decisión a reconfirmar ahora que también hay managers de por medio,
--      no como un bug que esta tarea deba arreglar por su cuenta.
--   Nota aparte: `recibi_aplicaciones` INSERT ya no comprobaba propiedad en la
--      factura DESTINO (solo en el recibí) — comportamiento previo, no se
--      amplía esa asimetría aquí; solo se añade la rama de manager al lado
--      del recibí, igual que ya hacía `es_suyo`.

-- ── 1. Firma viva de verdad, no solo `bloqueado` ────────────────────────────

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: agentes, contrato_evento_log, contrato_firma_viva, el, son, trg_espejo_proyecto
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090740_rls_propiedad_contratos_facturas.sql
--   supabase/migrations/20260729094754_equipo_se_ve_entre_si.sql
--   supabase/migrations/20260730044257_storage_update_snapshots_pendientes.sql
--   supabase/migrations/20260731043211_documentacion_bucket_e_indice.sql
--   supabase/migrations/20260731043542_aviso_almacenamiento_cron.sql
--   supabase/migrations/20260805023613_portal_comprador.sql
--   supabase/migrations/20260807021850_unidades_catalogos_proyecto_tipo.sql
--   supabase/migrations/20260807024457_unidades_catalogos_policies_to_authenticated.sql
--   supabase/migrations/20260807043910_contratos_facturas_visibilidad_por_agente.sql
--   supabase/migrations/20260811034823_recibi_aplicaciones_reforma_facturacion.sql
--   supabase/migrations/20260811034859_bucket_justificantes.sql
--   supabase/migrations/20260811035518_recibi_aplicaciones_delete_propio.sql
--   supabase/migrations/20260817131756_storage_borrar_solo_snapshots_pendientes.sql
--   supabase/migrations/20260819044926_law71_editar_firmado_y_borrar_facturas.sql
--   supabase/migrations/20260819145810_proyecto_por_enlace.sql
--   supabase/migrations/20260821152750_law71_super_admin_reasigna_autor_de_factura_anulada.sql
--   supabase/migrations/20260821153038_policies_de_law71_a_authenticated_no_a_public.sql
--   supabase/migrations/20260901021433_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260901120000_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260910091817_avisos_manager_email.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260911013643_proyectos_supervisados_separado.sql
--   supabase/migrations/20260911031517_equipo_deja_de_saltarse_la_rls.sql
--   supabase/migrations/20260911033802_proyectos_solo_los_asignados.sql
--   supabase/migrations/20260911035515_solo_admin_da_de_alta_proyectos.sql
--   supabase/migrations/20260914024847_directorio_de_compradores_y_el_autor_corrige_lo_suyo.sql
--   supabase/migrations/20260914090558_comisiones_equipos_venta.sql
--   supabase/migrations/20260914093532_comisiones_devengadas_manager_no_veia_al_closer.sql
--   supabase/migrations/20260914_directorio_de_compradores_y_el_autor_corrige_lo_suyo.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
--   supabase/migrations/20260918021400_storage_deja_de_ser_una_carpeta_compartida.sql
--   supabase/migrations/20260922133000_facturas_congela_contrato_numero_security_invoker.sql
-- ============================================================================
