-- ============================================================================
-- Catálogo de modelos de villa por proyecto — 31-jul-2026
-- ----------------------------------------------------------------------------
-- Petición del cliente: en Palm Field se puede construir CUALQUIERA de las dos
-- viviendas (Dream o Dune) en CUALQUIER parcela. Hasta ahora el modelo venía
-- pegado a la parcela porque así llegó la tabla de precios, y eso convertía una
-- decisión comercial —qué casa quiere el comprador— en un dato del inventario.
--
-- Lo que de verdad es de la PARCELA: su superficie y su precio de suelo
-- (125 €/m² en Palm Field, verificado sobre las 32).
-- Lo que es del MODELO: lo que cuesta construirlo (Dune 64.000, Dream 94.000).
-- El total es la suma, y cambia si el comprador cambia de casa.
--
-- El catálogo va en su tabla y no derivado de `unidades` porque, si un día todas
-- las parcelas quedaran asignadas a Dream, el precio de Dune desaparecería del
-- sistema sin que nadie lo hubiera dado de baja.
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: modelos, modelos_villa
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731071759_modelos_villa.sql
--   supabase/migrations/20260907053801_catalogo_de_modelos.sql
--   supabase/migrations/20260907060211_catalogo_modelos_alcance_de_obra.sql
--   supabase/migrations/20260911033911_catalogo_por_proyecto_tambien_se_filtra.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
-- ============================================================================
