-- Los catalogos con NIK y pasaporte en claro dejan de verlos los COMPRADORES.
--
-- Hallazgo de Seguridad en la consulta de deploy del 17-sep-2026. La deuda que
-- se cerro el 12-ago se cerro contra `anon`, no contra clientes con sesion: los
-- compradores del portal entran con signInWithPassword al MISMO proyecto de
-- Supabase, asi que son `authenticated` y las dos policies decian `using (true)`.
-- Medido: 58 cuentas en auth.users y solo 30 con ficha en public.usuarios; los
-- otros 28 son compradores. Ningun camino del portal lee estas dos tablas.
--
-- `es_agente()` es la barrera correcta: exige fila activa en public.usuarios, y
-- para quien no la tiene mira el claim `agente` del JWT, que un comprador no
-- lleva. ALTER POLICY y no DROP+CREATE, para no tirar nada.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: (fichero de ALTER/INSERT, sin CREATE)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917093525_nik_solo_equipo_no_compradores.sql
-- ============================================================================
