-- destructivo-ok: los únicos `drop` son `drop policy/trigger if exists` de
-- objetos que este mismo fichero vuelve a crear tres líneas más abajo, para
-- poder reejecutarlo entero sin que falle. No borra ninguna tabla, ninguna
-- columna y ningún dato. El único UPDATE masivo es el de la siembra
-- (`notif_visto_hasta` donde es nulo), que rellena una columna recién creada.
-- ============================================================================
-- Notificaciones de la intranet — 4-ago-2026
-- ----------------------------------------------------------------------------
-- PETICIÓN DEL OWNER: «a los administradores deben salirle notificaciones de
-- todo lo que pasa pero a cada operador lo suyo. Si han firmado un contrato de
-- un agente, que le salga que ya está firmado». Y la duda: «¿es un servicio que
-- escucha siempre?».
--
-- NO HACE FALTA NINGÚN SERVICIO. Un contrato no se firma solo: alguien escribe
-- en `contratos`. El disparador corre DENTRO de esa misma escritura y deja el
-- aviso apuntado. Cuando el operador abre cualquier herramienta, la campana lee
-- lo suyo. Con la intranet cerrada no hay nada consumiendo.
--
-- DOS TIPOS DE AVISO, Y SOLO UNO SE GUARDA:
--   · HECHOS — «este contrato quedó firmado». Ocurrió en un instante y no vuelve
--     a ocurrir. Se guardan aquí.
--   · VENCIMIENTOS — «esta factura vence en 5 días». No es que haya pasado algo,
--     es que LLEVA pasando, y será mentira dentro de una semana. Se calculan al
--     leer (topbar.js), con la misma consulta que ya usa Vencimientos en
--     Operaciones. Guardarlos obligaría a un proceso diario que los repasara y
--     los borrara: justo el servicio encendido que se quería evitar.
--
-- REPARTO: `destinatario` es el email de `creado_por` del documento — el MISMO
-- campo con el que la RLS decide hoy quién puede editar qué. Un segundo criterio
-- acabaría desalineado del primero. `destinatario` nulo (los 13 contratos
-- anteriores a que existiera la columna) = solo lo ven los administradores, que
-- es donde debe ir: inventar un destinatario es peor que no mandarlo.
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: anotar_aviso, cada, marcar_notificaciones_leidas, notificaciones, notificaciones_para_idx, notificaciones_recientes_idx, trg_avisa_contrato_firmado, trg_avisa_factura, trg_avisa_firma_enviada, trg_avisa_unidad, trg_aviso_contrato_firmado, trg_aviso_factura, trg_aviso_firma_enviada, trg_aviso_unidad
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090612_usuarios_funciones_permisos.sql
--   supabase/migrations/20260804050406_notificaciones_intranet.sql
--   supabase/migrations/20260804050853_notificaciones_cerrar_anotar_aviso.sql
--   supabase/migrations/20260812042537_aviso_unidad_bloqueada_cobrada.sql
--   supabase/migrations/20260909085614_notificaciones_nulo_solo_admins.sql
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260910091817_avisos_manager_email.sql
-- ============================================================================
