-- ════════════════════════════════════════════════════════════════════════════
-- UN CONTRATO, VARIAS PARCELAS — 18-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Encargo del owner (no del cliente): un comprador puede querer MÁS DE UNA
-- parcela en el mismo Bloqueo o la misma Carta de Reserva. El dato sigue siendo
-- `datos->fields->>parcela_codigo`, ahora admitiendo una LISTA separada por
-- comas («A4, A5, C7»): así las plantillas la imprimen tal cual, los listados
-- la enseñan tal cual, y un contrato viejo con un solo código es el caso
-- particular de una lista de uno — cero migración.
--
-- La relación de la base YA era N:1 (unidades.contrato_id apunta al contrato):
-- lo que asumía «una» era el TRIGGER. Esta es su reescritura, con las reglas de
-- siempre aplicadas POR PARCELA — y dos arreglos de minas que la multi-parcela
-- habría pisado en `avanza_unidad_por_cobro` (abajo, con su porqué).
--
-- Reglas conservadas del original, una a una (LAW-51: al tocar este trigger se
-- relee TODO consumidor):
--   · parcela ocupada por OTRO comprador → excepción nombrando el contrato;
--   · traspaso Carta→Bloqueo del MISMO comprador (pasaporte o email, los mismos
--     identificadores que crean la ficha) → la parcela pasa y la Carta se
--     cuelga del Bloqueo — ahora por parcela: un Bloqueo puede recoger A4 de
--     una Carta y A5 de otra, y cada Carta se re-cuelga;
--   · la Carta que PERDIÓ su parcela sigue editable: si al guardarla su código
--     está en manos del Bloqueo del mismo comprador, ese código SE SALTA en vez
--     de reventar (el early-exit del original, llevado al bucle);
--   · la escalera de estados de la unidad no cambia ni una regla.
-- Y una mejora de paso: al editar la lista solo se LIBERAN las parcelas que
-- salen — el original soltaba todas y reasignaba, y ese suelta-y-recoge pasaba
-- por 'disponible' un instante sin necesidad.
-- ════════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: avanza_unidad_por_cobro, sincroniza_unidad_contrato
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260812043919_avanza_unidad_por_cobro_fix_forward.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260824035201_construccion_por_parcela.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260916040622_avanza_unidad_por_cobro_exige_suelo_100.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
