-- ⚠️ `es_manager_de()` definida aquí abajo compara contra `u.proyectos` — eso
-- quedó CORREGIDO al día siguiente en proyectos_supervisados_separado.sql
-- (11-sep-2026): el owner señaló que "en qué proyectos puede crear contratos"
-- y "de qué proyecto es encargado un manager" son DOS cosas distintas, así
-- que `es_manager_de()` de verdad, en producción, compara contra la columna
-- nueva `u.proyectos_supervisados`. Lo que sigue vigente de este fichero es
-- todo lo demás (roles nuevos, `clients.propietario`, políticas de agente).
-- ════════════════════════════════════════════════════════════════════════════
-- AGENTE VE SOLO LO SUYO + ROLES sales_manager / project_manager — 10-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Encargo del owner. Revisión previa: Seguridad + Datos + Legal sobre el plan
-- (CEO/flujos/revision_previa.md), 15 hallazgos plegados aquí antes de escribir
-- una línea. Verificado contra la base REAL antes de diseñar (el repo estuvo 33
-- migraciones desincronizado hasta el 9-sep — no basta con leer el .sql viejo):
--   - contratos/facturas YA estaban bien scoped en lectura (es_agente() AND
--     es_suyo(creado_por)); NO existía ninguna política "el equipo se ve entre
--     sí" ahí — esa solo vive en `usuarios`. Solo hacía falta AÑADIR la rama de
--     manager, no tocar nada de lo que ya funcionaba.
--   - `clients` y `unidades` SÍ eran de lectura abierta a cualquier agente
--     (`es_agente()` a secas) — ahí es donde de verdad se cierra algo.
--
-- LAS DECISIONES QUE HAY QUE CONOCER ANTES DE TOCAR ESTO:
--
--   1. `puede_proyecto()` es fail-open a propósito (pensado para no bloquear
--      una ESCRITURA por un dato mal etiquetado) y compara por NOMBRE. Para
--      LECTURA eso es lo contrario de lo que se pide: una fila con proyecto
--      huérfano o mal escrito quedaría visible a todo el equipo, en silencio.
--      Por eso `es_manager_de()` de abajo es una función NUEVA, fail-CLOSED,
--      y compara por `proyecto_id` (uuid, ya indexado), nunca por nombre — un
--      proyecto renombrado no le afecta.
--   2. `es_suyo(autor)` devuelve TRUE cuando `autor` es NULL — correcto para
--      contratos/facturas (documento sin autor = de todos, decisión del
--      27-jul) pero JAMÁS se reutiliza tal cual para una fila nueva: para
--      `clients.propietario` el default es el CONTRARIO (sin propietario
--      reconstruible → NO visible a un agente, solo admin/manager), porque
--      esto es KYC (pasaporte, nacionalidad, domicilio) y el mismo patrón ya
--      mordió una vez con `notificaciones` (`es_suyo(null)=TRUE` enseñó avisos
--      solo-admin a todo el equipo del 4-ago al 9-sep).
--   3. `es_agente()` devuelve TRUE para CUALQUIER usuario activo, mire o no su
--      rol — así que un `sales_manager`/`project_manager` también la pasa.
--      Cada policy tocada añade su propia rama `es_manager_de(...)` explícita;
--      no se asume que el rol nuevo hereda nada de las funciones existentes.
--   4. Los roles nuevos son SOLO LECTURA. No se les da INSERT/UPDATE/DELETE en
--      ninguna tabla — el encargo pide que "reciban información" y "tengan
--      acceso a toda la información", nunca que editen. Si algún día hace
--      falta que editen, es una decisión aparte, no una consecuencia de esto.
--   5. La asignación de QUÉ proyectos ve cada manager reutiliza `usuarios.
--      proyectos` (uuid[], ya existe desde el 18-ago) — el owner sigue
--      asignándolo a mano, persona por persona, como ya hace con los agentes.
--      No hay tabla nueva de asignación ni regla automática por rol.

-- ── 1. Los dos roles nuevos ──────────────────────────────────────────────────
-- destructivo-ok: DROP+ADD CONSTRAINT solo amplía el CHECK de rol (5 valores en
-- vez de 3), no borra filas ni relaja nada de lo que ya había. Mismo patrón que
-- toda reescritura de policy de este fichero: se sustituye, no se retira.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: agentes, cada, cliente_visible, clients_propietario_idx, es_gestor, es_manager_de, solicitudes, unidad_visible
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090612_usuarios_funciones_permisos.sql
--   supabase/migrations/20260729090740_rls_propiedad_contratos_facturas.sql
--   supabase/migrations/20260730044257_storage_update_snapshots_pendientes.sql
--   supabase/migrations/20260731043211_documentacion_bucket_e_indice.sql
--   supabase/migrations/20260731043542_aviso_almacenamiento_cron.sql
--   supabase/migrations/20260804050406_notificaciones_intranet.sql
--   supabase/migrations/20260805023613_portal_comprador.sql
--   supabase/migrations/20260807021850_unidades_catalogos_proyecto_tipo.sql
--   supabase/migrations/20260807024457_unidades_catalogos_policies_to_authenticated.sql
--   supabase/migrations/20260807043910_contratos_facturas_visibilidad_por_agente.sql
--   supabase/migrations/20260811034823_recibi_aplicaciones_reforma_facturacion.sql
--   supabase/migrations/20260811034859_bucket_justificantes.sql
--   supabase/migrations/20260811035518_recibi_aplicaciones_delete_propio.sql
--   supabase/migrations/20260817131756_storage_borrar_solo_snapshots_pendientes.sql
--   supabase/migrations/20260901021433_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260901120000_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260909071823_solicitudes_pago.sql
--   supabase/migrations/20260909073555_solicitudes_pago_pagos_a_agentes.sql
--   supabase/migrations/20260909085614_notificaciones_nulo_solo_admins.sql
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260911013643_proyectos_supervisados_separado.sql
--   supabase/migrations/20260911031517_equipo_deja_de_saltarse_la_rls.sql
--   supabase/migrations/20260911033802_proyectos_solo_los_asignados.sql
--   supabase/migrations/20260911035515_solo_admin_da_de_alta_proyectos.sql
--   supabase/migrations/20260911055035_dar_de_alta_un_comprador_vuelve_a_funcionar.sql
--   supabase/migrations/20260911134947_dar_de_alta_un_comprador_vuelve_a_funcionar.sql
--   supabase/migrations/20260914094813_solicitudes_pago_beneficiario_email_y_origen.sql
--   supabase/migrations/20260914150000_solicitudes_pago_beneficiario_email_y_origen.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
--   supabase/migrations/20260918021400_storage_deja_de_ser_una_carpeta_compartida.sql
--   supabase/migrations/20260922133000_facturas_congela_contrato_numero_security_invoker.sql
-- ============================================================================
