-- ════════════════════════════════════════════════════════════════════════════
-- PERMISOS POR PROYECTO — 18-ago-2026, encargo del owner
-- ════════════════════════════════════════════════════════════════════════════
-- Hasta hoy el permiso tenía UNA sola dimensión: qué HERRAMIENTAS ve cada uno
-- (`usuarios.herramientas` + `puede()`). Eso reparte el acceso a Contratos,
-- Facturas, Obra… pero dentro de Contratos todo el mundo podía crear en
-- cualquiera de los 29 proyectos, vendiera el que vendiera. Esta es la segunda
-- dimensión: SOBRE QUÉ PROYECTOS puede trabajar cada agente.
--
-- LAS TRES DECISIONES DEL OWNER (18-ago), para que nadie las reabra a ciegas:
--   1. Alcance: se filtra donde se trabaja (el selector de proyecto y, con él,
--      el inventario de parcelas) Y se frena en la BASE al crear/editar. Los
--      paneles de dirección (Operaciones, Vencimientos) NO se filtran: ya están
--      limitados por herramienta y filtrar sus totales es otra obra.
--   2. A quién: solo al rol `agente`. `admin` y `super_admin` siguen sin límite
--      — es el corte que ya existe en todo el sistema (`es_admin()`).
--   3. Por defecto: sin proyectos asignados NO se crea nada. Para que nadie
--      pierda acceso hoy, la migración de abajo asigna TODOS los proyectos
--      activos a los agentes que ya existen; a partir de ahí se quita lo que
--      sobre. Un permiso se concede, no se hereda.
--
-- POR QUÉ SE GUARDAN IDs Y NO NOMBRES. `usuarios.proyectos` es `uuid[]` contra
-- `proyectos.id`. Guardar el nombre habría creado otra lista a mano que
-- `renombrar_proyecto()` tendría que ir a actualizar — que es exactamente el
-- fallo abierto en LAW-36. Con el id, renombrar un proyecto no toca ni un
-- permiso.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: agentes, borrar, el, puede_proyecto, puede_proyecto_de
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090740_rls_propiedad_contratos_facturas.sql
--   supabase/migrations/20260729094754_equipo_se_ve_entre_si.sql
--   supabase/migrations/20260730044257_storage_update_snapshots_pendientes.sql
--   supabase/migrations/20260731043211_documentacion_bucket_e_indice.sql
--   supabase/migrations/20260731043542_aviso_almacenamiento_cron.sql
--   supabase/migrations/20260731045054_borrado_con_permisos_y_enlaces.sql
--   supabase/migrations/20260805023613_portal_comprador.sql
--   supabase/migrations/20260807021850_unidades_catalogos_proyecto_tipo.sql
--   supabase/migrations/20260807024457_unidades_catalogos_policies_to_authenticated.sql
--   supabase/migrations/20260807043910_contratos_facturas_visibilidad_por_agente.sql
--   supabase/migrations/20260811034823_recibi_aplicaciones_reforma_facturacion.sql
--   supabase/migrations/20260811034859_bucket_justificantes.sql
--   supabase/migrations/20260811035518_recibi_aplicaciones_delete_propio.sql
--   supabase/migrations/20260817131756_storage_borrar_solo_snapshots_pendientes.sql
--   supabase/migrations/20260819044926_law71_editar_firmado_y_borrar_facturas.sql
--   supabase/migrations/20260821152750_law71_super_admin_reasigna_autor_de_factura_anulada.sql
--   supabase/migrations/20260821153038_policies_de_law71_a_authenticated_no_a_public.sql
--   supabase/migrations/20260821153053_policy_borrar_facturas_a_authenticated.sql
--   supabase/migrations/20260901021433_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260901120000_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260911031517_equipo_deja_de_saltarse_la_rls.sql
--   supabase/migrations/20260911033802_proyectos_solo_los_asignados.sql
--   supabase/migrations/20260911034604_puede_proyecto_cuenta_tambien_lo_que_supervisas.sql
--   supabase/migrations/20260911035515_solo_admin_da_de_alta_proyectos.sql
--   supabase/migrations/20260914024847_directorio_de_compradores_y_el_autor_corrige_lo_suyo.sql
--   supabase/migrations/20260914_directorio_de_compradores_y_el_autor_corrige_lo_suyo.sql
--   supabase/migrations/20260917010415_comision_admin_intranet.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
--   supabase/migrations/20260918021400_storage_deja_de_ser_una_carpeta_compartida.sql
--   supabase/migrations/20260921125405_law_facturas_enviada_no_se_borra.sql
--   supabase/migrations/20260922133000_facturas_congela_contrato_numero_security_invoker.sql
-- ============================================================================
