-- ════════════════════════════════════════════════════════════════════════════
-- VENCIMIENTOS PASA A TENER PERMISO PROPIO — 18-ago-2026 (2ª vuelta)
-- ════════════════════════════════════════════════════════════════════════════
-- El owner: «hay una nueva herramienta y no sale en la lista». Tenía razón, y la
-- causa está escrita en el propio catálogo: Vencimientos nació compartiendo la
-- clave `operaciones` porque una clave NUEVA hay que darla de alta en la edge
-- `admin-usuarios` y redesplegarla, y aquel día la edge estaba bloqueada. Al no
-- tener clave propia, no había nada que listar en el panel de permisos.
-- La edge se desplegó esa misma noche, así que el motivo ya no existe.
--
-- LO QUE HAY QUE MIGRAR, y por qué no es opcional: 10 de los 18 usuarios activos
-- tienen `operaciones` y NINGUNO tiene `vencimientos`. Crear la clave sin más
-- les quitaría de golpe una herramienta que ya usaban — y eso no sería una
-- decisión, sería una regresión metida por la puerta de atrás. Se les concede.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: vencimientos_update
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917143637_obra_confirmar_avance_tope_dias_y_reparto_real.sql
-- ============================================================================
