-- ════════════════════════════════════════════════════════════════════════════
-- LOS ADMIN TAMBIÉN SE LIMITAN POR HERRAMIENTA — 18-ago-2026, encargo del owner
-- ════════════════════════════════════════════════════════════════════════════
-- «Son gente del equipo interno pero no todos deben tener acceso a todo.»
--
-- Hasta hoy `puede(herramienta)` devolvía true para cualquier `admin`: la lista
-- de `usuarios.herramientas` existía para ellos —y estaba rellenada, entre 1 y
-- 10 herramientas cada uno— pero NO GOBERNABA NADA. Ocho de los dieciocho
-- usuarios eran admin, así que en la práctica el reparto por herramienta solo
-- se aplicaba a la mitad del equipo.
--
-- Ahora el único sin límite es `super_admin` (hay exactamente uno). Un admin
-- pasa por su lista igual que un agente.
--
-- LAS DOS DECISIONES DEL OWNER (18-ago):
--   1. Aterrizaje DIRECTO: se activa con lo que cada admin tiene marcado hoy,
--      sin rellenar nada antes. Se le enseñó el impacto exacto y lo aceptó —
--      p.ej. admin@lawangproperties.com se queda solo con Contratos.
--   2. La gestión de usuarios se limita TAMBIÉN en la base, no solo en el menú:
--      es el permiso más delicado que hay (quien lo tiene puede concederse
--      cualquier otro), así que esconder la pantalla no bastaba.
--
-- LO QUE ESTE CAMBIO NO TOCA, a propósito:
--   · `es_admin()` sigue significando lo mismo en `es_suyo()`: un admin sigue
--     viendo y editando documentos de otros. Eso es autoría, no herramientas.
--   · `puede_proyecto()` sigue exento para admin: el límite por proyecto es
--     solo para agentes (decisión del 18-ago, permisos_por_proyecto.sql).
--   · LEER no cambia para nadie. Verificado antes de aplicar: las 16 policies
--     que usan `puede()` son de escritura; ninguna de SELECT. La única lectura
--     afectada es la de las fotos de obra, cuya policy es FOR ALL — y a quien
--     no tenga «Obra» tampoco se le abre la herramienta, así que es coherente.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: admin, puede, solo
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090521_usuarios_y_permisos_tabla.sql
--   supabase/migrations/20260729090612_usuarios_funciones_permisos.sql
--   supabase/migrations/20260729091818_revocar_execute_anon_funciones_permisos.sql
--   supabase/migrations/20260729091848_execute_solo_authenticated_funciones_permisos.sql
--   supabase/migrations/20260807021850_unidades_catalogos_proyecto_tipo.sql
--   supabase/migrations/20260807024457_unidades_catalogos_policies_to_authenticated.sql
--   supabase/migrations/20260811034823_recibi_aplicaciones_reforma_facturacion.sql
--   supabase/migrations/20260811053843_usuarios_admin_no_toca_super_admin.sql
--   supabase/migrations/20260909135217_crm_leads_tablas_y_policies.sql
--   supabase/migrations/20260909135711_crm_leads_firmado_es_bloqueado_y_puede_sin_rama_ciega.sql
--   supabase/migrations/20260914121500_comisiones_devengadas_manager_no_veia_al_closer.sql
--   supabase/migrations/20260916093309_unidades_codigo_orden_natural.sql
--   supabase/migrations/20260917092917_congela_emisor_tambien_en_update.sql
--   supabase/migrations/20260917150021_proyecto_cambiar_estado_y_plazos_funciones.sql
--   supabase/migrations/20260921111614_contrato_closer_semilla_al_alta.sql
-- ============================================================================
