-- ═══════════════════════════════════════════════════════════════════════════
--  poder_id — bajo qué Poder Notarial actúa el apoderado del comprador
--  17-ago-2026 · APLICADO (migración poder_id_enlace_contrato_a_su_poder_notarial)
--  ---------------------------------------------------------------------------
--  CONTEXTO DE NEGOCIO, que no se deduce del código:
--
--  En un Hak Sewa comparecen DOS apoderados, uno por parte:
--    · el del ARRENDADOR — representa al dueño de la tierra   → campos hsn_apoderado_*
--    · el del ARRENDATARIO — compra en nombre del comprador   → campos adq_apoderado_*
--
--  El Poder Notarial que emite Lawang es SIEMPRE el del comprador: el cliente,
--  desde España, apodera a alguien en Indonesia para comprar por él ante notario.
--  Que los dos nombres sean distintos es lo normal, son los dos lados de la mesa.
--
--  Decisión del cliente (17-ago-2026): UN solo poder vale para todos sus
--  contratos, no hace falta uno por escritura.
--
--  POR QUÉ UNA COLUMNA Y NO `contrato_padre_id`:
--    · la dirección correcta es MUCHOS contratos → UN poder, y `padre` solo
--      admite uno por fila;
--    · `contrato_padre_id` ya sirve para otra jerarquía (Carta de Reserva →
--      Bloqueo de Parcela) y la leen tres sitios que asumen un solo nivel.
--
--  PARA QUÉ SIRVE DE VERDAD: el nombre del apoderado del comprador, su NIK y la
--  fecha del poder se TECLEABAN a mano en cada Hak Sewa, copiando datos que
--  viven en el poder. Copiados a mano, derivan. Con el enlace se leen del origen
--  y los tres campos quedan de solo lectura.
--
--  GUARDAS (probadas con un bloque revertido, sin dejar rastro):
--    1. mismo comprador          → pasa
--    2. apuntar a un no-poder    → bloquea, nombrando el documento y su tipo
--    3. poder de otro comprador  → bloquea (compara pasaporte/email, nunca el
--       nombre: una tilde de más daría un bloqueo falso — criterio de LAW-51)
--    4. apuntarse a sí mismo     → bloquea
-- ═══════════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contratos_poder_id_idx
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260817015522_poder_id_enlace_contrato_a_su_poder_notarial.sql
-- ============================================================================
