-- ============================================================================
-- Portal del comprador — 5-ago-2026
-- ----------------------------------------------------------------------------
-- 🔴 7-ago-2026: este fichero se había quedado DESACTUALIZADO frente a lo que
-- de verdad corría en producción — los bloques `documentos` (documentos_proyecto,
-- visible_portal) y `kyc` (documents por client_id) de portal_situacion() se
-- añadieron a mano en el editor SQL de Supabase en algún momento y nunca se
-- volvieron a guardar aquí. Una migración posterior que redefinió la función
-- copiando el cuerpo de ESTE fichero los borró sin que nadie lo pidiera —
-- 60 horas sin documentos ni KYC en el portal de ningún comprador, hasta que
-- un cliente lo notó. Quedan ya incluidos abajo. La lección, no solo para este
-- fichero: antes de `create or replace function` sobre algo que puede haber
-- cambiado fuera de un `apply_migration`, se lee la definición VIVA
-- (`pg_get_functiondef`), nunca se asume que el .sql del repo es la fuente
-- de verdad. Ver [[reference_transformar_y_verificar_no_reescribir]].
-- ----------------------------------------------------------------------------
-- Los compradores de Lawang consultan su situación (contratos, pagos, facturas
-- y avance de obra) en /portal/. Decisiones de diseño que hay que respetar:
--
--   · Un comprador es un usuario de Auth con `app_metadata.portal = true`.
--     NUNCA lleva ficha en `usuarios` ni el flag `agente`: todas las policies
--     internas cuelgan de es_agente()/es_admin(), así que un portal-user no ve
--     NADA del equipo por construcción. Y al revés: es_portal() es la única
--     puerta de lo suyo.
--
--   · El vínculo persona↔acceso NO es "buscar por email en clients": las fichas
--     de familia se crean SIN correo a propósito (UNIQUE(email), ver
--     compradores_desde_contrato.sql). El vínculo es la tabla `portal_accesos`
--     (email → client_id), que rellena el equipo al invitar. Explícito y
--     auditable; una familia con un correo lleva N filas.
--
--   · El portal NO tiene policies de SELECT sobre contratos/facturas: lee TODO
--     por una única RPC `security definer` (portal_situacion) que filtra por el
--     email del JWT y devuelve solo los campos que se pintan. Menos superficie
--     que auditar y ningún blob del jsonb viaja (el 97% de `datos` son firmas y
--     anexos en base64 — nunca select(*)).
--
--   · "Pagado" = MISMO criterio que /intranet/operaciones/ y unidades_estado: suma de
--     facturas no anuladas y no proforma del contrato. El portal no inventa un
--     segundo criterio de cobro; el reparto entre hitos se calcula al pintar.
--
--   · EXECUTE se revoca de PUBLIC y anon NOMBRÁNDOLOS: `revoke from public` a
--     secas no cierra una función de Supabase (aprendido el 4-ago).
-- ============================================================================

-- ── el claim del portal ─────────────────────────────────────────────────────

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: admins, agentes, es_portal, mismo_proyecto, obra, obra_actualizar, obra_fases, obra_fotos, portal, portal_accesos, portal_situacion, portal_ve_foto, portal_ve_pdf
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090740_rls_propiedad_contratos_facturas.sql
--   supabase/migrations/20260730044257_storage_update_snapshots_pendientes.sql
--   supabase/migrations/20260731043211_documentacion_bucket_e_indice.sql
--   supabase/migrations/20260731043542_aviso_almacenamiento_cron.sql
--   supabase/migrations/20260805023613_portal_comprador.sql
--   supabase/migrations/20260805024219_obra_actualizar_rpc.sql
--   supabase/migrations/20260805041649_portal_trazabilidad_acceso.sql
--   supabase/migrations/20260805050656_portal_documentos.sql
--   supabase/migrations/20260807020317_facturas_enviada_y_portal.sql
--   supabase/migrations/20260807021850_unidades_catalogos_proyecto_tipo.sql
--   supabase/migrations/20260807024457_unidades_catalogos_policies_to_authenticated.sql
--   supabase/migrations/20260807043910_contratos_facturas_visibilidad_por_agente.sql
--   supabase/migrations/20260807044931_clients_solo_admin_edita.sql
--   supabase/migrations/20260807053938_portal_situacion_restaura_documentos_kyc.sql
--   supabase/migrations/20260811034823_recibi_aplicaciones_reforma_facturacion.sql
--   supabase/migrations/20260811034859_bucket_justificantes.sql
--   supabase/migrations/20260811035214_portal_situacion_solo_recibi.sql
--   supabase/migrations/20260811035518_recibi_aplicaciones_delete_propio.sql
--   supabase/migrations/20260817131756_storage_borrar_solo_snapshots_pendientes.sql
--   supabase/migrations/20260824062250_portal_factura_nombre_en_vivo.sql
--   supabase/migrations/20260827110851_documents_borrado_por_admin.sql
--   supabase/migrations/20260828043905_obra_fotos_no_cascada_al_borrar_unidad.sql
--   supabase/migrations/20260828051500_obra_fotos_no_cascada_al_borrar_unidad.sql
--   supabase/migrations/20260831085121_portal_situacion_datos_personales.sql
--   supabase/migrations/20260831085533_portal_situacion_soporte_mensajes.sql
--   supabase/migrations/20260831120000_portal_situacion_datos_personales.sql
--   supabase/migrations/20260831122500_portal_situacion_soporte_mensajes.sql
--   supabase/migrations/20260901021433_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260901031353_unificar_soporte_mensajes.sql
--   supabase/migrations/20260901044902_portal_firma_pendiente.sql
--   supabase/migrations/20260901050000_portal_firma_pendiente.sql
--   supabase/migrations/20260901052414_soporte_a_tickets.sql
--   supabase/migrations/20260901053000_soporte_a_tickets.sql
--   supabase/migrations/20260901120000_aviso_soporte_mensajes_equipo.sql
--   supabase/migrations/20260901140000_unificar_soporte_mensajes.sql
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260911031517_equipo_deja_de_saltarse_la_rls.sql
--   supabase/migrations/20260911031743_auditoria_firmas_y_obra_respetan_el_alcance.sql
--   supabase/migrations/20260911033802_proyectos_solo_los_asignados.sql
--   supabase/migrations/20260911035515_solo_admin_da_de_alta_proyectos.sql
--   supabase/migrations/20260914021546_portal_situacion_precio_reserva.sql
--   supabase/migrations/20260914_portal_situacion_precio_reserva.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
--   supabase/migrations/20260918021400_storage_deja_de_ser_una_carpeta_compartida.sql
--   supabase/migrations/20260922133000_facturas_congela_contrato_numero_security_invoker.sql
-- ============================================================================
