-- ============================================================================
-- portal_autoservicio — el acceso al portal deja de concederse a mano
-- ----------------------------------------------------------------------------
-- 8-sep-2026. Hasta hoy, para que un comprador entrara en /portal/ un admin
-- tenía que pulsar «Invitar al portal» en su ficha. El paso se olvidaba y, peor,
-- cuando el correo de invitación no salía (SMTP por defecto de Supabase, ~4/h)
-- el fallo solo vivía en un toast: el 8-sep había 19 accesos concedidos y el
-- único estrenado era la cuenta de pruebas del owner.
--
-- La regla pasa a ser del sistema, no de quien se acuerde:
--   tener ficha de comprador con ese correo + al menos un contrato = acceso.
-- El comprador escribe su correo en /portal/, y si le corresponde se le crea el
-- acceso y se le manda el enlace. Nadie concede nada y no sale ni un correo que
-- el propio cliente no haya pedido.
--
-- Decisiones que hay que respetar al tocar esto:
--
--   · REVOCADO MANDA SOBRE LA REGLA. `portal-invitar` revoca apagando TODAS las
--     filas de ese correo, así que una sola fila con activo=false significa «se
--     le quitó a propósito» y la derivación NO lo resucita. Sin esto, revocar a
--     alguien cuya ficha conserva el correo no serviría de nada.
--
--   · SE EXIGE CONTRATO. 23 de las 128 fichas con correo no tienen ninguno: son
--     interesados, no compradores. Abrirles el portal les enseñaría una pantalla
--     vacía y ampliaría la superficie sin dar nada.
--
--   · EL EQUIPO NO ENTRA POR AQUÍ. Una misma cuenta de Auth no puede ser del
--     equipo y del portal (mismo motivo que el 400 `ese_email_es_del_equipo` de
--     portal-invitar). Y no es un caso raro: el 8-sep hay 8 fichas de comprador
--     con el correo de un compañero — son compañeros que además compran, no
--     datos mal metidos.
--
--   · `portal_accesos` SIGUE SIENDO LA FUENTE ÚNICA de quién ve qué. Esta
--     función solo la SIEMBRA; no se deriva nada al vuelo. Por eso el vínculo
--     manual desde Compradores sigue existiendo y sigue haciendo falta: el 8-sep,
--     5 de los 19 accesos usan un correo distinto al de la ficha (familias, o el
--     comprador que prefiere otro buzón), y eso la regla no lo puede adivinar.
--
--   · La función NO crea la cuenta de Auth ni manda el correo: eso exige
--     service_role y vive en la Edge `portal-acceso`. Aquí solo la decisión.
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: portal_autoservicio
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260908013953_portal_autoservicio.sql
-- ============================================================================
