-- destructivo-ok: `create or replace function`, misma firma y mismos campos
-- del jsonb devuelto — no borra nada, solo cambia de dónde sale un valor.
-- ════════════════════════════════════════════════════════════════════════════
-- EL PORTAL PODÍA ENSEÑAR EL NOMBRE DE OTRO COMPRADOR EN UNA FACTURA — 24-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Hallazgo de hoy (revisión previa de Datos+Seguridad+Legal, no de auditoría
-- mecánica): `portal_situacion()` devolvía el nombre de cada factura leyendo
-- `f.cliente_nombre` — un texto guardado en el momento de crear el documento,
-- que puede quedarse desactualizado (un traspaso, un error al copiar datos).
-- El formulario interno (facturas/index.html) NUNCA tiene este problema porque
-- `traerContrato()` lo recalcula en vivo cada vez que se abre — pero eso solo
-- corrige lo que ve el agente en el formulario, nunca lo que ya está guardado
-- en la base. El comprador, en su portal, nunca pasa por ese formulario: veía
-- directamente el texto guardado, sin la corrección.
--
-- Caso real: REC00046 y PRO00055 (contrato RP00071, David Jimenez Vera / Sara
-- Caballero Palleja) tienen `cliente_nombre` con el nombre de otra pareja.
-- Nadie lo notó desde dentro del estudio porque el formulario lo enseña bien
-- solo. Plegado en el pendiente LAW-75 (mismo incidente, contexto/pendientes.md).
--
-- LA CURA, sin tocar el criterio de "quién es" (LAW-51/`contrato_identificadores`
-- ya fijó que la fuente es el JSONB del contrato, NUNCA `contrato_compradores`/
-- `clients` — esa tabla puede quedar vacía en silencio si el trigger que la
-- rellena atrapa un error, es_agente() la puede editar a mano, y
-- `sincronizar_compradores()` solo da de alta, nunca corrige una ficha ya
-- enlazada): se replica en SQL el mismo criterio que ya usa el formulario
-- (`compradoresDeContrato()` + `nombresFactura()` en contracts/assets/
-- compradores.js) — adq1 → adq2 → adq3 → `datos.compradores[]`, sin repetir
-- a la misma persona. Si el contrato no trae ningún nombre (huérfanas de
-- LAW-38, sin contrato_id), se cae al texto guardado — nunca a un campo en
-- blanco: un documento hacia un tercero real con un hueco es peor que uno
-- con un dato viejo (hallazgo de Seguridad en la revisión previa).
--
-- No toca RLS ni el resto de `portal_situacion()` — SOLO el campo 'cliente' de
-- cada factura. Base: la definición VIVA en producción (`pg_get_functiondef`),
-- que ya difería del repo en 'cobrado' (usa `contrato_cobrado(c.id)`, no la
-- CTE `cobros` que trae `contracts/sql/portal_comprador.sql` — arreglado de
-- paso para no reabrir esa deriva al reemplazar la función entera).

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contrato_nombres_factura, portal_situacion
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260805023613_portal_comprador.sql
--   supabase/migrations/20260805041649_portal_trazabilidad_acceso.sql
--   supabase/migrations/20260805050656_portal_documentos.sql
--   supabase/migrations/20260807020317_facturas_enviada_y_portal.sql
--   supabase/migrations/20260807053938_portal_situacion_restaura_documentos_kyc.sql
--   supabase/migrations/20260811035214_portal_situacion_solo_recibi.sql
--   supabase/migrations/20260824062250_portal_factura_nombre_en_vivo.sql
--   supabase/migrations/20260831085121_portal_situacion_datos_personales.sql
--   supabase/migrations/20260831085533_portal_situacion_soporte_mensajes.sql
--   supabase/migrations/20260831120000_portal_situacion_datos_personales.sql
--   supabase/migrations/20260831122500_portal_situacion_soporte_mensajes.sql
--   supabase/migrations/20260901031353_unificar_soporte_mensajes.sql
--   supabase/migrations/20260901044902_portal_firma_pendiente.sql
--   supabase/migrations/20260901050000_portal_firma_pendiente.sql
--   supabase/migrations/20260901052414_soporte_a_tickets.sql
--   supabase/migrations/20260901053000_soporte_a_tickets.sql
--   supabase/migrations/20260901140000_unificar_soporte_mensajes.sql
--   supabase/migrations/20260914021546_portal_situacion_precio_reserva.sql
--   supabase/migrations/20260914_portal_situacion_precio_reserva.sql
-- ============================================================================
