-- 22-sep-2026 — el precio de Construcción con techo elegido se comprueba en SERVIDOR.
-- Detalle y porqué en contracts/sql/descuento_comercial_construccion_valido.sql.
--
-- QUÉ AÑADE: cuando datos.techo trae precio, precio_total debe ser exactamente
-- techo + Σextras − descuento_comercial (±0,01). Hasta hoy ese candado era solo de
-- pantalla y falló: CC00105/CC00106/CC00107 se guardaron con un precio tecleado a
-- mano (el atributo que enganchaba el readonly no se emitía en contratos nuevos).
-- Solo se comprueba en INSERT o cuando cambia alguno de los cuatro datos que
-- entran en la cuenta — nunca en un UPDATE ajeno (misma lección que el fix del
-- 21-sep: un cinturón incondicional rompía ediciones que no tenían que ver).

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: descuento_comercial_construccion_valido
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260921122811_descuento_comercial_construccion_valido.sql
--   supabase/migrations/20260921124646_descuento_comercial_construccion_valido_fix_precio_total_incondicional.sql
--   supabase/migrations/20260922013705_precio_construccion_cuadra_con_techo.sql
-- ============================================================================
