-- destructivo-ok: ALTER TABLE ADD COLUMN, DROP+CREATE FUNCTION son adiciones y
-- sustituciones. El UPDATE de abajo lleva WHERE (email = ANY de 5 personas
-- concretas, pedido explícito del owner), no es masivo. Cero DELETE/TRUNCATE.
-- ════════════════════════════════════════════════════════════════════════════
-- `proyectos` (crea contratos) y `proyectos_supervisados` (a qué proyecto
-- supervisa un manager) son DOS COSAS DISTINTAS — 11-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Corrección del owner sobre lo construido hoy: había fundido las dos cosas en
-- la misma columna `usuarios.proyectos`, y por eso hice de /usuarios/ un
-- espejo de solo lectura para managers (para no tener "dos sitios editando lo
-- mismo"). Pero NO son lo mismo:
--   · `usuarios.proyectos`              → en qué proyectos puede este usuario
--     CREAR/EDITAR contratos como agente. Se edita en /usuarios/. Vale igual
--     para un agente que para un manager: un manager también puede vender.
--   · `usuarios.proyectos_supervisados` → de qué proyecto es encargado este
--     manager — ve TODO lo que hagan los agentes ahí y puede corregirlo. Se
--     edita en /proyectos/ (ficha de CADA proyecto), nunca en /usuarios/.
-- `es_manager_de()` pasa a mirar la columna nueva: como la usan TODAS las
-- policies de lectura/escritura de managers (clients, unidades, contratos,
-- facturas, recibi_aplicaciones, solicitudes_pago, el aviso por email), este
-- es el único sitio que hay que tocar — ningún otro archivo .sql se reescribe.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: es_manager_de, son, usuario_supervisa_proyecto
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260910090734_permisos_agente_solo_lo_suyo_y_managers.sql
--   supabase/migrations/20260910091817_avisos_manager_email.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260911013643_proyectos_supervisados_separado.sql
--   supabase/migrations/20260914090558_comisiones_equipos_venta.sql
--   supabase/migrations/20260914093532_comisiones_devengadas_manager_no_veia_al_closer.sql
-- ============================================================================
