-- ════════════════════════════════════════════════════════════════════════════
-- EL PROYECTO SE REFERENCIA POR ENLACE, NO POR NOMBRE — 19-ago-2026
-- ════════════════════════════════════════════════════════════════════════════
-- DECISIÓN DEL OWNER: «compradores y proyectos MANDAN sobre el resto de
-- herramientas en cuanto a su información; si añado un proyecto o parcelas,
-- toda la suite que haga referencia a eso debe actualizarse al momento, ni
-- siquiera preguntar».
--
-- CÓMO ESTABA. `unidades` ya lo hacía bien (`proyecto_id`). `contratos` y
-- `facturas` guardaban SOLO el nombre en texto. `renombrar_proyecto()` propaga
-- ese texto a cinco tablas y hasta respeta los documentos congelados — está
-- bien construida— pero propaga **por igualdad de nombre**: cualquier fila cuyo
-- texto no case exactamente queda huérfana para siempre y nada lo dice.
-- Medido el 19-ago: **13 contratos** apuntan a nombres que ya no existen
-- («Mejan Village», «Palm Field by Balian Hills», «Sumba Hills by SandalWoods»…).
--
-- CÓMO QUEDA:
--   · `proyecto_id` es la referencia. El nombre en texto pasa a ser un ESPEJO:
--     si hay id, el texto se escribe desde el id en cada guardado, así que no
--     puede divergir aunque alguien lo teclee.
--   · Renombrar un proyecto se propaga por ID, y **también si alguien edita la
--     tabla `proyectos` a mano**, no solo desde la RPC.
--   · Y lo que NO case por nombre al migrar se queda con `proyecto_id` nulo:
--     ahí el huérfano se VE, que es justo lo que faltaba.
--
-- ⚠️ Congelado sigue mandando sobre el campo IMPRESO. La columna
-- `proyecto_nombre` —la que lee toda la suite— se actualiza siempre; el
-- `datos.fields.proyecto_nombre` de un contrato firmado o una factura enviada
-- NO se toca: ese es el papel que ya tiene alguien en la mano.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contratos_proyecto_idx, facturas_proyecto_idx, proyectos_huerfanos, trg_espejo_proyecto, trg_proyecto_renombrado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260819145810_proyecto_por_enlace.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
-- ============================================================================
