-- ═══════════════════════════════════════════════════════════════════════
-- OPCIONAL, SIN APLICAR — 30-jul-2026
-- Permitir al super_admin reasignar el AUTOR de un documento ya cerrado
-- (contrato bloqueado o factura anulada).
--
-- Por qué no está aplicado: las policies actuales exigen `bloqueado = false`
-- y `anulada = false`, y esa condición es la que hace inmutable un documento
-- firmado. Ampliarla es una decisión del dueño, no una corrección técnica:
-- abre la puerta a modificar filas que hoy no se pueden tocar.
--
-- Lo que SÍ funciona sin esto: reasignar el autor de cualquier contrato no
-- bloqueado y de cualquier factura no anulada. El panel lo dice cuando no
-- puede, en vez de ofrecer un botón que la RLS rechaza.
--
-- Alcance de estas policies: SOLO la columna `creado_por`. Postgres no filtra
-- columnas en una policy, así que la restricción se impone con un trigger que
-- rechaza cualquier update que cambie otra cosa. Sin ese trigger, "reasignar
-- el autor" sería en realidad "editar un contrato firmado", que es lo que
-- estamos protegiendo.
-- ═══════════════════════════════════════════════════════════════════════

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: contratos_bloqueado_solo_autor, el, es_super_admin, facturas_anulada_solo_autor, solo_cambia_autor
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090740_rls_propiedad_contratos_facturas.sql
--   supabase/migrations/20260729094754_equipo_se_ve_entre_si.sql
--   supabase/migrations/20260731045054_borrado_con_permisos_y_enlaces.sql
--   supabase/migrations/20260811053843_usuarios_admin_no_toca_super_admin.sql
--   supabase/migrations/20260819044926_law71_editar_firmado_y_borrar_facturas.sql
--   supabase/migrations/20260821152750_law71_super_admin_reasigna_autor_de_factura_anulada.sql
--   supabase/migrations/20260821153038_policies_de_law71_a_authenticated_no_a_public.sql
--   supabase/migrations/20260911011008_managers_escriben_en_su_proyecto.sql
--   supabase/migrations/20260914024847_directorio_de_compradores_y_el_autor_corrige_lo_suyo.sql
--   supabase/migrations/20260914_directorio_de_compradores_y_el_autor_corrige_lo_suyo.sql
--   supabase/migrations/20260918021123_puede_proyecto_deja_de_abrir_cuando_el_nombre_no_casa.sql
-- ============================================================================
