-- Lawang · contratos — cerrar el agujero de "authenticated = cualquiera"
-- 22-jul-2026
--
-- Problema: las policies eran `to authenticated using (true)` y el registro
-- público de Supabase Auth está ABIERTO (/auth/v1/settings → disable_signup:false).
-- La publishable key está en el HTML de app.html (es pública por diseño), así que
-- cualquiera podía registrarse con su propio email, confirmarlo desde su propio
-- buzón y quedar como `authenticated` → leer TODOS los contratos guardados
-- (pasaporte, domicilio, teléfono de los compradores) y el bucket de PDFs firmados.
--
-- Fix: las policies exigen un flag en app_metadata. app_metadata solo se escribe
-- desde el servidor (service_role / dashboard); user_metadata NO vale porque lo
-- fija el propio usuario en el signUp.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: es_agente
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260729090612_usuarios_funciones_permisos.sql
--   supabase/migrations/20260729091818_revocar_execute_anon_funciones_permisos.sql
--   supabase/migrations/20260729091848_execute_solo_authenticated_funciones_permisos.sql
--   supabase/migrations/20260807024457_unidades_catalogos_policies_to_authenticated.sql
-- ============================================================================
