-- Ya aplicado en producción (28-ago-2026, aviso del owner: "el contrato
-- RP00116 está vinculado a A5, que está fuera de inventario. Necesito
-- quitarla y no puedo. La nueva vinculación debe ser: W3 D5"). Copia de
-- repo-de-registro, no se vuelve a ejecutar.
--
-- El contrato guardaba parcela_codigo = "A5" (texto suelto de antes de
-- LAW-73, 21-ago-2026, cuando la parcela pasó a salir siempre del
-- inventario) pero la relación real (unidades.contrato_id) ya apuntaba
-- correctamente a W3.1 - D5 -- vinculada por otra vía, probablemente desde
-- Proyectos, nunca desde este contrato. El propio contracts/assets/
-- parcela_inventario.js protege a propósito cualquier código "histórico" que
-- no esté en el inventario actual sin botón de quitar (no se puede
-- reescribir texto libre), así que la UI nunca iba a dejar corregir esto
-- sola -- por diseño, no por error.
--
-- Seguro de corregir en sitio: la firma de este contrato quedó ANULADA y
-- nunca `firmado_en` (tabla contrato_firmas, verificado antes de tocar
-- nada) -- no hay ningún documento ya entregado a la compradora que se esté
-- alterando.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: (fichero de ALTER/INSERT, sin CREATE)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
-- ============================================================================
