-- ============================================================================
-- SOCIEDADES EMISORAS — de `contracts/assets/entities.js` a la base
--
-- POR QUE. Hasta hoy la identidad de cada sociedad emisora (razon social, NPWP,
-- domicilio, logo, tinta del documento) vivia en un `const SOCIEDADES` dentro de
-- un fichero del repo que se sirve publico y sin login. Eso rompe la norma de la
-- suite «si el cliente lo puede dar de alta —o cambiar de opinion sobre el— no
-- puede vivir en un fichero» (contexto/suite_lawang.md), y con una segunda
-- empresa dentro de la intranet deja de aguantar: cada alta seria un commit.
--
-- QUE NO HACE ESTA MIGRACION, a proposito:
--   · NO toca ni un numero de documento. El owner decidio el 17-sep-2026 NO
--     separar todavia las series por sociedad (LAW-235): las tres secuencias
--     globales siguen exactamente como estan. Separarlas exige antes que un
--     contable indonesio diga si la normativa obliga a reinicio anual o a un
--     formato concreto de serie para una PT.
--   · NO escribe una sola fila de `facturas`. Esa tabla tiene cinco triggers de
--     fila y dos se tragan los errores (`exception when others then raise
--     warning`), asi que un UPDATE masivo devengaria o dejaria de devengar
--     comision del 0,5% sin que nadie se entere. Los 412 documentos ya emitidos
--     se quedan como historico documentado, decision del owner del 17-sep.
--
-- LA CLAVE NO SE EDITA NUNCA. `clave` va guardada dentro de cada contrato
-- (`datos->'fields'->>'sociedad_firmante'`) y de cada factura (`sociedad`), y
-- las plantillas la miran literalmente en `<!--if:sociedad_firmante=tepi_sungai-->`.
-- Por eso es la primary key y por eso el GRANT de UPDATE la deja fuera: no basta
-- con no ofrecerla en un formulario.
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: _sociedades_autoria, _sociedades_log, sociedades, sociedades_log, trg_sociedades_autoria, trg_sociedades_log
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917082347_sociedades_a_la_base.sql
--   supabase/migrations/20260917083244_sociedades_clave_rechaza_en_vez_de_ajustar.sql
--   supabase/migrations/20260917100751_sociedades_jurisdiccion.sql
--   supabase/migrations/20260917160000_sociedades_a_la_base.sql
--   supabase/migrations/20260917164500_sociedades_clave_rechaza_en_vez_de_ajustar.sql
--   supabase/migrations/20260917190000_sociedades_jurisdiccion.sql
-- ============================================================================
