-- La jurisdiccion deja de deducirse de la clave literal.
--
-- Hallazgo MEDIA de Legal en la consulta de deploy del 17-sep-2026:
-- `contracts/app.html` avisaba de que las nueve plantillas declaran al Promotor
-- «sociedad de nacionalidad Indonesia» comparando la clave contra el literal
-- 'sandal_woods_ltd'. Mientras las sociedades nacian por SQL eso aguantaba;
-- desde que se dan de alta desde /intranet/sociedades/, la cuarta empresa
-- imprimiria esa declaracion falsa sin que nada avisara. Es el mismo patron que
-- `es_escrow` en cuentas_bancarias: lo dice la FILA, no su nombre.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: (fichero de ALTER/INSERT, sin CREATE)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917100751_sociedades_jurisdiccion.sql
-- ============================================================================
