-- La clave de una sociedad: RECHAZAR, no ajustar en silencio.
--
-- La primera version hacia `new.clave := old.clave`, asi que un intento de
-- renombrarla no fallaba: simplemente no pasaba nada, y el log registraba un
-- update sin cambios. El estandar de Seguridad en esta suite es rechazar, nunca
-- ajustar por debajo — un guardado que dice que fue bien y no hizo lo que se le
-- pidio es peor que un error.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: _sociedades_autoria
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917082347_sociedades_a_la_base.sql
--   supabase/migrations/20260917083244_sociedades_clave_rechaza_en_vez_de_ajustar.sql
--   supabase/migrations/20260917160000_sociedades_a_la_base.sql
--   supabase/migrations/20260917164500_sociedades_clave_rechaza_en_vez_de_ajustar.sql
-- ============================================================================
