-- 22-sep-2026 — techo «Ulin» automático para modelos sin variantes de techo.
-- Revisión previa #39 (Legal + Datos). Decisión del owner: "haz un techo
-- estándar automático pero llámalo Ulin".
--
-- POR QUÉ. Desde el 16-sep el precio de Construcción sale de techo+extras y, desde
-- el 22-sep, el servidor lo exige (precio_construccion_cuadra_con_techo.sql). Pero
-- 10 de 15 modelos activos no tienen filas en modelo_techos, así que en sus
-- contratos no había fórmula: precio a mano y sin descuento comercial.
--
-- QUÉ HACE. Solo cuando el modelo NO tiene ninguna variante, la función devuelve
-- una única opción sintética «Ulin» con el precio base de construcción del modelo
-- para ese proyecto (la misma cifra que ya calcula la CTE `base`: modelos_villa
-- si hay precio propio, si no modelos). No se escribe ninguna fila: el precio
-- sigue teniendo un solo dueño. Se reconoce porque techo_id = modelo_id (no
-- existe en modelo_techos): el editor la marca `sintetico` y NO imprime «(por
-- defecto)» — con una sola opción no hubo elección (Legal).
--
-- REGLAS (Datos): precio y moneda de la MISMA fila (coalesce mv.moneda,
-- m.moneda); si el precio base es NULL, CERO filas (nunca una fila con precio
-- NULL: el editor la preseleccionaría y el trigger no tendría nada que
-- comprobar); `not exists` con esquema (search_path vacío); la rama existente
-- entre paréntesis para conservar su `order by`.
--
-- DIVERGENCIA ASUMIDA, no bug: la web pública (modelo/datos.php) sigue
-- ocultando del configurador los modelos sin sirap+bambu; el editor de contratos
-- sí les enseña «Ulin». Son dos consumidores distintos de dos fuentes distintas.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: function modelo_techos_opciones(uuid, uuid)
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260922024034_techo_ulin_sintetico.sql
-- ============================================================================
