-- Traspaso de cliente: arrastra tambien sus contratos, facturas y recibis —
-- 17-sep-2026, encargo del owner.
--
-- CONTEXTO. Desde el 14-sep existe /intranet/compradores/ -> "Traspasar", que
-- cambia SOLO `clients.propietario` y lo dice en el propio aviso: "Los
-- contratos y las facturas NO se mueven: el traspaso es de la ficha, no del
-- trabajo" (supabase/migrations/20260914_directorio_de_compradores_y_el_autor_corrige_lo_suyo.sql,
-- comentario de compradores/index.html linea ~1184). Fue deliberado para el
-- caso "el agente ya puede ABRIR la ficha que dio de alta otro". Lo que pide
-- el owner ahora es distinto: cuando de verdad se traspasa un cliente de un
-- agente a otro, sus contratos, facturas y recibis (misma tabla `facturas`,
-- distinguidos por tipo) tienen que seguirle. LAW-159 ya nombraba el hueco:
-- "probablemente traspasos de cliente entre agentes que no quedaron
-- documentados en ningun otro sitio".
--
-- QUE NO TOCA, a proposito:
--   - `contrato_closer`/`contrato_closer_log` (atribucion de venta/comision):
--     tabla aparte, deliberadamente desacoplada de `creado_por`
--     (20260911020137_crm_atribucion_ventas_y_ranking_closers.sql explica por
--     que `creado_por` NO sirve para medir quien cerro la venta). Un traspaso
--     de gestion no cambia quien cobra la comision.
--   - Contratos `bloqueado = true`: se quedan con su autor. Mismo limite que
--     ya tiene "Reasignar autor" (contracts/assets/autoria.js); ampliarlo es
--     la decision del dueño que describe, sin aplicar,
--     contracts/sql/reasignar_autor_bloqueados.sql.
--   - Facturas `anulada = true`: estas SI se mueven (solo `creado_por`), al
--     reves que los contratos bloqueados: LAW-71
--     (20260821152750_law71_super_admin_reasigna_autor_de_factura_anulada.sql)
--     ya construyo el trigger `factura_anulada_solo_cambia_autor` justo para
--     autorizar esto. Excluirlas aqui seria mas restrictivo que la propia base
--     y dejaria al admin reasignandolas una a una despues (Regla 0 de
--     contexto/suite_lawang.md: "una copia pegada de otra herramienta es
--     deuda").
--
-- QUIEN. `es_super_admin()`, no `es_admin()`. La ficha SOLA (sin cascada)
-- sigue siendo de cualquier admin (RLS de `clients`, sin cambios); arrastrar
-- documentos es la version en bloque de "Reasignar autor", ya restringida a
-- super_admin porque "reatribuir un documento es un acto de administracion de
-- personas, no de documentos" (autoria.js). Mismo criterio, aplicado a muchos
-- documentos de una vez.
--
-- COMO SE ENLAZAN LOS CONTRATOS. Por `contrato_compradores.client_id`, para
-- CUALQUIER rol (adquiriente_1, adquiriente_2...) — no por
-- `facturas.client_id`, que el trigger `factura_hereda_cliente` solo rellena
-- para `adquiriente_1` y dejaria fuera, en silencio, las facturas de un
-- comprador secundario.
--
-- SOLO SE MUEVE LO QUE ERA DEL PROPIETARIO SALIENTE. El filtro exige
-- `creado_por = v_anterior` (comparacion normal, nunca IS NOT DISTINCT FROM:
-- si `v_anterior` es NULL —fichas sin dueño reconstruible, LAW-180— no se
-- adivina nada, y todo lo de esa ficha cae en "sin autor" para que un humano
-- lo revise, nunca en "movido"). Un contrato de este cliente cuya autoria es
-- de un TERCER agente (admin, un compañero que lo redacto) no se reatribuye
-- solo por traspasar al comprador — se cuenta aparte para que el super_admin
-- lo vea y decida a mano con "Reasignar autor" si tambien hay que moverlo.
--
-- POR QUE `set local session_replication_role = replica` alrededor de las dos
-- UPDATE. `trg_sincroniza_unidad` (contratos, contracts/sql/vinculo_contrato_unidad.sql)
-- se creo SIN lista de columnas, asi que cualquier UPDATE lo dispara aunque
-- solo cambie `creado_por` — y su guard de reentrada solo protege llamadas
-- ANIDADAS (`pg_trigger_depth() > 1`), no esta, que es de primer nivel. Mismo
-- patron ya escrito en contexto/patrones_tecnicos.md -> "El dato tiene un
-- dueño" para backfills masivos: se desactivan los triggers de fila para las
-- dos UPDATE de este traspaso, que solo tocan `creado_por` y no necesitan que
-- ningun trigger de negocio reaccione.
--
-- CAPTURAR `v_anterior` ANTES de escribir nada: si se releyera
-- `clients.propietario` despues del primer UPDATE, la comparacion seria
-- contra el valor NUEVO y no moveria nunca nada.
--
-- UNA SOLA UPDATE por tabla, con OR en el WHERE (nunca dos pasadas): una
-- factura enlazada a la vez por `contrato_id` y por `client_id` no se toca
-- dos veces ni deja dos filas en `correcciones_datos` para el mismo cambio.
--
-- RASTRO. Una fila en `correcciones_datos` por cada columna cambiada (mismo
-- patron que autoria.js), TODO dentro de la misma transaccion que el propio
-- traspaso: si algo revienta a mitad, no queda ni el cambio ni un rastro de
-- que se intento — mas seguro que un traspaso a medias con rastro parcial.
--
-- Revision previa 17-sep con Seguridad + Datos (revision #22,
-- CEO/revisiones/estado.json): los 5+5 hallazgos de las dos estan plegados
-- arriba y en el cuerpo de la funcion.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: traspasar_cliente_con_documentos
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260917070000_traspaso_cliente_arrastra_documentos.sql
--   supabase/migrations/20260917083601_traspaso_cliente_arrastra_documentos.sql
-- ============================================================================
