-- destructivo-ok: CREATE OR REPLACE VIEW sustituye la misma vista con una
-- columna mas al final -- ninguna columna existente se quita ni se reordena
-- (Postgres no deja insertar en medio en un CREATE OR REPLACE: 42P16 la
-- primera vez que se probo insertandola antes de `facturado`).
-- ════════════════════════════════════════════════════════════════════════════
-- unidades_estado: añade qué agente creó el contrato — 11-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Encargo del owner: en Proyectos, ver de un vistazo qué agente hizo el
-- contrato de cada unidad, sin abrir el contrato. `contratos.creado_por` ya
-- existe (email del autor); esta vista solo lo expone como
-- `contrato_creado_por`. El JS resuelve el email a nombre con un mapa
-- `usuarios.email → nombre` cargado aparte (RLS "el equipo se ve entre sí"
-- ya deja leerlo a cualquiera del equipo, no hace falta ser admin).
--
-- ⚠️ CREATE OR REPLACE VIEW resetea `security_invoker` a su default SIN avisar
-- (ya mordió dos veces en este proyecto: unidades_estado_vista_fase_zona
-- 10-ago, unidades_estado_precio_efectivo 26-ago). La vista real tenía
-- `security_invoker=true` — se re-declara aquí EN LA MISMA sentencia.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: resetea, sustituye, unidades_estado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260805024801_unidades_estado_con_obra.sql
--   supabase/migrations/20260807043910_contratos_facturas_visibilidad_por_agente.sql
--   supabase/migrations/20260810100129_unidades_estado_vista_fase_zona.sql
--   supabase/migrations/20260810101230_unidades_estado_restaura_security_invoker.sql
--   supabase/migrations/20260811035145_unidades_estado_solo_recibi.sql
--   supabase/migrations/20260812042114_estado_unidad_por_tipo_y_cobro_fix_view.sql
--   supabase/migrations/20260819044137_cobro_repartido_entre_unidades.sql
--   supabase/migrations/20260824035201_construccion_por_parcela.sql
--   supabase/migrations/20260826112241_unidades_estado_precio_efectivo.sql
--   supabase/migrations/20260902022413_unidades_estado_restaura_security_invoker_2.sql
--   supabase/migrations/20260911005624_unidades_estado_agente_creador.sql
--   supabase/migrations/20260911085553_unidades_estado_cobrado_suelo_obra.sql
--   supabase/migrations/20260911085617_unidades_estado_restaura_security_invoker_3.sql
--   supabase/migrations/20260915004928_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915005638_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260915100000_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915104500_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260916093309_unidades_codigo_orden_natural.sql
--   supabase/migrations/20260922011052_law71_desbloqueado_estando_firmado.sql
-- ============================================================================
