-- ============================================================================
-- Métricas de almacenamiento — 31-jul-2026
-- ----------------------------------------------------------------------------
-- Pregunta del owner: "¿cuál es el límite de Supabase? ¿qué pasa si se llena?"
-- Lo que pasa es que las SUBIDAS EMPIEZAN A FALLAR. Supabase no borra nada ni
-- avisa por su cuenta con antelación útil: rechaza la escritura. En esta suite
-- eso significa que una firma se completa, el PDF no se puede guardar y el
-- contrato queda sin sellar — por eso hace falta verlo venir, no enterarse.
--
-- DOS FUNCIONES, no una (añadido 31-jul-2026, migración *_interno): el cálculo
-- vive en `_uso_almacenamiento()`, sin permisos — la llaman el panel (a través
-- del wrapper) y el cron nocturno de `revisar_almacenamiento()`
-- (aviso_almacenamiento.sql), que corre como `postgres` y no tiene JWT, así
-- que compartir la función con el guard de `es_agente()` dentro la dejaría
-- fallando en silencio todas las noches. `uso_almacenamiento()` es el wrapper
-- con permiso que llama el panel — mismo resultado, con el filtro de quién
-- puede pedirlo. `pg_database_size` y el conteo sobre `storage.objects` no
-- están al alcance del rol `authenticated`, por eso las dos son SECURITY
-- DEFINER.
--
-- LÍMITES: los del plan contratado — Pro desde el 15-sep-2026 (100 GB de
-- ficheros, 8 GB de base de datos; antes Free, 1 GB / 500 MB). Si se sube de
-- plan otra vez, se cambian aquí los DOS valores por defecto de las DOS
-- funciones (los cuatro números) y ya — no hay forma de leer el plan de
-- facturación desde SQL ni desde el MCP de este entorno, así que es un
-- número escrito a mano y hay que acordarse de tocarlo (17-sep-2026: el panel
-- llevaba dos días diciendo el límite del Free con el Pro ya pagado).
-- ============================================================================

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: _uso_almacenamiento, uso_almacenamiento
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731043307_uso_almacenamiento.sql
--   supabase/migrations/20260731043420_uso_almacenamiento_ritmo_real.sql
--   supabase/migrations/20260731043524_uso_almacenamiento_interno.sql
--   supabase/migrations/20260917013026_uso_almacenamiento_plan_pro.sql
--   supabase/migrations/20260917060000_uso_almacenamiento_plan_pro.sql
-- ============================================================================
