-- ⚠️ SUPERSEDIDO el mismo día por proyectos_supervisados_separado.sql: esta
-- función (`usuario_asigna_proyecto`) tocaba `usuarios.proyectos`, que el
-- owner corrigió que NO es lo mismo que "de qué proyecto es encargado un
-- manager" — eso ahora vive en la columna `proyectos_supervisados` y en la
-- función `usuario_supervisa_proyecto`. Esta función YA NO EXISTE en la base
-- (se dropeó). Se deja el fichero como historial de por qué se hizo atómica
-- en primer lugar (el hallazgo de Seguridad de más abajo sigue aplicando
-- igual a la función nueva).
-- destructivo-ok: CREATE OR REPLACE FUNCTION es sustitucion/adicion, no retirada. Sin DELETE/TRUNCATE/RLS off.
-- ════════════════════════════════════════════════════════════════════════════
-- ASIGNAR/QUITAR UN PROYECTO A UN MANAGER, DE FORMA ATÓMICA — 11-sep-2026
-- ════════════════════════════════════════════════════════════════════════════
-- Hallazgo de Seguridad en la consulta de deploy (capa 1) sobre
-- intranet/proyectos/index.html: el guardado de managers desde la ficha del
-- proyecto calculaba el array `proyectos` nuevo sobre una copia cacheada al
-- abrir la ficha y lo sobrescribía entero. Si el mismo manager se tocaba casi
-- a la vez desde otra pantalla (/usuarios/ u otra ficha de proyecto), la
-- escritura que llegara segunda pisaba sin aviso la de la primera — pérdida
-- silenciosa de una asignación o una revocación, sobre una columna que
-- decide autorización.
--
-- Arreglo: un RPC que hace el array_append/array_remove EN LA BASE, en una
-- sola sentencia — no hay lectura-modificación-escritura en el cliente que
-- pueda quedarse atrasada. SECURITY DEFINER porque necesita escribir en
-- `usuarios` de otra persona (el permiso ya lo exige la policy real,
-- verificado en producción: «admin edita, pero no toca fila super_admin sin
-- serlo» = es_admin() AND puede('usuarios') AND (rol<>'super_admin' OR
-- es_super_admin())) — y por eso la función REPITE esa misma comprobación a
-- mano: un SECURITY DEFINER se salta la RLS de la tabla, así que si la
-- función no comprueba nada, cualquiera con EXECUTE tendría vía libre.
--
-- ⚠️ Ojo con un hallazgo de la MISMA revisión que resultó ser falso positivo:
-- se citó una migración vieja (`20260811053843_...`) que decía que la policy
-- de UPDATE de `usuarios` solo exigía `es_admin()`, sin `puede()`. Verificado
-- en vivo el 11-sep: la policy real SÍ incluye `puede('usuarios')`, y
-- `puede()` solo se salta las herramientas para `es_super_admin()`, no para
-- cualquier admin. El repo tiene migraciones desincronizadas de producción
-- (precedente: 33 el 9-sep) — un hallazgo de seguridad sobre una policy se
-- verifica contra `pg_policies` en vivo, nunca contra el .sql del repo.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: es, usuario_asigna_proyecto
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260807044931_clients_solo_admin_edita.sql
--   supabase/migrations/20260819155002_vencimientos_monto_y_pct_numericos.sql
--   supabase/migrations/20260909135217_crm_leads_tablas_y_policies.sql
--   supabase/migrations/20260911005009_usuario_asigna_proyecto_atomico.sql
--   supabase/migrations/20260921125405_law_facturas_enviada_no_se_borra.sql
-- ============================================================================
