-- Candado de base para rol/herramientas de usuarios (Seguridad, revisión previa 19-sep-2026,
-- encargos/20260919_lawang_v4_paridad_lanzamiento.md → Decisiones).
--
-- Motivo: la policy UPDATE de public.usuarios es
--   qual/with_check: es_admin() AND puede('usuarios') AND (rol <> 'super_admin' OR es_super_admin())
-- que solo impide ASCENDER a alguien a super_admin. No impide que cualquier admin (no super) con
-- el permiso 'usuarios' ascienda un agente a admin, ni que cambie el array `herramientas` de sí
-- mismo o de cualquier otro, vía API directa (sin pasar por la UI ni por la edge admin-usuarios).
-- «Solo el super_admin reparte poder» lo cumplía la edge al CREAR, no la base al EDITAR.
--
-- Este trigger cierra ese hueco: cualquier UPDATE que toque rol o herramientas sin ser
-- es_super_admin() falla. No toca la policy existente (sigue haciendo su parte) ni ninguna otra
-- columna de usuarios.

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: usuarios_bloquea_cambio_rol_herramientas, usuarios_candado_rol_herramientas
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260921110844_usuarios_trigger_bloquea_rol_herramientas.sql
-- ============================================================================
