-- ============================================================================
-- El contrato reserva la unidad, y la unidad lo sabe — 31-jul-2026
-- ----------------------------------------------------------------------------
-- Hasta hoy `unidades.contrato_id` existía pero lo rellenaba una persona a mano
-- desde /unidades/. O sea: el contrato podía decir "parcela A5" y el inventario
-- seguir enseñando A5 como disponible. Eso es una parcela vendible dos veces.
--
-- Ahora lo hace la BASE DE DATOS y no la aplicación, porque a `contratos` le
-- escriben tres sitios distintos —la app de contratos, la función de firma y
-- cualquier corrección por SQL— y una regla que vive en uno de los tres no se
-- cumple desde los otros dos.
--
-- QUÉ SE MUEVE SOLO Y QUÉ NO:
--   · contrato con parcela  →  la unidad queda `reservada` y apuntando a él
--   · contrato firmado      →  `vendida`
--   · se quita la parcela   →  la unidad vuelve a `disponible`
--   · se borra el contrato  →  la unidad vuelve a `disponible`
--   · `bloqueada` y `no_disponible` NO se tocan NUNCA: los pone una persona por
--     un motivo que la base no conoce (un litigio, una reserva verbal), y un
--     automatismo que los pisa es peor que no tener automatismo.
--
-- El AVANCE DE COBRO no se guarda en la unidad: se calcula al leerlo desde
-- `facturas`. Guardarlo sería una tercera copia del mismo dato que se queda
-- vieja en cuanto alguien anule una factura.
-- ============================================================================

-- ---- el contrato manda sobre la unidad -------------------------------------

-- ============================================================================
-- PUNTERO — el codigo vive en supabase/migrations (22-sep-2026)
-- ----------------------------------------------------------------------------
-- Esta carpeta guardaba una COPIA del SQL de cada migracion "para leerla".
-- Dos copias del mismo codigo se desincronizan solas (el 22-sep hubo que
-- sincronizar borrar_operacion.sql a mano cuatro veces en un dia). Desde hoy
-- aqui queda el porque (arriba) y el indice de donde esta el codigo:
--
-- Objetos: libera_unidad_sin_contrato, sincroniza_unidad_contrato, trg_libera_unidad, trg_sincroniza_unidad, unidades_estado
-- Fuente (la ultima es la vigente):
--   supabase/migrations/20260731065652_vinculo_contrato_unidad.sql
--   supabase/migrations/20260805024801_unidades_estado_con_obra.sql
--   supabase/migrations/20260810100129_unidades_estado_vista_fase_zona.sql
--   supabase/migrations/20260810101230_unidades_estado_restaura_security_invoker.sql
--   supabase/migrations/20260811035145_unidades_estado_solo_recibi.sql
--   supabase/migrations/20260812042114_estado_unidad_por_tipo_y_cobro_fix_view.sql
--   supabase/migrations/20260812042147_estado_unidad_por_tipo_y_cobro.sql
--   supabase/migrations/20260814070120_parcela_traspaso_carta_a_bloqueo.sql
--   supabase/migrations/20260814095601_traspaso_mismo_comprador_y_enlace.sql
--   supabase/migrations/20260814095850_traspaso_carta_sucedida_editable.sql
--   supabase/migrations/20260819044137_cobro_repartido_entre_unidades.sql
--   supabase/migrations/20260824035201_construccion_por_parcela.sql
--   supabase/migrations/20260826112241_unidades_estado_precio_efectivo.sql
--   supabase/migrations/20260828073214_rp00116_corrige_parcela_codigo.sql
--   supabase/migrations/20260902022413_unidades_estado_restaura_security_invoker_2.sql
--   supabase/migrations/20260910043844_carta_reserva_traspaso_por_prefijo.sql
--   supabase/migrations/20260911005624_unidades_estado_agente_creador.sql
--   supabase/migrations/20260911085553_unidades_estado_cobrado_suelo_obra.sql
--   supabase/migrations/20260911085617_unidades_estado_restaura_security_invoker_3.sql
--   supabase/migrations/20260914120341_exige_parcela_al_guardar.sql
--   supabase/migrations/20260915004928_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915005638_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260915100000_unidades_estado_cobro_solo_si_contrato_visible.sql
--   supabase/migrations/20260915104500_unidades_estado_deja_de_duplicar_el_gate.sql
--   supabase/migrations/20260916093309_unidades_codigo_orden_natural.sql
--   supabase/migrations/20260917012656_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260917040000_errores_de_guardado_al_grano.sql
--   supabase/migrations/20260921060542_libera_reservas_vencidas.sql
--   supabase/migrations/20260921080952_enlace_por_id_y_law73_reabierta.sql
--   supabase/migrations/20260921081711_law73_reabierta_ambito_por_codigo.sql
--   supabase/migrations/20260921082637_fix_regresion_liberado_en.sql
-- ============================================================================
