create table if not exists axisworks_meta_vigilancia_acciones (
  id bigint generated by default as identity primary key,
  cuando timestamptz not null default now(),
  adset_id text not null,
  campana text not null,
  accion text not null,           -- 'pausar_tope' | 'presupuesto_subir' | 'presupuesto_bajar' | 'presupuesto_omitido'
  motivo text not null,
  valor_antes numeric,
  valor_despues numeric,
  detalle text
);

-- Append-only de verdad: nadie modifica ni borra filas de esta tabla, ni siquiera el
-- propio panel. Mismo patron de RLS on + 0 politicas que axisworks_meta_vigilancia: solo
-- la service key (bypassa RLS) escribe, PostgREST con la anon/publishable key no ve nada.
alter table axisworks_meta_vigilancia_acciones enable row level security;

revoke all on axisworks_meta_vigilancia_acciones from anon, authenticated;

create index if not exists idx_vigilancia_acciones_cuando
  on axisworks_meta_vigilancia_acciones (cuando desc);
;
