-- destructivo-ok: revoca únicamente un privilegio de ejecución sobre una
-- función creada en la migración anterior de esta misma sesión
-- (20260914121500); no toca filas.
--
-- CORRECCIÓN sobre 20260914121500_comisiones_devengadas_manager_no_veia_al_closer.sql,
-- misma sesión: get_advisors(security) marcó
-- `_equipo_de_condicion_comision` como ejecutable por `anon` vía
-- /rest/v1/rpc/_equipo_de_condicion_comision. `revoke all ... from public`
-- NO basta -- Supabase concede EXECUTE a `anon` y `authenticated` por
-- separado, aparte de PUBLIC. Es la MISMA piedra ya documentada 3 veces en
-- el repo (20260729091818, 20260819135855, 20260821154831,
-- 20260914100100_condicion_tramos_revoca_execute_trigger) y que esta propia
-- migración volvió a pisar por no copiar la forma completa del `revoke`.
--
-- Riesgo práctico: bajo pero real -- a diferencia de
-- valida_suma_tramos_comision (que devuelve trigger y PostgREST no puede
-- invocar), esta función SÍ devuelve uuid y SÍ es invocable por RPC. Solo
-- devuelve un equipo_id (ya público vía equipos_venta), así que no filtraba
-- nada sensible -- pero `anon` no debe tener ejecución de nada en este
-- esquema, por norma del repo, y se cierra igual.
revoke all on function public._equipo_de_condicion_comision(uuid) from public, anon, authenticated;
grant execute on function public._equipo_de_condicion_comision(uuid) to authenticated;
