-- El respaldo del renombrado SandalWoods -> Sumba Hills (migracion 20260827020601)
-- se creo con `create table ... as select ...`. Un CTAS NO hereda la RLS de la tabla
-- de origen y nace sin ella, y en el esquema `public` de Supabase los privilegios por
-- defecto ya le dan a `anon` y `authenticated` SELECT/INSERT/UPDATE/DELETE/TRUNCATE.
-- Resultado: quedo abierta a cualquiera con la clave publicable.
--
-- Verificado desde fuera el 2-sep-2026, como anonimo y sin credencial de servicio:
--   GET  -> 206, content-range 0-0/73   (las 73 filas legibles)
--   POST -> 201 Created                 (fila insertada; sonda borrada acto seguido)
--
-- Lo grave no es que se lean 73 numeros de contrato. Es que el comentario de la tabla
-- documenta un rollback que hace UPDATE sobre `contratos` con JOIN por id contra ESTE
-- respaldo: cualquiera podia insertar filas con el id de un contrato real y el valor
-- que quisiera, y quien ejecutase el deshacer se lo habria escrito en `contratos.datos`.
-- Un TRUNCATE anonimo, ademas, borraba la unica forma de deshacer el renombrado.
--
-- Se activa RLS sin politicas: es una tabla de respaldo manual, no la lee ningun cliente
-- (solo la nombra su propia migracion). Sin politicas, anon y authenticated no ven nada
-- y `service_role` la sigue usando con normalidad. Es el mismo patron que ya siguen las
-- otras 10 tablas internas de este proyecto.
alter table public._respaldo_resort_sandalwoods enable row level security;;
