-- R8: solapamiento de audiencia (targeting_historial) + exclusion de segmento
-- (exclusiones_segmento). Pedido del owner 28-ago-2026, autorizado tras revision previa
-- con Seguridad+Datos+Marketing. Mismo patron exacto que axisworks_meta_vigilancia_acciones:
-- RLS on + 0 politicas -- solo la service key de infraestructura/panel-web/server.py
-- lee/escribe, nunca `anon`.
--
-- El dato tiene un dueño (contexto/patrones_tecnicos.md): Meta es la fuente REAL del
-- targeting en vivo; esta tabla es una COPIA CONGELADA con hash+fecha para poder
-- reconstruir cuando un targeting era "de fiar" (estable) sin tener que re-preguntar a
-- Meta cada vez -- Meta no guarda ese historial, solo el valor actual.

create table if not exists public.axisworks_meta_targeting_historial (
  id bigint generated by default as identity primary key,
  adset_id text not null,
  capturado_en timestamptz not null default now(),
  targeting jsonb not null,
  hash text not null,
  origen text not null default 'vuelta_automatica'
);

comment on table public.axisworks_meta_targeting_historial is
  'R8 (server.py -> vigilar_ads()): snapshot del targeting en vivo de cada adset ACTIVE, '
  'una fila por VALOR distinto (dedup por hash, no una fila por vuelta). Sirve para '
  'reconstruir cuando un valor de targeting fue "linea base fiable" -- 3 capturas '
  'identicas seguidas, ver _vigila_r8_targeting_snapshot en server.py -- que R8.1 puede '
  'reponer si detecta solapamiento de audiencia entre dos adsets sin diferenciar. '
  'RLS on + 0 politicas: solo la service key de panel-web lee/escribe.';

create index if not exists axisworks_meta_targeting_historial_adset_idx
  on public.axisworks_meta_targeting_historial (adset_id, capturado_en desc);

alter table public.axisworks_meta_targeting_historial enable row level security;

create table if not exists public.axisworks_meta_exclusiones_segmento (
  id bigint generated by default as identity primary key,
  adset_id text not null,
  campana text not null,
  edad_min int not null,
  edad_max int not null,
  genero text not null,
  excluido_en timestamptz not null default now(),
  revertido_en timestamptz,
  motivo text not null,
  clics int not null,
  gasto numeric not null,
  targeting_antes jsonb not null,
  targeting_despues jsonb not null
);

comment on table public.axisworks_meta_exclusiones_segmento is
  'R8.4 (server.py -> vigilar_ads()): registro reversible de cada segmento edad+genero '
  'excluido por 0 leads con piso de clics/gasto cumplido en 14 dias (maximo 1 exclusion '
  'por adset cada 7 dias). revertido_en NULL = la exclusion sigue activa en Meta; se '
  'rellena A MANO cuando el owner deshace el cambio en Meta Y aqui, para que el '
  'historial no mienta sobre lo que esta vivo hoy. targeting_antes/targeting_despues '
  'guardan el JSON exacto para revertir sin adivinar. RLS on + 0 politicas: solo la '
  'service key de panel-web lee/escribe.';

create index if not exists axisworks_meta_exclusiones_segmento_adset_idx
  on public.axisworks_meta_exclusiones_segmento (adset_id, excluido_en desc);

alter table public.axisworks_meta_exclusiones_segmento enable row level security;
;
